- organization-bootstrap/environments/main.tf
- organization-bootstrap/environments/outputs.tf
- organization-bootstrap/environments/variables.tf
Let's all work on the main repo
> Merge ludo's branch from forked repo

- .ci/cloudbuild.lint.yaml
- .ci/scripts/check_boilerplate.py
- organization-bootstrap/environments/providers.tf
- organization-bootstrap/environments/variables.tf
- organization-bootstrap/environments/versions.tf
> Turn on ci, add linting and boilerplate steps

- foundations/environments/README.md
- foundations/environments/main.tf
- foundations/environments/variables.tf
This moves XPN role assignment for environment service accounts from the org to the folder, enforcing proper separation at the environment level.
> Assign XPN roles at the folder level in the per-environment foundation example

- foundations/business-units/main.tf
- foundations/environments/main.tf
- infrastructure/shared-vpc/main.tf
This reverts the project module to the last good version before output dependency was broken, until the [project factory issue](https://github.com/terraform-google-modules/terraform-google-project-factory/issues/308) is fixed.
> Revert project module version

- foundations/business-units/README.md
- foundations/business-units/backend.tf.sample
- foundations/business-units/main.tf
- foundations/business-units/outputs.tf
- foundations/business-units/terraform.tfvars.sample
- foundations/business-units/variables.tf
- modules/folders-unit/README.md
- modules/folders-unit/locals.tf
- modules/folders-unit/main.tf
- modules/folders-unit/variables.tf
Alex, spent some time on the bu folder and module. Apart from some minor cleanup I adopted a different approach, which of course makes sense to me but needs your opinion.
My thinking follows two concepts:
- the foundations example is an example not a module, so it should offer some high level customization through variables for core resources (project, GCS, naming, org, etc.) but it should be explicit in `main.tf` for the business units; this also matches what we saw with the customer we worked with together who is using the prototype of this, where main becomes the documentation for the business unit specifics
- having complex variables which are used only once, especially where those are not a low level platform choice (region, etc.) but model the customer usecase makes the example …
> Streamline bu example and module

- modules/compute-vm-cos-coredns/main.tf
- modules/compute-vm-cos/README.md
- modules/compute-vm-cos/cloud-config-file.yaml
- modules/compute-vm-cos/cloud-config.yaml
- modules/compute-vm-cos/cloud-config/coredns.yaml
- modules/compute-vm-cos/cloud-config/generic.yaml
- modules/compute-vm-cos/main.tf
- modules/compute-vm-cos/outputs.tf
- modules/compute-vm-cos/variables.tf
This introduces a generic COS module and updates the compute-vm-cos-coredns to use it
> Split COS to a generic module

- infrastructure/hub-and-spoke-peering/main.tf
- infrastructure/hub-and-spoke-vpn/main.tf
- infrastructure/onprem-google-access-dns/main.tf
- infrastructure/shared-vpc-gke/main.tf
- modules/net-vpc/README.md
- modules/net-vpc/main.tf
- modules/net-vpc/variables.tf
- tests/modules/net_vpc/fixture/variables.tf
- tests/modules/net_vpc/test_plan_subnets.py
This changes `modules/net-vpc` to support subnets with the same name in different regions. I had to adapt the maps to accept subnet `region/name` keys instead of just `name`, which makes the end-to-end examples a bit uglier in some cases.
For that reason, If you prefer to not merge this and keep as it is I would understand, as in the end this repo is about simple/readable modules.
> subnets with the same name in different regions

- modules/gke-cluster/main.tf
I ended up in the `gke-cluster` module from [Shared VPC/GKE](https://github.com/terraform-google-modules/cloud-foundation-fabric/tree/master/infrastructure/shared-vpc-gke) because I wanted to configure various aspects of the node-pool. A note like this would have saved me having to figure out why we don't take node_config params to the `gke-cluster` module.
> Adds clarification to gke-cluster module for node_config

- modules/compute-mig/main.tf
- modules/compute-mig/outputs.tf
- modules/net-ilb/main.tf
- modules/net-ilb/outputs.tf
- tests/modules/compute_mig/__init__.py
- tests/modules/compute_mig/fixture/main.tf
- tests/modules/compute_mig/fixture/variables.tf
- tests/modules/compute_mig/test_plan.py
A single health check resource with dynamic blocks for all types does not seem to work anymore, as tests are failing. This changes the `net-ilb` and `compute-mig` modules so that there's now one health check resource per type. A future PR might split out health checks int their own separate module so as to avoid code duplication.
> Fix health checks in net-ilb and compute-mig modules

- modules/cloud-config-container/cos-generic-metadata/README.md
- modules/cloud-config-container/cos-generic-metadata/cloud-config.yaml
- modules/cloud-config-container/cos-generic-metadata/main.tf
- modules/cloud-config-container/cos-generic-metadata/outputs.tf
- modules/cloud-config-container/cos-generic-metadata/variables.tf
- modules/cloud-config-container/envoy-traffic-director/README.md
- modules/cloud-config-container/envoy-traffic-director/files/customize.sh
- modules/cloud-config-container/envoy-traffic-director/files/envoy.yaml
- modules/cloud-config-container/envoy-traffic-director/main.tf
- modules/cloud-config-container/envoy-traffic-director/modules/cos-generic-metadata
- modules/cloud-config-container/envoy-traffic-director/outputs.tf
- modules/cloud-config-container/envoy-traffic-director/variables.tf
This is a Terraform/COS implementation of [Configuring a single Compute Engine VM for Traffic Director](https://cloud.google.com/traffic-director/docs/set-up-gce-vms?hl=hr#per_host_config) using the fabric framework. The main difference here is that while there they intercept node-internal traffic, we intercept traffic sent to the node externally via port 80. This does not include the TD resources, the plan is to use this on an end-to-end example that exposes a fleet of these instances behind a L7 XLB to use TD advanced routing features later on. Potentially this could also replace the Squid example at one point.
I've generalized the COS cloud-config generation, not sure if including the symlink is the appropriate way for a module to reference another one.
> Envoy with Traffic Director cloud-config

- modules/net-vpn-ha/main.tf
External gateway is not using the provided project_id, but defaulting to the provider one. This fails if the provider does not specify a project ID.
> adds project_id to external gateway

- modules/dns/README.md
- modules/dns/main.tf
- modules/dns/variables.tf
- modules/service-directory/README.md
- modules/service-directory/main.tf
- modules/service-directory/outputs.tf
- modules/service-directory/variables.tf
- modules/service-directory/versions.tf
Endpoint variable design is suboptimal, but it needs to take into account the fact that addresses will be dynamic in most cases, and be set in the same variable used to manage multiple resources. 
This module will probably be used to manage namespace, namespace IAM, and possibily services and their IAM, enabilng management of endpoints by other identities in different Terraform root modules or outside of Terraform.
One feature allowed by this change is implementing fine grained ACLs in Cloud DNS through Service Directory.
> New service directory module and sd zone type in DNS module

- modules/gke-cluster/main.tf
- modules/gke-cluster/variables.tf
Google supports CSI Driver for PD (https://cloud.google.com/kubernetes-engine/docs/how-to/gce-pd-csi-driver) which is also supported by TF Google Beta Provider (https://www.terraform.io/docs/providers/google/r/container_cluster.html#gce_persistent_disk_csi_driver_config)
> Added PD CSI Driver Addon support

- CHANGELOG.md
- infrastructure/shared-vpc-gke/main.tf
- modules/project/README.md
- modules/project/main.tf
- modules/project/outputs.tf
- modules/project/service_accounts.tf
This change rationalizes the way robot and default service accounts are exposed in the project module's outputs:
- all service accounts are exposed via a single `service_accounts` output
- the general/legacy service robot is exposed in `service_accounts.cloud_services`
- per-service robots are exposed in `service_accounts.robots`, eg `service_accounts.robots.container-engine`
- default service accounts are exposed in `service_accounts.default`, eg `service_accounts.default.compute`
Adding extra robot service accounts is done via the `local.service_accounts_robot_services` variable in the `service_accounts.tf` file which has been added in this PR.
> Better service account outputs in project module

- modules/iam-service-accounts/main.tf
- modules/iam-service-accounts/outputs.tf
- modules/iam-service-accounts/variables.tf
- tests/modules/iam_service_accounts/__init__.py
- tests/modules/iam_service_accounts/fixture/main.tf
- tests/modules/iam_service_accounts/fixture/variables.tf
- tests/modules/iam_service_accounts/test_plan.py
This updates a few leftovers from the old versions in the service account module, and hopefully makes outputs more resilient to corner cases like a service account being deleted outside of Terraform, where old outputs tended to raise errors.
The changes should be backward-compatible.
> Refactor service account module outputs

- CHANGELOG.md
- modules/dns/README.md
- modules/dns/main.tf
- modules/dns/outputs.tf
- modules/dns/versions.tf
`dns_keys` output added to the `dns` module, so things like DS entry will be outputed if DNSSEC configuration is provided
> dns_keys output added to the dns module

- modules/project/README.md
- modules/project/main.tf
- modules/project/outputs.tf
- modules/project/service_accounts.tf
- modules/project/variables.tf
- tests/modules/project/fixture/variables.tf
- tests/modules/project/test_plan.py
This allows using the project module to configure and customize pre-existing projects, without having to import them manually in state. It introduces count in the project resource, which works as far as I can understand but might need some extra testing especially with destroy.
This also adds a variable to optionally configure project API activation, useful in the situations above where you're referencing a pre-existing project, and need to activate extra APIs but don't want them to disable any depend APIs that were previously enabled.
> Make project creation optional in project module

- CHANGELOG.md
- modules/project/README.md
- modules/project/main.tf
- modules/project/outputs.tf
- modules/project/variables.tf
This adds support for Shared VPC at the project level, which is needed whenever you're not doing prototypes inside an existing project, and especially useful if you're managing a pre-existing project and VPC.
> Support Shared VPC in project module

- cloud-operations/asset-inventory-feed-remediation/main.tf
- infrastructure/hub-and-spoke-peering/main.tf
- infrastructure/hub-and-spoke-vpn/main.tf
- infrastructure/onprem-google-access-dns/main.tf
- infrastructure/shared-vpc-gke/main.tf
- modules/compute-vm/README.md
- modules/compute-vm/main.tf
- modules/compute-vm/variables.tf
- tests/modules/compute_vm/fixture/main.tf
- tests/modules/compute_vm/fixture/variables.tf
- tests/modules/compute_vm/test_plan_zones.py
This change allows supporting multiple zones in the `compute-vm` module, which is useful when creating multiple instances to get the multi-zone SLA. It also makes the `zones` variable optional, defaulting to the `b` zone in the region if no zones are specified.
> Support multiple zones in compute-vm module

- modules/bigquery-dataset/main.tf
#117 
- Added the line `provider = google-beta` for the resource "google_bigquery_dataset_access" under /modules/bigquery-dataset
- The module now runs without any problems and also formatted the files within the subdirectory after the changes.
> Added google-beta provider for dataset-access resource

- modules/dns/README.md
- modules/dns/main.tf
- modules/dns/variables.tf
- modules/organization/outputs.tf
This is code to make it optional to create the managed zone in the DNS module.
With this, it would be possible to split-up the record-sets in multiple modules.
> Add the option to not create a DNS managed zone

- CHANGELOG.md
- modules/gcs/README.md
- modules/gcs/main.tf
- modules/gcs/variables.tf
- modules/net-address/README.md
- modules/net-address/main.tf
- modules/net-address/outputs.tf
- modules/net-address/variables.tf
- modules/net-address/versions.tf
- modules/net-vpn-ha/README.md
- modules/net-vpn-ha/main.tf
- modules/net-vpn-ha/outputs.tf
- modules/net-vpn-ha/variables.tf
- tests/modules/net_address/__init__.py
- tests/modules/net_address/fixture/main.tf
- tests/modules/net_address/fixture/outputs.tf
- tests/modules/net_address/fixture/variables.tf
- tests/modules/net_address/test_plan.py
- tests/modules/net_vpc/test_plan_subnets.py
This adds support for specifying internal address purposes, which is [only supported from version 3.28.0](https://github.com/hashicorp/terraform-provider-google-beta/blob/master/CHANGELOG.md#3280-june-29-2020) of the `google-beta` provider, so this requirement is also set in the module.
The module's interface has always been a bit ugly, and it's even uglier now that a new variable has been added. I would love breaking compatibility and putting all internal IP configuration options in a single `internal_address_config` variable. Upside is a cleaner interface more similar to other modules, downside is one needs to set all three configuration items (`null` can be used of course) even if a single one needs to be specified.
WDYT?
> Add support for internal address purpose (and possibly refactor variables)

- CHANGELOG.md
- modules/folders-unit/main.tf
- modules/gcs/README.md
- modules/gcs/main.tf
- modules/gcs/variables.tf
- tests/modules/gcs/fixture/main.tf
- tests/modules/gcs/fixture/variables.tf
- tests/modules/gcs/test_plan.py
This PR is to reflect the deprecation of bucket_policy_only in favor of uniform_bucket_level_access in the terraform provider (https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.38.0).
To stay consistent with the default behavior of the module, the default for uniform_bucket_level_access is set to `true` to override the default in storage API which is `false`.
I thought it was wise, but I could be wrong.
> Change bucket_policy_only into uniform_bucket_level_access in GCS module

- modules/net-address/versions.tf
google-beta provider version 3.28.0 can no more be fetched by Terraform, updated the version to latest
> provider version update

- modules/cloud-config-container/nginx/README.md
Added the "depends_on" attribute for views to be created only after all the tables are created to avoid failure.
Please check terraform-google-modules#145
This should help the user avoid the error "The table xxxxxx does not exist when creating a view.
> Updated the main.tf for bigquery-datasets for creating views

- modules/gke-nodepool/README.md
- modules/gke-nodepool/main.tf
- modules/gke-nodepool/outputs.tf
- modules/gke-nodepool/variables.tf
- networking/hub-and-spoke-peering/main.tf
- networking/shared-vpc-gke/README.md
- networking/shared-vpc-gke/main.tf
- networking/shared-vpc-gke/outputs.tf
- tests/modules/gke_nodepool/__init__.py
- tests/modules/gke_nodepool/fixture/main.tf
- tests/modules/gke_nodepool/fixture/variables.tf
- tests/modules/gke_nodepool/test_plan.py
- tests/networking/shared_vpc_gke/test_plan.py
This change adds support for an optional internally-manages service account to the GKE nodepool module like we have for the GCE module, fixing #62.
It also shortens the node configuration variables by renaming their prefix from `node_config_` to `node_` for readability, breaking compatibility with previous versions.
A module test has also been added to validate the service account / scopes change.
> Add support for internal service account to GKE nodepool module

- modules/gke-nodepool/README.md
- modules/gke-nodepool/main.tf
- modules/gke-nodepool/variables.tf
This PR addresses the need to have working taints on gke nodepools.
Automatic transformation via local variables from list(string) to the map google provider expects.
Example usage:
```hcl
node_taints = [
"sighup.io/role=app:NoSchedule"
]
```
> Adding node taints on gke nodepool

- modules/gke-nodepool/README.md
- modules/gke-nodepool/main.tf
- modules/gke-nodepool/variables.tf
Add the possibility to use a Customer Managed Encryption Key to encrypt the boot disk attached to each node in the node pool.
Node config reference: 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_config
Cloud KMS reference: 
https://cloud.google.com/compute/docs/disks/customer-managed-encryption
> Add boot_disk_kms_key to node_config

- modules/iam-service-accounts/README.md
Change curl www.onprem.example.com -s |grep h1 
with 
curl www.onprem.example.org -s |grep h1
> onprem-google-access-dns readme typo

- foundations/business-units/main.tf
Fix for the parent folder of the audit-project. it was set to root-node instead of shared-folder as indicated into the overview diagram.
> Changed parent folder from root_node to shared-folder into the audit-project example code.

- modules/cloud-config-container/squid/README.md
- modules/cloud-config-container/squid/cloud-config.yaml
- modules/cloud-config-container/squid/docker/Dockerfile
- modules/cloud-config-container/squid/docker/cloudbuild.yaml
- modules/cloud-config-container/squid/docker/entrypoint.sh
- modules/cloud-config-container/squid/main.tf
- modules/cloud-config-container/squid/squid.conf
- modules/cloud-config-container/squid/variables.tf
This PR
- Includes Dockerfile for the squid container used by `modules/cloud-config-container/squid/`
- Updates `modules/cloud-config-container/squid/` to support both allow lists and deny lists.
> Update squid cos container

- modules/net-vpn-dynamic/README.md
- modules/net-vpn-dynamic/main.tf
- modules/net-vpn-dynamic/variables.tf
- modules/net-vpn-ha/README.md
- modules/net-vpn-ha/variables.tf
- networking/hub-and-spoke-vpn/main.tf
- networking/onprem-google-access-dns/main.tf
This allows setting a different router for specific tunnels associated with a single VPN gateway.
> Add support for per-tunnel routers to VPN dynamic and HA

- modules/project/versions.tf
The new essential contacts resource uses the beta provider.
> Set version for google-beta provider in project module

- modules/folder/README.md
- modules/folder/main.tf
- modules/folder/variables.tf
- modules/logging-bucket/README.md
- modules/logging-bucket/main.tf
- modules/logging-bucket/outputs.tf
- modules/logging-bucket/variables.tf
- modules/organization/README.md
- modules/organization/main.tf
- modules/organization/variables.tf
- modules/project/README.md
- modules/project/main.tf
- modules/project/variables.tf
- tests/modules/folder/fixture/variables.tf
- tests/modules/folder/test_plan_logging.py
- tests/modules/logging_bucket/__init__.py
- tests/modules/logging_bucket/fixture/main.tf
- tests/modules/logging_bucket/fixture/variables.tf
- tests/modules/logging_bucket/test_plan.py
- tests/modules/organization/fixture/variables.tf
- tests/modules/organization/test_plan_logging.py
- tests/modules/project/fixture/variables.tf
- tests/modules/project/test_plan_logging.py
This PR:
- Introduces a new module `logging-bucket` to create [Cloud Logging Buckets](https://cloud.google.com/logging/docs/storage#logs-buckets)
- Adds support to create logging sinks using logging buckets as the destination
- Extends existing logging sinks to support per-sink exclusions
> Support for Cloud Logging buckets

- modules/dns/main.tf
- tests/modules/dns/fixture/main.tf
- tests/modules/dns/fixture/variables.tf
- tests/modules/dns/test_plan.py
This fixes a bug in private DNS zones, where visibiity for at least one VPC was required.
> Allow DNS zones visible to no VPCs

- modules/folder/README.md
- modules/folder/main.tf
- modules/folder/variables.tf
- modules/organization/README.md
- modules/organization/main.tf
- modules/organization/variables.tf
- modules/project/README.md
- modules/project/main.tf
- modules/project/variables.tf
- tests/modules/organization/fixture/main.tf
- tests/modules/organization/fixture/variables.tf
- tests/modules/organization/test_plan.py
This integrates customizations we're making for my current customer, where IAM at the resource hierarchy level is tightly coupled with groups, which are vetted by the security team as a unit, together with their associated roles and point of application (org, folder, project).
Directly supporting this model allows much better readability in the resulting Terraform code, and emphasises the documentation part of IaC, which is one of the core features we aim to support in Fabric.
The feature is implemented via authoritative bindings, as an integral part of the security approval is the assurance that no other bindings are applied outside of this process, but is implemented in a lightweight fashion so that it can be used together with the `iam` variable, to support mixed use-cases or …
> Add support for group-based IAM to resource management modules

- networking/shared-vpc-gke/README.md
- networking/shared-vpc-gke/main.tf
- networking/shared-vpc-gke/outputs.tf
- networking/shared-vpc-gke/variables.tf
This allows quicker creation of the svpc example when a GKE cluster is not needed. I will use this in the upcoming OpenShift example.
> Make cluster creation optional in Shared VPC example

- cloud-operations/asset-inventory-feed-remediation/README.md
- cloud-operations/asset-inventory-feed-remediation/main.tf
- cloud-operations/asset-inventory-feed-remediation/outputs.tf
- modules/project/outputs.tf
- modules/project/service_accounts.tf
- tests/cloud_operations/asset_inventory_feed_remediation/test_plan.py
- tests/cloud_operations/scheduled_asset_inventory_export_bq/test_plan.py
- tests/data_solutions/data_platform_foundations/test_plan.py
This PR update the CAI remediation example to create the feed directly from terraform instead of gcloud
> Update CAI example

- networking/ilb-next-hop/README.md
- networking/ilb-next-hop/assets/gw.yaml
- networking/ilb-next-hop/gateways.tf
- networking/ilb-next-hop/main.tf
- networking/ilb-next-hop/outputs.tf
- networking/ilb-next-hop/variables.tf
- networking/ilb-next-hop/vms.tf
- tests/networking/ilb_next_hop/test_plan.py
Changes the ILB as next hop example so that
- the README file mentions recent support for all protocols and symmetric hashing, and links to the official documentation
- sets of instances are now created in two zones to better reflect real-world scenarios
- gw configuration does not use `netplan` anymore to make sure network configuration is present at first boot
- VM anf forwarding rules addresses, and basic commands to SSH to instances and monitor backed health are provided in the Terraform outputs
> Update ILBaNH example (all protocols, symmetric hashing, multi-zone)

- modules/iam-service-account/main.tf
- modules/iam-service-account/outputs.tf
Generate the service account output statically based on the service
account name and parent project. This allows, among other things, to use
service accounts as map keys (e.g. to be used in the `iam` argument in
other modules).
With this  PR, the example below works as expected:
```terraform
module "project" {
source          = "./modules/project"
billing_account = "XXXX"
name            = "my-project"
parent          = "folders/YYYY"
}
module "sa1" {
source     = "./modules/iam-service-account"
project_id = module.project.project_id
name       = "newsa1"
}
module "folder" {
source = "./modules/folder"
parent = "folders/ZZZZ"
name   = "new folder"
iam = {
(module.sa1.iam_email) = ["roles/owner"]
}
}
```
> Compute service account email statically

- modules/iam-service-account/main.tf
I was getting the following error (on apply only, plans works fine)when trying to create an SA via a module for_each and setting permissions at the same time:
```
│ Error: Attempt to get attribute from null value
│ 
│   on .terraform/modules/projects_tf_infra.sa/modules/iam-service-account/main.tf line 62, in locals:
│   62:   resource_iam_email        = "serviceAccount:${local.service_account.email}"
│     │ local.service_account is null
│ 
│ This value is null, so it does not have any attributes.
```
This fixes it, as it uses the static version of the SA email if local.service_account is null.
However, I don't fully understand why local.service_account is null in this case. Let me know if you'd like to reproduce this locally to look further into this.
> Fix SA IAM dynamic interpolation

- cloud-operations/asset-inventory-feed-remediation/main.tf
- cloud-operations/dns-fine-grained-iam/main.tf
- cloud-operations/dns-shared-vpc/examples/shared-vpc-example/test.example
- data-solutions/cmek-via-centralized-kms/main.tf
- data-solutions/gcs-to-bq-with-dataflow/main.tf
- modules/compute-mig/README.md
- modules/compute-vm/README.md
- modules/compute-vm/main.tf
- modules/compute-vm/variables.tf
- modules/net-ilb/README.md
- networking/filtering-proxy/main.tf
- networking/hub-and-spoke-peering/main.tf
- networking/hub-and-spoke-vpn/main.tf
- networking/ilb-next-hop/gateways.tf
- networking/ilb-next-hop/vms.tf
- networking/onprem-google-access-dns/main.tf
- networking/private-cloud-function-from-onprem/main.tf
- networking/shared-vpc-gke/main.tf
- tests/modules/compute_vm/fixture/variables.tf
- tests/modules/compute_vm/test_plan_interfaces.py
- third-party-solutions/openshift/prepare.py
This only adds the parameter `nic_type` to compute-vm. I would consider creating a module for compute images in order to catch the issue that certain flags are already enabled in public images when enabling `GVNIC` as a guest os feature.
> Allow using gVNIC in compute-vm (#211)

- modules/gcs/main.tf
I've run into scenarios where Terraform attempts to create the gcs notification resource before the topic IAM binding and hence run into 403 issues. I've added an explicit depends on to avoid the scenario.
> added depends on topic iam binding

- modules/apigee-organization/README.md
- modules/apigee-organization/outputs.tf
Adding `envs` as export to apigee-organization module.
This helps users that want to reference the envs from their apigee-x-instance like so to ensure the instance is created before it is attached.
```hcl
module "apigee-x-instance" {
source    = "../../../../modules/apigee-x-instance"
name      = var.name
region    = var.region
cidr_mask = 22
apigee_org_id = "my-project"
apigee_environments = [
module.my_org.envs["eval1"].name,
module.my_org.envs["eval2"].name
]
}
```
> Adding Apigee Environments as output for apigee-organization module

- factories/subnets/outputs.tf
Adjusted module outputs so that it's easier to consume them when using the factory in a larger codebase.
> Added subnet id and self_link to outputs

- modules/__experimental/net-dns-policy-address/README.md
- modules/__experimental/net-dns-policy-address/main.tf
- modules/__experimental/net-dns-policy-address/outputs.tf
- modules/__experimental/net-dns-policy-address/variables.tf
Workaround for [this provider issue](https://github.com/hashicorp/terraform-provider-google/issues/3753).
> Experimental module to derive DNS inbound policy addresses

- CHANGELOG.md
- modules/net-vpc/main.tf
This aligns the `net-vpc` module with the changes introduced in #499
> Update net-vpc module to use beta provider for shared vpc resources.

- fast/stages/02-security/vpc-sc.tf
This moves spec/status definition in locals, and adds a new local,  to make it simpler to switch from/to dry run mode.
> Make it simpler to switch from/to dry run mode

- fast/stages/01-resman/organization.tf
This is a safe and sane org policy that should be recommended for most customers to prevent them from accidentally configuring internal dns in a way that has reduced availability
https://cloud.google.com/compute/docs/internal-dns#enforce_dns_by_policy
> Add Zonal DNS Only org policy

- fast/stages/03-project-factory/prod/README.md
- fast/stages/03-project-factory/prod/main.tf
- fast/stages/03-project-factory/prod/variables.tf
FAST PF was not applying after the latest changes to the factory.
Also, are we intentionally not using prefix in the FAST PF? Projects names are just using the filename of the yaml.
> Fix renamed argument to project factory module

- modules/compute-vm/README.md
- modules/compute-vm/tags.tf
- modules/compute-vm/variables.tf
- modules/folder/README.md
- modules/folder/tags.tf
- modules/folder/variables.tf
- modules/kms/README.md
- modules/kms/tags.tf
- modules/kms/variables.tf
- modules/organization/README.md
- modules/organization/outputs.tf
- modules/organization/tags.tf
- modules/organization/variables.tf
- modules/project/README.md
- modules/project/tags.tf
- modules/project/variables.tf
- tests/modules/organization/fixture/main.tf
- tests/modules/organization/fixture/variables.tf
- tests/modules/organization/test_plan_tags.py
This adds support for tag keys, tag values, IAM bindings and tag bindings to the organization, folder, project, kms and compute vm modules.
Support for additive IAM has not been added, as this would complicate the code quite a bit having to support multiple nested loops and guard against dynamically created resources in keys. It's much simpler to use plain old resources in code for that.
Bindings are only supported for the object being managed by the module, keeping with the spirit of our module design where we deal with one object and its dependencies/features at a time. So it's not possible to assign tags to folders and projects from the organization module for example, but to do that the folder or project module needs to be used for the bindings.
This fixes #267 for most [supported …
> Add support for resource management tags and tag bindings

- modules/cloud-function/README.md
- modules/cloud-function/main.tf
- modules/cloud-function/variables.tf
There is no way to provide whether to use uniform access level or not other than provide own bucket.
Using uniform access in anyway recommended by GCP approach. If someone has use case, where ACL's are required, then they can provide they own bucket.
This makes life easier for cases, where uniform access is mandated by organization policy.
Apart from that, I've fixed few things around versioning:
* missing activation of versioning
* adding to the lifecycle rule that it affects only non-current versions of objects (otherwise, function will lose it's code after specified time)
> Use uniform access on Cloud Functions buckets.

- modules/apigee-organization/README.md
- modules/apigee-organization/main.tf
- modules/apigee-organization/variables.tf
- tests/modules/apigee_organization/fixture/main.tf
Adding the `billing_type` variable from the [Apigee Organization](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_organization) resource to allow users to specify the billing explicitly.
> Add billing_type for Apigee Organization Module

- modules/apigee-x-instance/README.md
- modules/apigee-x-instance/variables.tf
- tests/modules/apigee_x_instance/fixture/variables.tf
- tests/modules/apigee_x_instance/test_plan.py
The parameters has changed to allow both a /22 for the runtime and a /28 for the master authorized network of an Apigee instance.
> Allow multiple CIDR blocks in the ip_range for Apigee Instance

- fast/stages/01-resman/README.md
- fast/stages/01-resman/branch-data-platform.tf
- fast/stages/01-resman/branch-networking.tf
- fast/stages/01-resman/branch-sandbox.tf
- fast/stages/01-resman/branch-security.tf
- fast/stages/01-resman/branch-teams.tf
- fast/stages/01-resman/organization.tf
- fast/stages/01-resman/outputs.tf
- fast/stages/01-resman/variables.tf
This allows changing the names used for secure tags in resource management, to address issues where tags with thosenames already exist.
> FAST: allow changing tag names from variables in resman

- examples/data-solutions/sqlserver-alwayson/instances.tf
The `template_file` provider is deprecated and not available for darwin_arm64. This PR replaces it with`templatefile()`
> Remove template_file provider references

- fast/stages/00-bootstrap/README.md
- fast/stages/00-bootstrap/identity-providers.tf
This removes unsupported attributes and adds supported ones to the Gitlab mapping used for Workload Identity Federation pools.
Tested with the following condition:
```hcl
cicd_repositories = {
bootstrap = {
branch            = "main"
identity_provider = "gitlab-ludomagno"
name              = "ludomagno/fast-test"
type              = "gitlab"
}
}
federated_identity_providers = {
gitlab-ludomagno = {
attribute_condition = "attribute.namespace_path==\"ludomagno\""
issuer              = "gitlab"
}
}
```
> Fix Gitlab WIF attributes

- fast/stages/00-bootstrap/log-export.tf
- fast/stages/00-bootstrap/organization.tf
- modules/folder/README.md
- modules/gcs/README.md
- modules/gcs/outputs.tf
- modules/organization/README.md
- modules/project/README.md
- Fix FAST audit logging (stage0) when pubsub is used as destination
- Split each organization-level logging sink of type `logging` to a separate logging bucket.
- Add convenience output `id` to `gcs` module
> Fix FAST audit logs when using pubsub as destination

- CHANGELOG.md
- modules/apigee-x-instance/README.md
- modules/apigee-x-instance/main.tf
- modules/apigee-x-instance/variables.tf
- tests/modules/apigee_x_instance/fixture/main.tf
- tests/modules/apigee_x_instance/test_plan.py
> Add `consumer_accept_list` to `apigee-x-instance`

- modules/gke-cluster/main.tf
- tests/modules/gke_cluster/__init__.py
- tests/modules/gke_cluster/fixture/main.tf
- tests/modules/gke_cluster/fixture/variables.tf
- tests/modules/gke_cluster/test_plan.py
- tests/modules/gke_nodepool/test_plan.py
> Fix addons for autopilot clusters, add tests for gke-cluster.

- fast/stages/01-resman/cicd-project-factory.tf
In the module branch-pf-dev-sa-cicd, the calls to the "format" function were missing the argument var.automation.federated_identity_pool.
> FAST - added missing format argument in branch-pf-dev-sa-cicd

- examples/factories/project-factory/README.md
- examples/factories/project-factory/main.tf
- tests/examples/factories/project_factory/fixture/projects/project.yaml
- tests/examples/factories/project_factory/fixture/variables.tf
> Allow interpolating SAs in project factory subnet IAM bindings

- fast/stages/01-resman/outputs-files.tf
01-resman failed when outpus_location was not specified. In case of using Cloud Build with SoureRepo for runninc terraform commands, outputs_location is unnecessary but the line 36 fails due to the null value. Need to have null check at the beginning.
> fixing to move without output_location

- modules/cloud-run/README.md
- modules/cloud-run/main.tf
- modules/cloud-run/variables.tf
- tests/modules/cloud_run/fixture/main.tf
- tests/modules/cloud_run/test_plan.py
This PR refactors the Cloud Run module so that revision template annotations can be set, via a new `revision_annotations` variable that mediates all the [available annotations](https://cloud.google.com/run/docs/reference/rest/v1/RevisionTemplate). It also changes the way config connector is specified and optionally created, to better fit in with the other annotations, and reduce variable space.
Fixes #769 
Fixes #772
> Refactor Cloud Run module

- modules/cloud-run/main.tf
1. Fix typo (min_scale instead of max_scale, probably just copy-paste error)
2. Brought these lines together, stylistically makes more sense
> typo fix (max_scale -> min_scale)

- modules/secret-manager/README.md
- modules/secret-manager/outputs.tf
Secret manager module output (versions) contains sensitive value and without that flag, terraform init and plan throws error. I have added the sensitive flag for that output in that module.
> Secret manager flag sensitive output

- modules/cloud-identity-group/README.md
- modules/cloud-identity-group/main.tf
- modules/cloud-identity-group/variables.tf
- tests/modules/cloud_identity_group/fixture/main.tf
- tests/modules/cloud_identity_group/fixture/variables.tf
Add support for MANAGERS role.
Associated bug is fixed: https://github.com/hashicorp/terraform-provider-google/issues/7616
> Support manager role in cloud identity group module

- examples/factories/README.md
- examples/factories/cloud-identity-group-factory/README.md
- examples/factories/cloud-identity-group-factory/main.tf
- examples/factories/cloud-identity-group-factory/output.tf
- examples/factories/cloud-identity-group-factory/outputs.tf
- examples/factories/cloud-identity-group-factory/variables.tf
- tests/examples/factories/cloud_identity_group_factory/__init__.py
- tests/examples/factories/cloud_identity_group_factory/fixture/data/group1@example.com.yaml
- tests/examples/factories/cloud_identity_group_factory/fixture/main.tf
- tests/examples/factories/cloud_identity_group_factory/test_plan.py
Create a Cloud Identity Group factory example.
> Cloud Identity Group factory

- fast/stages/00-bootstrap/main.tf
- fast/stages/01-resman/main.tf
Currently the creation of gcs buckets fails:
- regional vs. multi_regional condition is inverted
- it's MULTI_REGIONAL (with underscore)
> Fix automation gcs location

- examples/cloud-operations/asset-inventory-feed-remediation/main.tf
- examples/cloud-operations/dns-fine-grained-iam/main.tf
- examples/cloud-operations/dns-shared-vpc/main.tf
- examples/cloud-operations/glb_and_armor/main.tf
- examples/cloud-operations/packer-image-builder/main.tf
- examples/cloud-operations/quota-monitoring/main.tf
- examples/data-solutions/cloudsql-multiregion/main.tf
- examples/data-solutions/data-playground/main.tf
- examples/data-solutions/gcs-to-bq-with-least-privileges/main.tf
- examples/data-solutions/sqlserver-alwayson/main.tf
- examples/gke-serverless/multitenant-fleet/main.tf
- examples/networking/hub-and-spoke-peering/main.tf
- examples/networking/hub-and-spoke-vpn/README.md
- examples/networking/hub-and-spoke-vpn/main.tf
- examples/networking/ilb-next-hop/main.tf
- examples/networking/private-cloud-function-from-onprem/main.tf
- fast/stages/02-networking-nva/landing.tf
- fast/stages/02-networking-nva/spoke-dev.tf
- fast/stages/02-networking-nva/spoke-prod.tf
- fast/stages/02-networking-peering/landing.tf
- fast/stages/02-networking-peering/spoke-dev.tf
- fast/stages/02-networking-peering/spoke-prod.tf
- fast/stages/02-networking-vpn/landing.tf
- fast/stages/02-networking-vpn/spoke-dev.tf
- fast/stages/02-networking-vpn/spoke-prod.tf
- modules/project/README.md
- modules/project/outputs.tf
- modules/project/variables.tf
this commit:
- Disables API deactivation by default on project destruction
- Adds "jit" service accounts as explicit dependency to the `project_id` output
- Makes `project_id` and `number` outputs depend_on the same resources
> Change `modules/project` service_config default

- CHANGELOG.md
- tools/changelog.py
This adds support for keeping revision sub headings in unprocessed (i.e. cloned from the existing file) revisions.
> Fix changelog generator

- modules/cloudsql-instance/main.tf
- tests/modules/cloudsql_instance/test_plan.py
See issue 780: https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/780
> regional MySQL DBs - automatic backup conf

- modules/project/README.md
- modules/project/service-accounts.tf
- modules/project/variables.tf
Project module creates default service account for (depending on the services enabled) for compute and app services and provided the Editor role by default . [Doc here](https://cloud.google.com/iam/docs/service-accounts#default)
To control the high privileged role, we can use terraform resource 'google_project_default_service_accounts'. I have added this resource in project module with an input variable to provide the setting for Keep, Deprivilege, disable or delete.
> Management of GCP project default service accounts

- modules/cloud-config-container/nginx-tls/files/customize.sh
The limitation for cert request is 64 characters in Common Name field:
```
problems making Certificate Request
140473219843520:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:crypto/asn1/a_mbstr.c:107:maxsize=64
```
This also puts the FQDN into `subjectAltName`, so we keep compatibility.
> nginx-tls: only use hostname part for TLS certificate

- blueprints/third-party-solutions/wordpress/cloudrun/README.md
1. "docker tag" has to include the Docker image version
2. The link to Cloud Shell was not working
> Fix docker tag command and link to Cloud Shell in WP blueprint

- CHANGELOG.md
- tools/changelog.py
The GH API sometimes don't return all pulls when using filters, and/or don't sort them properly. This makes it impossible to process pulls in streaming mode, and forces us to fetch them all and sort later. The tool becomes slower but we avoid updating skipping requests when updating CHANGELOG.
> Make changelog tool slower to work around inconsistencies in API results

- .github/workflows/tests.yml
- default-versions.tf
- tests/blueprints/conftest.py
- tests/examples/conftest.py
- tests/fast/conftest.py
- tests/modules/api_gateway/__init__.py
- tests/modules/api_gateway/test_plan.py
- tests/modules/conftest.py
- tests/requirements.txt
Testing what you suggested Julio.
> Run tests in parallel using `pytest-xdist`

- .github/workflows/tests.yml
- default-versions.tf
- tests/test-versions.tf
Reverts GoogleCloudPlatform/cloud-foundation-fabric#885
> Revert "Improve handling of tf plugin cache in tests"

- blueprints/cloud-operations/network-dashboard/README.md
- blueprints/cloud-operations/network-dashboard/variables.tf
- add variable documentation to the readme
- sort variables alphabetically
- validate values for `cf_version`
> Improve net dashboard variables

- modules/cloud-identity-group/main.tf
Important so we can flag these groups are TF managed and must not be manually updated.
> Add missing description field

- fast/stages/00-bootstrap/automation.tf
- fast/stages/01-resman/organization.tf
This is needed to fix the org policy-pocalypse triggered in FAST by the new implementation of org policies introduced in #930
> FAST: enable org policy API, fix run.allowedIngress value

- fast/stages/00-bootstrap/automation.tf
- fast/stages/00-bootstrap/cicd.tf
- fast/stages/01-resman/branch-data-platform.tf
- fast/stages/01-resman/branch-gke.tf
- fast/stages/01-resman/branch-networking.tf
- fast/stages/01-resman/branch-project-factory.tf
- fast/stages/01-resman/branch-sandbox.tf
- fast/stages/01-resman/branch-security.tf
- fast/stages/01-resman/branch-teams.tf
- fast/stages/01-resman/cicd-data-platform.tf
- fast/stages/01-resman/cicd-gke.tf
- fast/stages/01-resman/cicd-networking.tf
- fast/stages/01-resman/cicd-project-factory.tf
- fast/stages/01-resman/cicd-security.tf
> Use display_name instead of description for FAST service accounts

- modules/cloud-function/main.tf
- tests/modules/cloud_function_v2/__init__.py
- tests/modules/cloud_function_v2/fixture/bundle/main.py
- tests/modules/cloud_function_v2/fixture/main.tf
- tests/modules/cloud_function_v2/fixture/variables.tf
- tests/modules/cloud_function_v2/test_plan.py
Use local variable for storage source as it is done for v1 functions.
When bucket_name is provided on input of the module then creation of v2 function fails with an error:
```
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/[...]/modules/cloud-function/main.tf line 144, in resource "google_cloudfunctions2_function" "function":
│  144:         bucket = google_storage_bucket.bucket[0].name
│     │ google_storage_bucket.bucket is empty tuple
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
```
These changes fixes this error.
Copied tests from v1 functions to ensure that v2 function is working properly.
> cloud-functions v2 - fix reference to bucket_name

- CONTRIBUTING.md
I noticed that tests on my laptop worked very slow, especially compared to GitHub workflows or my workstation.
For example, on my laptop (connected through medium bandwidth, high latency 3G connection) speedup is 26x :
```bash
pytest tests/blueprints
=============================== 41 passed, 1 warning in 4182.25s (1:09:42) ===============================
```
vs:
```bash
TF_PLUGIN_CACHE_DIR=/tmp/tfcache pytest tests/blueprints
=============================== 41 passed, 1 warning in 159.37s (0:02:39) ===============================
```
On my workstation, the speed up is not so drastic, but stil significant (1.58x faster):
```bash
/usr/bin/time  pytest tests/blueprints
=============================== 41 passed, 1 warning in 315.45s (0:05:15) ===============================
324.84user …
```
> Add note about TF_PLUGIN_CACHE_DIR

- fast/assets/templates/workflow-github.yaml
- fast/stages/02-networking-nva/outputs.tf
- fast/stages/02-networking-peering/outputs.tf
- fast/stages/02-networking-separate-envs/outputs.tf
- fast/stages/02-networking-vpn/outputs.tf
This fixes a few things in the GitHub workflow
- include plan stderr in PR comment
- remove the code to post to the action status page, as that too has a message length limit
- additional step to error workflow if plan or apply fails, needed since the plan and apply steps have `continue-on-error: true` to allow the PR comment step to always run
- set `continue-on-error: true` on the step that posts the PR comment, and add a second step that posts a shorter comment which omits plan standard output in case of failure due to comment length
It also fixes file outputs for the networking stages, which raise an error if the `outputs_location` variable is not set.
> FAST: fixes to GitHub workflow and 02/net outputs

- modules/cloud-function/README.md
- modules/cloud-function/main.tf
- modules/cloud-function/variables.tf
Updated CF module to support customer build worker pools
> Worker pool support for `cloud-function`

- modules/pubsub/README.md
- modules/pubsub/main.tf
- modules/pubsub/outputs.tf
- modules/pubsub/variables.tf
Pubsub topics can now have schemas (https://cloud.google.com/pubsub/docs/admin#schemas). 
This PR adds an option to set the schema settings and create a new optional resource of type `google_pubsub_schema` attached to the `google_pubsub_topic`.
> Add schemas to Pubsub topic module.

- modules/pubsub/README.md
- modules/pubsub/main.tf
- modules/pubsub/variables.tf
Pubsub can now have subscriptions that write directly to BigQuery.
* https://cloud.google.com/pubsub/docs/bigquery
In the Google Terraform provider, this is configured using an additional block inside a `google_pubsub_subscription` resource.
* https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#nested_bigquery_config
This PR adds a new input variable to the `pubsub` module, to optionally add this block to some of the subscriptions defined in the module.
> Add BigQuery subcriptions to Pubsub module.

- .github/workflows/container-image.yml
Fixes `ERROR: denied: permission_denied: write_package` - this didn't show up on my tests under my org/user, most probably because the GoogleCloudPlatform org has different default workflow permissions set.
> Add missing `write_package` permission

- .github/labeler.yml
- .github/workflows/labeler.yml
This PR frees us from the burden of manually labelling pull requests.
> Use `actions/labeler` to automatically label pull requests

- fast/stages/00-bootstrap/README.md
Apparently we forgot to change this particular line in the README when moving 00-cicd to the extras/ folder
> fast README, one line fix: 00-cicd stage got moved to extras/

- modules/gke-cluster/main.tf
Resolves:
```
> terraform  apply  /var/tmp/1000/terraform/26c67a5d-6df1-48ef-b802-69c0ae4a0209.tfplan
module.cluster.google_container_cluster.cluster: Creating...
╷
│ Error: googleapi: Error 400: Duplicate resource: cpu., badRequest
│ 
│   with module.cluster.google_container_cluster.cluster,
│   on fabric/modules/gke-cluster/main.tf line 17, in resource "google_container_cluster" "cluster":
│   17: resource "google_container_cluster" "cluster" {
│ 
╵
```
> Fix memory/cpu typo in gke cluster module

- modules/apigee/README.md
- tests/modules/apigee/fixture/test.all.tfvars
Small change in the instance examples:
* An apigee org can only have 1 instance per region
* Every instance needs a /22 so they can't use the same cidr
> Apigee instance doc examples

- .github/workflows/container-image.yml
Fixes the following warning:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Replace `set-output` with env variable and remove single quotes on labels

- modules/apigee/main.tf
- tests/modules/apigee/fixture/test.env_only.tfvars
Fixed attribute reference issues for the `node_config` dynamic block.
Added test case for Apigee PAYG Environment Node Config.
Changes committed:
- modified:   `modules/apigee/main.tf`
- modified:   `tests/modules/apigee/fixture/test.env_only.tfvars`
> fix apigee PAYG env node config dynamic block

- blueprints/cloud-operations/terraform-enterprise-wif/tfc-workflow-using-wif/README.md
- blueprints/cloud-operations/terraform-enterprise-wif/tfc-workflow-using-wif/terraform.auto.tfvars.template
- blueprints/cloud-operations/terraform-enterprise-wif/tfc-workflow-using-wif/tfc-oidc/README.md
- blueprints/cloud-operations/terraform-enterprise-wif/tfc-workflow-using-wif/tfc-oidc/get_audience.sh
- blueprints/cloud-operations/terraform-enterprise-wif/tfc-workflow-using-wif/tfc-oidc/main.tf
- blueprints/cloud-operations/terraform-enterprise-wif/tfc-workflow-using-wif/tfc-oidc/outputs.tf
- blueprints/cloud-operations/terraform-enterprise-wif/tfc-workflow-using-wif/tfc-oidc/variables.tf
- blueprints/cloud-operations/terraform-enterprise-wif/tfc-workflow-using-wif/variables.tf
This PR is about using Workload Identity Federation with Terraform Cloud.
I propose this change because the **audience** in Terraform Cloud / Enterprise is already defined by the user in the `TFC_WORKLOAD_IDENTITY_AUDIENCE` environment variable for the workspace. So you can avoid to define it in the Terraform code as variable.
I take this opportunity to also correct a typo error in the documentation.
Thank you for the sample code, it helped me a lot to understand how to use Workload Identity Federation with Terraform Cloud.
Have a nice day ! 👋
> feat(blueprints): get audience from tfc environment variable

- fast/stages/00-bootstrap/README.md
Because of the billing API limitations, Though BigQuery dataset will be created within billing project, it will be empty.  BigQuery export have to be manually enabled in order for the data to be populated within the dataset. Since the Readme doesn't capture this, a note and reference link was added.
> FAST: add instructions for billing export to stage 0 README

- modules/bigtable-instance/README.md
- modules/bigtable-instance/main.tf
- modules/bigtable-instance/variables.tf
- tests/modules/bigtable_instance/fixture/main.tf
This adds the possiblity to define several clusters in a Bigtable instance, which enables replication in Bigtable.
Some of the configurations options are moved inside a `map` that defines the properties of each cluster.
These changes alter the interface of the module, so any previous code using this module will have to adapt to the new options interface.
> Add cluster replicas to Bigtable module.

- fast/stages/02-security/vpc-sc.tf
`02-security` stage by default is not creating the landing and prod perimeters, and the dev perimeter is missing `restricted_services`. This fixes it.
> fix restricted services not being added to the perimeter configurations

- modules/apigee/README.md
- modules/apigee/main.tf
- modules/apigee/variables.tf
- tests/modules/apigee/fixture/test.env_only_with_api_proxy_type.tfvars
- tests/modules/apigee/fixture/test.env_only_with_deployment_type.tfvars
- tests/modules/apigee/fixture/variables.tf
- tests/modules/apigee/test_plan.py
Add support for deployment_type and api_proxy_type in google_apigee_environment resource, for the Apigee module
> add new parameters support in apigee module

- blueprints/data-solutions/data-platform-foundations/README.md
- modules/project/service-accounts.tf
- tests/blueprints/apigee/bigquery-analytics/basic.yaml
- tests/blueprints/cloud_operations/asset_inventory_feed_remediation/test_plan.py
- tests/blueprints/cloud_operations/scheduled_asset_inventory_export_bq/test_plan.py
- tests/blueprints/cloud_operations/unmanaged_instances_healthcheck/test_plan.py
- tests/blueprints/data_solutions/data_platform_foundations/test_plan.py
- tests/blueprints/gke/binauthz/test_plan.py
- tests/blueprints/networking/private_cloud_function_from_onprem/test_plan.py
- tests/blueprints/serverless/api_gateway/test_plan.py
- tests/fast/stages/s00_bootstrap/simple.yaml
This PR enables the `cloudbuild.googleapis.com` on the project modules, which is needed in order to be able to have the cloudbuild service account created automatically on projects.
> Include cloudbuild API in project module

- modules/cloudsql-instance/README.md
- modules/cloudsql-instance/main.tf
- modules/cloudsql-instance/variables.tf
Add support for the point_in_time_recovery_enabled property in CloudSQL backup_configuration
Use optional() for configuration map in order to maintain backwards compatibility with previous configurations
> CloudSQL Backup Configuration: Support Point In Time Recovery

- modules/gke-cluster/main.tf
Add support for the cluster_autoscaling configuration block in the gke-cluster module when autopilot = true.
Previously this would fail because the enabled parameter could not be set with autoscaling enabled. Changed to set enabled = null and added support for the auto_provisioning_defaults configuration, primarily to allow for specification of a non-default service account
> Add Autopilot Support for cluster_autoscaling Configuration in GKE Module

- modules/project/README.md
- modules/project/service-accounts.tf
Provide explicit documentation when and which service identities require manual IAM grants.
> Add documentation about JIT-ed service accounts

- blueprints/data-solutions/data-playground/main.tf
Implement a 'lifecycle' block on 'google_notebooks_instance' to mitigate [issue 9164 in the Google provider](https://github.com/hashicorp/terraform-provider-google/issues/9164)
> Workaround to mitigate provider issue 9164

- modules/bigquery-dataset/README.md
- modules/bigquery-dataset/main.tf
- modules/bigquery-dataset/variables.tf
Add 'max_time_travel_hours ' support on BQ module with default value .
The current module cause a continue 'tf apply' change due to the missing default value.
```
~ resource "google_bigquery_dataset" "default" {
id                              = "projects/PROJECT_ID/datasets/DATASET_NAME"
- max_time_travel_hours           = "168" -> null
}
```
> Add 'max_time_travel_hours ' support on BQ module

- modules/gke-nodepool/main.tf
replaced .secondary_pod_range by var.pod_range.secondary_pod_range that is the object which contins create, cidr an name attributes.
> changed pod_range reference to include secondary_pod_range issue #1157

- modules/project/README.md
- modules/project/iam.tf
- tests/modules/project/examples/iam-additive-members.yaml
- tests/modules/project/examples/iam-additive.yaml
Allow robots names in additive IAM grants.
Regrettably all member names will be known after apply, hence changes in the tests.
> Allow additive IAM grants by robots name

- blueprints/data-solutions/data-platform-foundations/demo/dataflow-csv2bq/README.md
Added some light restructuring for the documentation on the Dataflow pipeline example and included two new example commands for launching the Dataflow pipeline for local development. One via DirectRunner for full local runs and one via DataflowRunner for tests on Dataflow.
> Additional documentation for the Data Platform Dataflow pipeline example

- fast/extras/0-cicd-github/main.tf
fix the missing 'module_prefix' in the 'locals' block.
> fix module_prefix in fast extras 0-cicd-github

- modules/net-ilb-l7/backend-service.tf
Internet and serverless NEGs (Cloud Run) don't use them and it's an error to add one in their backend services.
> Allow to not use any health check

- modules/net-ilb-l7/README.md
SNEGs don't use health checks and it's an error to add one in their backend services. 'terraform plan' doesn't detect it, only 'apply'.
> Don't define nor use health checks with SNEGs

- modules/gke-hub/README.md
- modules/project/README.md
- modules/project/service-accounts.tf
To provision ASM managed you [need to give permission to ASM service accounts](https://cloud.google.com/service-mesh/docs/managed/provision-managed-anthos-service-mesh#register_clusters_to_a_fleet)  on the project. Adding it to JIT list.
> adding meshconfig.googleapis.com to JIT list.

- blueprints/apigee/network-patterns/nb-glb-psc-neg-sb-psc-ilbl7-hybrid-neg/vpn.tf
- blueprints/networking/hub-and-spoke-vpn/vpn-dev-r1.tf
- blueprints/networking/hub-and-spoke-vpn/vpn-prod-r1.tf
- blueprints/networking/private-cloud-function-from-onprem/main.tf
- blueprints/serverless/cloud-run-corporate/main.tf
- fast/stages/2-networking-a-peering/vpn-onprem.tf
- fast/stages/2-networking-b-vpn/vpn-onprem.tf
- fast/stages/2-networking-b-vpn/vpn-spoke-dev.tf
- fast/stages/2-networking-b-vpn/vpn-spoke-prod-primary.tf
- fast/stages/2-networking-b-vpn/vpn-spoke-prod-secondary.tf
- fast/stages/2-networking-c-nva/vpn-onprem.tf
- fast/stages/2-networking-d-separate-envs/vpn-onprem-dev.tf
- fast/stages/2-networking-d-separate-envs/vpn-onprem-prod.tf
- modules/net-vpn-ha/README.md
- modules/net-vpn-ha/main.tf
- modules/net-vpn-ha/variables.tf
In draft for now as blueprints and FAST need to be aligned.
> Allow multiple peer gateways in VPN HA module

- modules/gke-hub/main.tf
- tests/modules/gke_hub/test_plan.py
Two fixes:
- the cluster [should be in the form of  "//container.googleapis.com/CLUSTER_RESOURCE_NAME" ](https://cloud.google.com/anthos/fleet-management/docs/register/gke?hl=it#register_your_cluster) - I don't think this is particularly relevant, but it's such a small change
- the condition on when to create the authority seemed to be inverted (it should be created if contains is true, but written that way I think it doesn't create it when contains is true)
> Fix Workload Identity for ASM in GKE hub module

- modules/compute-mig/health-check.tf
- modules/net-ilb/health-check.tf
* **compute-mig** and **net-ilb** module: https healthcheck mapped properly to local.hc.https (was previously mismapped to local.hc.http) #1185
> Fix HTTPS health check mismapped to HTTP in compute-mig and net-ilb modules

- modules/gke-cluster/main.tf
- modules/pubsub/README.md
- modules/pubsub/main.tf
- modules/pubsub/outputs.tf
- Fix issue with GKE cluster notifications topic creation logic.
- Output static topic ID from `pubsub` module.
> Fix issue with GKE cluster notifications topic & static output for pubsub module

- fast/stages/0-bootstrap/organization.tf
- tests/fast/stages/s0_bootstrap/simple.yaml
By default new orgs grant billing.creator and
resourcemanager.projectCreator to the whole domain[1]. This PR makes FAST remove the former binding during the bootstrap (the latter is already managed by FAST).
Fixes #1220
[1] https://cloud.google.com/resource-manager/docs/default-access-control
> Manage billing.creator role authoritatively in FAST bootstrap.

- modules/net-vpc/README.md
- modules/net-vpc/subnets.tf
- tests/modules/net_vpc/examples/factory.yaml
This allows using the same name for subnets in different regions, while still using the factory file name as a default if no subnet name has been explicitly set.
> Allow overriding name in net-vpc subnet factory

- fast/stages/1-resman/branch-gke.tf
GCS buckets in branch-gke.tf were missing the location and storage class handling. Every other bucket here has it.
> Fast: resman: location and storage class added to GKE GCS buckets

- modules/net-vpc/README.md
- modules/net-vpc/subnets.tf
- modules/net-vpc/variables.tf
- tests/modules/net_vpc/examples/subnet-iam.yaml
This addresses the long-standing request to implement support for subnet additive bindings in the `net-vpc` module.
It also simplifies the subnet factory IAM interface and aligns it with our usual interface in modules, replacing the `iam_groups`, `iam_users` and `iam_service_accounts` attributes with a single `iam` attribute. This change reduces internal complexity and cognitive overload, and should have a very limited impact on usage.
Fixes #1103
> Add support for `iam_additive` and simplify factory interface in net VPC module

- blueprints/data-solutions/data-platform-foundations/README.md
- blueprints/data-solutions/data-platform-foundations/terraform.tfvars.sample
> Fix variable terraform.tfvars.sample

- modules/cloud-config-container/simple-nva/README.md
- modules/cloud-config-container/simple-nva/main.tf
- modules/cloud-config-container/simple-nva/variables.tf
Users can now pass FRR BGP configs as strings and not just as paths to existing files. This is useful if templatefile is used in the caller module.
> simple-nva: add ability to parse BGP configs as strings.

- modules/ncc-spoke-ra/README.md
- modules/ncc-spoke-ra/main.tf
- modules/ncc-spoke-ra/variables.tf
* Users can now set route priorities
* Prefixes all GCP names with a prefix so the module can be instantiated multiple times in the same project
* Calls the variables and add suffixes 0 and 1 (instead of 1 and 2) to interfaces and peers to reflect the GCP nomenclature
> Improvements to NCC-RA spoke module.

- modules/cloud-run/main.tf
> Ignore changes to metadata.0.annotations in Cloud Run module

- modules/cloud-config-container/simple-nva/README.md
- modules/cloud-config-container/simple-nva/cloud-config.yaml
- modules/cloud-config-container/simple-nva/main.tf
- modules/cloud-config-container/simple-nva/variables.tf
The NVA is running COS which, by default, allows outgoing connections and accepts incoming connections only through the SSH service. This was causing issues with BGP sessions not being established between NVAs, this PR includes:
- default firewall configuration for well known protocols configured via FRR (ex. enabling BGPd will automatically opens port 179 on the NVA)
- added optional_firewall_open_ports variable to easily open ports for both TCP and UDP protocols on the NVA
- extended module documentation in README
> Added local firewall management (iptables) on the NVA for dealing with COS default deny on inbound connections

- fast/stages/3-project-factory/dev/README.md
Updating readme so that the provider and terraform variables section is identical to the documentation in the other stages.
> Update Provider and Terraform variables section

- blueprints/cloud-operations/network-dashboard/README.md
- blueprints/cloud-operations/network-dashboard/src/README.md
- blueprints/cloud-operations/network-dashboard/src/plugins/discover-group-networks.py
- blueprints/cloud-operations/network-dashboard/src/plugins/series-firewall-rules.py
- blueprints/cloud-operations/network-dashboard/src/plugins/series-networks.py
- blueprints/cloud-operations/network-dashboard/src/plugins/series-routes.py
- add explicit requirements for Python version at least 3.9
- add constraint on Shared VPC service projects and host project to both be in the monitoring scope
- fix issue with itertools.groupby which assumes the iterator to be already sorted when grouping by keys
The latter issue was causing duplicated metric to be written on Cloud Monitoring resulting in the following error:
_One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric_
> Network Dashboard improvements and bug fixing

- fast/stages/README.md
Fixed typo from "fatory" to "factory" in readme.
> Fixed type in readme for FAST stages

- modules/cloud-run/main.tf
Currently, the labels var is defined but not used, it is my understanding that this var should be used in the metadata main block of the `google_cloud_run_service` resource
> Use labels var in cloud-run module

- blueprints/serverless/cloud-run-explore/README.md
- blueprints/serverless/cloud-run-explore/main.tf
Now that IAP for Cloud Run is GA, the IAP service agent needs to be provisioned and granted access to invoke Cloud Run.
Fixes #1321
> IAP for Cloud Run GA

- modules/net-vpc/subnets.tf
The conditional statement, with tomap({}) will cause the following error under terraform 1.4.5
Error: Inconsistent conditional result types
│ 
│   on ../../../modules/net-vpc/subnets.tf line 20, in locals:
│   20:   _factory_data = var.data_folder == null ? tomap({}) : {
│   21:     for f in fileset(var.data_folder, "**/*.yaml") :
│   22:     trimsuffix(basename(f), ".yaml") => yamldecode(file("${var.data_folder}/${f}"))
│   23:   }
│     │ var.data_folder is "data/subnets/common"
│ 
│ The false result value has the wrong type: element types must all match for conversion to map.
> Inconsistent conditional result types error in net-vpc module

- modules/net-ilb-l7/main.tf
When renewing the certificate by updating the variable file, GCP will not let you update because it will try to delete the old certificate is been used by the target proxy. Updating lifecycle  with create_before_destroy will allow the certificate and attach to the proxy and then delete the old certificate.
> Certificate renewal through terraform 

- blueprints/data-solutions/vertex-mlops/metadata.yaml
This reorganizes the yaml to accommodate a breaking change we had to do for a [proto migration](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1493).  This is cosmetic and I have not changed any content. Validated using `cft blueprint metadata --validate`.
> chore: update metadata schema

- fast/stages/1-resman/branch-security.tf
it should be able to use automation project
as a quota project, hence it needs `serviceusage.serviceUsageConsumer` role
> fixed permissions for security stage SA

- blueprints/data-solutions/data-platform-foundations/README.md
- blueprints/factories/project-factory/README.md
- modules/net-ilb-l7/README.md
- modules/project/README.md
- blueprints/data-solutions/data-platform-foundations/README.md
- blueprints/factories/project-factory/README.md
- modules/net-ilb-l7/README.md
- modules/project/README.md
> Update to multiple README.md

- blueprints/data-solutions/vertex-mlops/metadata.yaml
Minor update to use tagline in the readme and use dir name as blueprint name.
> chore: update mlops blueprint metadata

- modules/logging-bucket/README.md
- modules/logging-bucket/main.tf
- modules/logging-bucket/variables.tf
We have a use case, Local Controls, that requires to configure CMEK with Logging buckets. This commit adds an optional variable to configure CMEK in the `logging-bucket` module. By default the Logging bucket won't use CMEK encryption.
To configure CMEK for Logging buckets it's also required to add the correct permissions to the bucket service account. For more information and a Terraform example, see:
https://cloud.google.com/logging/docs/routing/managed-encryption-storage
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config#example-usage
> Support CMEK encryption in logging-bucket module

- blueprints/networking/decentralized-firewall/validator/firewallSchema.yaml
- blueprints/networking/decentralized-firewall/validator/firewallSchemaAutoApprove.yaml
The Firewall Validator schema configuration contains a field `target_service_account`. This should be updated to `target_service_accounts` to match the `google_compute_firewall` Terraform resource argument:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_firewall#target_service_accounts
> Firewall Validator fix target_service_accounts ref

- fast/stages/1-resman/branch-sandbox.tf
If you have the `project_factory` feature enabled, but not the `sandbox` feature (as it's not a requirement on your org), when doing a `terraform apply` on `1-resman` it raises this errors as it's expecting the wrong feature when creating the sandbox SA
```
│ Error: Invalid index
│ 
│   on branch-sandbox.tf line 68, in resource "google_organization_iam_member" "org_policy_admin_sandbox":
│   68:   member = module.branch-sandbox-sa.0.iam_email
│     │ module.branch-sandbox-sa is empty tuple
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
```
> fix(stages): only add sandbox SA when `sandbox` feature is enabled

- CHANGELOG.md
- blueprints/networking/ha-vpn-over-interconnect/README.md
- modules/net-dedicated-vlan-attachment/README.md
- modules/net-dedicated-vlan-attachment/variables.tf
Updated wording in CHANGELOG.md
Updated “mtu” variable description in modules/net-dedicated-vlan-attachment/variables.tf
Fixed typo in blueprints/networking/ha-vpn-over-interconnect/README.md
Fixed typo in modules/net-dedicated-vlan-attachment/README.md
> Multiple Updates in READMEs and wording

- fast/stages/1-resman/README.md
- fast/stages/1-resman/organization.tf
- fast/stages/1-resman/variables.tf
- modules/organization/organization-policies.tf
- tests/modules/organization/test_plan_org_policies_modules.py
This adds support for a custom tag hierarchy to FAST stage 1, and includes simple aliasing to refer to the internally created IaC service accounts in tag value bindings.
```hcl
tags = {
org-policies = {
description = "Tag values used in organization policy conditions."
values = {
drs-allow-all = {
description = "Allow all in Domain Restricted Sharing."
iam = {
"roles/resourcemanager.tagUser" = ["sandbox"]
}
}
}
}
}
```
It also creates a new tag key that forms the base of the hierarchy of tag values for org policy conditions. This has a single default value for "DRS all" but can be extended by using the same tag key name in the custom variable shown above.
> Add custom tag support to FAST

- blueprints/data-solutions/data-platform-minimal/README.md
- blueprints/networking/README.md
- blueprints/serverless/README.md
- blueprints/serverless/cloud-run-corporate/README.md
> Fixing typos

- fast/assets/templates/workflow-github.yaml
- fast/assets/templates/workflow-sourcerepo.yaml
- fast/stages-multitenant/0-bootstrap-tenant/templates/workflow-github.yaml
- fast/stages-multitenant/0-bootstrap-tenant/templates/workflow-sourcerepo.yaml
- fast/stages-multitenant/1-resman-tenant/templates/workflow-github.yaml
- fast/stages-multitenant/1-resman-tenant/templates/workflow-sourcerepo.yaml
- fast/stages/0-bootstrap/templates/workflow-sourcerepo.yaml
- fast/stages/1-resman/templates/workflow-github.yaml
- fast/stages/1-resman/templates/workflow-sourcerepo.yaml
Bootstrap was bumped in #1414
my networking repo GH action was failing
> Bump TF version in all workflow templates to coincide with module requirements

- blueprints/data-solutions/data-platform-minimal/02-processing.tf
`container-egine` errors
```
│ Error: Invalid index
│ 
│   on ../../../../modules/project/shared-vpc.tf line 74, in resource "google_project_iam_member" "shared_vpc_host_robots":
│   74:     : "serviceAccount:${local.service_accounts_robots[each.value.service]}"
│     │ each.value.service is "container-egine"
│     │ local.service_accounts_robots is object with 177 attributes
│ 
│ The given key does not identify an element in this collection value.
```
> data-platform-minimal - correct typo

- blueprints/data-solutions/data-platform-minimal/02-processing.tf
error is 
```
│ Error: Unsupported attribute
│ 
│   on ../../../../blueprints/data-solutions/data-platform-minimal/02-processing.tf line 46, in locals:
│   46:     ? var.network_config.subnet_self_links.processingestration
│     │ var.network_config.subnet_self_links is object with 2 attributes
│ 
│ This object does not have an attribute named "processingestration".
╵
```
I'm guessing this should be `processing_transformation` the other option is `processing_composer`
> data-platform-minimal - 02-processing.tf typo

- blueprints/data-solutions/shielded-folder/README.md
I faced error during my deployment even though I created `data-engineers group`. Then I found out that variables file uses `gcp-data-engineers` as default. The same is valid for `data-security`.
reference lines in `variables.tf`:
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/261ad646a821851fb4c1e42d26fefa41e8aa371f/blueprints/data-solutions/shielded-folder/variables.tf#L68
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/261ad646a821851fb4c1e42d26fefa41e8aa371f/blueprints/data-solutions/shielded-folder/variables.tf#L69
> match readme groups with variables file

- blueprints/data-solutions/shielded-folder/README.md
In this PR I fix README to properly list roles needed to run the Shielded Folder blueprint.
> Fix Shielded folder README

- CHANGELOG.md
- blueprints/data-solutions/data-platform-foundations/README.md
- blueprints/data-solutions/data-platform-foundations/outputs.tf
- blueprints/data-solutions/data-platform-minimal/README.md
- blueprints/data-solutions/data-platform-minimal/outputs.tf
- fast/stages/3-data-platform/dev/README.md
- fast/stages/3-data-platform/dev/outputs.tf
- fast/stages/3-data-platform/dev/README.md
- fast/stages/3-data-platform/dev/outputs.tf
- CHANGELOG.md
- blueprints/data-solutions/data-platform-minimal/README.md
- blueprints/data-solutions/data-platform-minimal/outputs.tf
- blueprints/data-solutions/data-platform-foundations/README.md
> Updating a few files to fix typos

- fast/stages/2-networking-a-peering/data/dashboards/vpc_and_vpc_peering_group_quotas.json
- fast/stages/2-networking-b-vpn/data/dashboards/vpc_and_vpc_peering_group_quotas.json
- fast/stages/2-networking-c-nva/data/dashboards/vpc_and_vpc_peering_group_quotas.json
- fast/stages/2-networking-d-separate-envs/data/dashboards/vpc_and_vpc_peering_group_quotas.json
- fast/stages/2-networking-e-nva-bgp/data/dashboards/vpc_and_vpc_peering_group_quotas.json
- tests/fast/stages/s2_networking_a_peering/stage.yaml
- tests/fast/stages/s2_networking_b_vpn/stage.yaml
- tests/fast/stages/s2_networking_c_nva/stage.yaml
- tests/fast/stages/s2_networking_d_separate_envs/stage.yaml
- tests/fast/stages/s2_networking_e_nva_bgp/stage.yaml
Adding a monitoring dashboard for key VPC and VPC peering group network quotas that most of our customers care about.
I added this only in the networking-a-peering folder, should I also add it for other networking architecture options in fast?
Should I also add alerting policies when your utilization is above 80% for any of these quotas?
> Peering dashboard

- blueprints/data-solutions/data-platform-minimal/outputs.tf
Currently `composer.dag_bucket` returns full URL to DAGs location.  With this change, it will return only bucket name, so it is inline with `gcs_buckets` and variable name.
> Return only bucket name of composer, not full url to dags folder

- modules/ncc-spoke-ra/README.md
- modules/ncc-spoke-ra/main.tf
- modules/ncc-spoke-ra/variables.tf
Modified module input variable to deal with ncc hub creation (passing the name of the hub to create) as well as referencing existing hub via id (instead of the name). Only specifying the name of the hub (even if in the same project) led to strange terraform behaviour (name of the hub being interpreted as the project id somehow), at least in the latest version of the provider.
> Update ncc-spoke-ra module to explicity request ncc hub id when referencing existing hubs

- tools/check_documentation.py
- tools/tfdoc.py
- rename methods so it's clear which ones work on the tf reference tables and which ones work on the toc
- add a `--toc-only` option
- fail if `--toc-only` is false and no tfref mark is found
> Minimal tfdoc refactoring for legibility

- modules/dataplex-autodq/README.md
- modules/dataplex-autodq/main.tf
- modules/dataplex-autodq/variables.tf
@thinhha this is how I'd handle the cameCase/snake_case fields in the spec files. Basically first try cameCase and if it fails then you try snake_case. What do you think?
@ludoo wdyt?
> autodq parsing proposal

- modules/net-vpc/README.md
- modules/net-vpc/routes.tf
- modules/net-vpc/variables.tf
- tests/modules/net_vpc/examples/routes.yaml
> Allow custom route descriptions in net-vpc module

- modules/net-vpc/README.md
- modules/net-vpc/main.tf
- modules/net-vpc/outputs.tf
- modules/net-vpc/subnets.tf
- modules/net-vpc/variables.tf
- tests/modules/net_vpc/examples/ipv6.yaml
> Add support for ipv6 to net-vpc module

- fast/stages/0-bootstrap/README.md
- fast/stages/0-bootstrap/outputs.tf
When using Cloud Source repos with FAST, there is no workflow identity federation configuration, so `local.cicd_providers[v["identity_provider"]]` is null. When the bootstrap stage's output module tries to populate the `audience` local, this causes a null object exception.
There may be other ways to address this, but wrapping the call in a try block seemed the most painless to me.
> fix null object exception in bootstrap output when using cloudsource

- modules/net-firewall-policy/factory.tf
Currently the net-firewall-policy module factory implementation doesn't enable customisation of the rule action, nor does it `plan` correctly due to a missing name attribute.
Customisable action - the action for egress and ingress rules generated using the factory is hardcoded to "deny" and "allow" respectively. The previous `net-vpc-firewall-policy` module allowed customisation but set deny egress and allow ingress by default, which has been replicated in this PR rather than requiring an explicit action which the HFW set up in the `folder` module required.
Missing attribute - while the rules passed via `.tfvars` have a name/direction appended in `main.tf` the factory rules do not. As the direction for factory rules is assigned in `factory.tf`, this PR adds the name there too.
```
│ …
```
> Fix net-firewall-policy factory name and action

- modules/ncc-spoke-ra/main.tf
Currently CR peers may be created before the NCC-RA spoke is created (so before the VM is attached to an NCC spoke).
This errors out because we can't reference a VM as a peer before it gets added to an NCC spoke.
Adding an explicit dependency between the CR peer and the NCC RA spoke.
[tried to add an IMPLICIT dependency but makes the code much more complex and unreadable]
> [Fix] Add explicit dependency between CR peers and NCC RA spoke creation

- fast/stages/2-networking-a-peering/landing.tf
- fast/stages/2-networking-a-peering/spoke-dev.tf
- fast/stages/2-networking-a-peering/spoke-prod.tf
- fast/stages/2-networking-b-vpn/landing.tf
- fast/stages/2-networking-b-vpn/spoke-dev.tf
- fast/stages/2-networking-b-vpn/spoke-prod.tf
- fast/stages/2-networking-c-nva/landing.tf
- fast/stages/2-networking-d-separate-envs/spoke-dev.tf
- fast/stages/2-networking-d-separate-envs/spoke-prod.tf
- fast/stages/2-networking-e-nva-bgp/landing.tf
**Step 2 of "using correctly ASN in FAST"**
After talking with @juliocc it seems long AS numbers may not be ingested properly if applied from a 32 bit system, so it would be better to avoid them.
On the other hand, a default ASN number is not really needed for Cloud NAT.
As a result
* with a [previous patch](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/1633) we moved to optional the cloud nat module ASN (not required by APIs)
* with THIS patch, we revert (again!) the FAST ASN patch --> meaning, we will no longer specify ASNs in FAST
> [revert(revert(patch))] Remove unused ASN numbers for CloudNAT in FAST

- .github/workflows/linting.yml
- CONTRIBUTING.md
- tools/check_documentation.py
- tools/check_links.py
- tools/check_names.py
- tools/validate_metadata.py
- Only print liniting failures in GH workflows
- Provide a user-friend script (tools/lint.sh) to run all checks in one go
---
**Checklist**
> Simplify linting output in workflow

- modules/gke-cluster-autopilot/README.md
- modules/gke-cluster-autopilot/main.tf
- modules/gke-cluster-autopilot/variables.tf
- tests/modules/gke_cluster_autopilot/examples/monitoring-config-control-plane.yaml
Although one cannot disable Cloud Monitoring integration in GKE Autopilot clusters, one has some flexibility over which control plane components' metrics should be ingested: [manage GKE metrics](https://cloud.google.com/stackdriver/docs/solutions/gke/managing-metrics).
This PR adds a new input variable `monitoring_config` and a block to the cluster resource to facilitate that. The variable is optional with a sensible default value.
The interface is similar in style to #1625. Since there was no monitoring configuration in place for this module previously, it is not likely for this PR to break any existing code 🙏 
I've added an example to the README as well.
Feedback is welcome 🙃
**Checklist**
If applicable, I acknowledge that I have:
> gke-cluster-autopilot: add monitoring configuration

- fast/stages/1-resman/outputs.tf
It sometimes happens that when the FAST stage 1 TF destroy process breaks half way through, we get some errors on outputs:
```
Error: Unsupported attribute
│
│   on outputs.tf line 226, in locals:
│  226:     tag_keys         = { for k, v in module.organization.tag_keys : k => v.id }
│     │ module.organization is object with 8 attributes
│
│ This object does not have an attribute named "tag_keys".
╵
╷
│ Error: Unsupported attribute
│
│   on outputs.tf line 228, in locals:
│  228:     tag_values       = { for k, v in module.organization.tag_values : k => v.id }
│     │ module.organization is object with 8 attributes
│
│ This object does not have an attribute named "tag_values".
```
While the real cause is still unknown, this patch tries to …
> [#1661] Make FAST stage 1 resman tf destroy more reliable

- blueprints/factories/project-factory/main.tf
- tests/blueprints/factories/project_factory/examples/example.yaml
The `labels` key in `data_merges` in the **project-factory** blueprint was the only one not being merged.
---
**Checklist**
> merge labels from data_merges in project factory

- modules/compute-mig/autoscaler.tf
The `compute-mig` module at `//modules/compute-mig` takes in the `mode` property via the variable `autoscaler_config` but does not propagate it to the `google_compute_autoscaler` and `google_compute_region_autoscaler` resources in `autoscaler.tf`.
---
**Checklist**
> fix(compute-mig): add mode property to compute_region_autoscaler

- modules/net-vpc/subnets.tf
Fixed the nit from PR 1666 as per recommendation 
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/1666#issuecomment-1717067026
---
**Checklist**
> fixed up nit from PR 1666

- CONTRIBUTING.md
* Fix two broken links to section headers.
* Fix and expand the examples in the **Running tests for specific examples** section.
I recalled that I initially had some difficulties running the commands from that section. Now that I got the gist of it, I would like to propose a few changes. I fixed the examples that despite their description returned ambiguous results and added a few more examples of targeting specific tests.
Happy to provide more details, if need be 🙂 
**Checklist**
I acknowledge that I have:
> CONTRIBUTING guide: fix broken links and update "running tests for specific examples" section

- fast/stage-links.sh
- fast/stages-multitenant/0-bootstrap-tenant/README.md
- fast/stages-multitenant/0-bootstrap-tenant/outputs.tf
- fast/stages/0-bootstrap/cicd.tf
- fast/stages/0-bootstrap/outputs-files.tf
- fast/stages/0-bootstrap/outputs-gcs.tf
- fast/stages/1-resman/README.md
- fast/stages/1-resman/main.tf
- fast/stages/2-networking-a-peering/README.md
- fast/stages/2-networking-b-vpn/README.md
- fast/stages/2-networking-c-nva/README.md
- fast/stages/2-networking-d-separate-envs/README.md
- fast/stages/2-networking-e-nva-bgp/README.md
- fast/stages/2-security/README.md
- fast/stages/3-data-platform/dev/README.md
- fast/stages/3-gke-multitenant/dev/README.md
- fast/stages/3-project-factory/dev/README.md
- fast/stages/COMPANION.md
> Rename FAST globals output file

- modules/cloud-function-v1/README.md
- modules/cloud-function-v2/README.md
- tests/fixtures.py
- tests/modules/cloud_function_v1/examples/secrets.yaml
- tests/modules/cloud_function_v2/examples/secrets.yaml
Additional tests for #1703 to catch such errors in the future.
In this case, for Cloud Functions v2 test, if I only want to test `secret_environment_variables` and `secret_volumes`, I still need to specify all non-important attributes in inventory, e.g.:
```yaml
values:
module.cf-http.google_cloudfunctions2_function.function:
name: test-cf-http
service_config:
- all_traffic_on_latest_revision: true
available_cpu: '0.166'
available_memory: 256M
environment_variables: null
ingress_settings: ALLOW_ALL
max_instance_count: 1
min_instance_count: 0
secret_environment_variables:
- key: VARIABLE_SECRET
project_id: '1234567890'
secret: var_secret
version: latest
secret_volumes:
- mount_path: /app/secret
project_id: '1234567890'
secret: path_secret
versions:
- path: first
version: '1'
- path: second …
```
> Cf secret tests

- fast/stages/0-bootstrap/README.md
- fast/stages/0-bootstrap/organization.tf
- fast/stages/CLEANUP.md
This is a potential fix for an issue we're seeing with org policies in stage 0, when applied with user credentials. In draft until we verify the fix actually addresses the issue.
> Only apply org policies when bootstrap user is not set

- modules/cloud-function-v1/README.md
- modules/cloud-function-v1/main.tf
- modules/cloud-function-v1/variables.tf
- modules/cloud-function-v2/README.md
- modules/cloud-function-v2/main.tf
- modules/cloud-function-v2/variables.tf
- tests/modules/cloud_function_v1/examples/bucket-creation.yaml
- tests/modules/cloud_function_v2/examples/bucket-creation.yaml
As you suggested, I made the change only to the local variable.
With this change, "bucket" variable will have the value of "var.bucket_name" only if the bucket has to be created.
Otherwise, it will have the name of the created bucket.
---
**Checklist**
> Add bug fix in bucket local variable

- fast/stages/0-bootstrap/README.md
- fast/stages/0-bootstrap/organization.tf
This PR adds an example that shows how to conditionally set the oslogin org policy via a custom tag value. It's needed by the data platform, and also demonstrates how to define custom tag values and rules.
@lcaggio use this in your DP setup
> FAST: add example of custom org policy condition to bootstrap README

- blueprints/cloud-operations/dns-fine-grained-iam/README.md
- blueprints/cloud-operations/dns-shared-vpc/README.md
- blueprints/networking/decentralized-firewall/README.md
- blueprints/networking/filtering-proxy-psc/README.md
- blueprints/networking/filtering-proxy/README.md
- blueprints/networking/hub-and-spoke-vpn/README.md
- blueprints/networking/private-cloud-function-from-onprem/README.md
- blueprints/networking/shared-vpc-gke/README.md
- blueprints/serverless/cloud-run-corporate/README.md
- modules/dns/README.md
- modules/dns/main.tf
- modules/dns/outputs.tf
- modules/service-directory/README.md
- tests/fast/stages/s2_networking_a_peering/stage.yaml
- tests/fast/stages/s2_networking_b_vpn/stage.yaml
- tests/fast/stages/s2_networking_c_nva/stage.yaml
- tests/fast/stages/s2_networking_d_separate_envs/stage.yaml
- tests/fast/stages/s2_networking_e_nva_bgp/stage.yaml
- tests/modules/dns/examples/peering-zone.yaml
- tests/modules/dns/examples/public-zone.yaml
- tests/modules/dns/examples/reverse-zone.yaml
Fix dns module with provider version >= 5
hashicorp/terraform-provider-google#16096
---
**Checklist**
> Fix dnssec keys lookup

- fast/stages-multitenant/0-bootstrap-tenant/identity-providers.tf
- fast/stages/0-bootstrap/identity-providers.tf
- tools/lint.sh
Change to tools/lint.sh to invoke python3 for blueprint metadata 
Wording update to:
fast/stages-multitenant/0-bootstrap-tenant/identity-providers.tf
fast/stages/0-bootstrap/identity-providers.tf
---
**Checklist**
> Update to lint.sh and wording to some tf

- modules/gke-nodepool/main.tf
> Fix typo in GKE nodepool taints

- blueprints/data-solutions/sqlserver-alwayson/README.md
- blueprints/data-solutions/sqlserver-alwayson/outputs.tf
- blueprints/data-solutions/sqlserver-alwayson/vpc.tf
- blueprints/networking/filtering-proxy-psc/main.tf
- blueprints/networking/filtering-proxy/main.tf
- blueprints/networking/glb-hybrid-neg-internal/glb.tf
- blueprints/networking/glb-hybrid-neg-internal/main.tf
- blueprints/networking/ilb-next-hop/gateways.tf
- blueprints/networking/ilb-next-hop/outputs.tf
- blueprints/networking/ilb-next-hop/vpc-left.tf
- blueprints/networking/ilb-next-hop/vpc-right.tf
- fast/stages/2-networking-c-nva/nva.tf
- fast/stages/2-networking-c-nva/spoke-dev.tf
- fast/stages/2-networking-c-nva/spoke-prod.tf
- modules/net-lb-int/README.md
- modules/net-lb-int/groups.tf
- modules/net-lb-int/health-check.tf
- modules/net-lb-int/main.tf
- modules/net-lb-int/outputs.tf
- modules/net-lb-int/variables.tf
- tests/modules/net_lb_int/defaults.yaml
- tests/modules/net_lb_int/forwarding-rule.tfvars
- tests/modules/net_lb_int/forwarding-rule.yaml
The PR adds support for:
* dual stack: being able to configure both IPv4 and IPv6 addresses on the same ILB
* use of multiple forwarding rules (indeed, both IPv4 and IPv6), thus being able to expose multiple frontend IPs
---
**Checklist**
> [#1764] net-lb-int: add support for dual stack and multiple forwarding rules

- fast/stages/3-project-factory/dev/README.md
- fast/stages/3-project-factory/dev/outputs.tf
Don't dump all project module outputs in the FAST project factory stage outputs.
> Less verbose project factory stage outputs

- modules/net-lb-app-int/README.md
Serverless NEG backends don't support RATE balancing:
Error: Error creating RegionBackendService: googleapi: Error 400: Invalid value for field 'resource.backends[0].balancingMode': 'RATE'. Balancing mode is not supported for Serverless network endpoint groups., invalid
---
**Checklist**
> Fix Internal App LB serverless NEG backend example

- modules/compute-vm/README.md
Remove old todo from compute-vm module readme.
---
**Checklist**
> compute-vm: remove old todo

- fast/stages/2-security/README.md
FAST security stage references a `kms_defaults`which has since been removed.
Updating README.md accordingly.
---
**Checklist**
> FAST: removed references to kms_defaults

- fast/stages/2-networking-a-peering/data/hierarchical-ingress-rules.yaml
- fast/stages/2-networking-b-vpn/data/hierarchical-ingress-rules.yaml
- fast/stages/2-networking-c-nva/data/hierarchical-ingress-rules.yaml
- fast/stages/2-networking-d-separate-envs/data/hierarchical-ingress-rules.yaml
- fast/stages/2-networking-e-nva-bgp/data/hierarchical-ingress-rules.yaml
- Adds VPC serverless connector NAT ranges to hierarchical fw
- Comments out an almighty allow all from hierarchical fw
---
**Checklist**
> FAST: Add VPC serverless connector NAT ranges to hierarchical fw

- blueprints/apigee/hybrid-gke/glb.tf
- blueprints/gke/autopilot/glbs.tf
- blueprints/third-party-solutions/phpipam/glb.tf
- modules/net-address/README.md
- modules/net-address/main.tf
- modules/net-address/variables.tf
- modules/net-lb-app-ext/README.md
- tests/modules/net_address/examples/ipv6.yaml
Allows users to reserve IPv6 addresses.
FYI I submitted the initial PR without modifying the BP tests (yet), so we can first make sure that the modification to global addresses is done the way we want. Please, let me know if looks of to you.
---
**Checklist**
> [net-address] enable ipv6

- fast/stages/0-bootstrap/README.md
- modules/gcve-private-cloud/README.md
Updating wording
---
**Checklist**
> Updating wording

- modules/net-vpc-peering/README.md
- modules/net-vpc-peering/main.tf
- modules/net-vpc-peering/variables.tf
Added the stack_type field for the "google_compute_network_peering" terraform resource. Link to documentation: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_peering#stack_type
> Net VPC Peering: added stack_type field

- modules/gke-nodepool/main.tf
- modules/gke-nodepool/variables.tf
Fix validation and dynamic block for optional gpu_driver as it errors out on null when the block is not provided.
---
**Checklist**
> Fix validation and dynamic block for optional gpu_driver

- modules/net-lb-app-int/README.md
- modules/net-lb-app-int/backend-service.tf
- modules/net-lb-app-int/variables-backend-service.tf
Removed options that are not applicable to this load balancer. See here:
https://cloud.google.com/load-balancing/docs/backend-service#balancing-mode
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_backend_service#connection_tracking_policy
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_backend_service#failover_ratio
---
**Checklist**
> Removed options that are not applicable to this load balancer

- modules/organization/README.md
- modules/organization/iam.tf
- tests/examples/conftest.py
- tests/examples_e2e/setup_module/e2e_tests.tfvars.tftpl
- tests/modules/organization/examples/basic.yaml
- tests/modules/organization/examples/logging.yaml
- tests/modules/organization/examples/network-tags.yaml
- tests/modules/organization/examples/roles.yaml
- tests/modules/organization/examples/tags.yaml
- tests/pytest.ini
* added tag `serial` to mark tests to be run serially
* always run tests using `loadgroup` distribution to make use of `serial` tag
* added end-to-end tests for organization, not adding to custom constraints as the name has to be unique
* fixed granting custom roles created in the same module call
[E2E tests run](https://github.com/GoogleCloudPlatform/fast-e2e/actions/runs/6865343619)
---
**Checklist**
> Organization module end-to-end tests

- modules/cloudsql-instance/README.md
- modules/cloudsql-instance/main.tf
- modules/cloudsql-instance/variables.tf
Added the following parameters: edition, collation, disk_autoresize_limit, connector_enforcement
---
**Checklist**
> added missing sql parameters

- modules/cloud-config-container/cos-generic-metadata/cloud-config.yaml
Fix permission assignments to cloud init configuration.
Otherwise you obtain error during the initialization:
```
$ sudo cloud-init schema --system
Invalid cloud-config /var/lib/cloud/instances/XXX/cloud-config.txt Error: Cloud config schema errors: write_files.0.permissions: 420 is not of type 'string', write_files.1.permissions: 420 is not of type 'string'
```
> Fix permissions assignments

- blueprints/third-party-solutions/f5-bigip/f5-bigip-ha-active/README.md
- blueprints/third-party-solutions/f5-bigip/f5-bigip-ha-active/variables.tf
Some improvements and copyright additions to F5 blueprints
---
**Checklist**
> Fixes/improvements to F5 HA blueprint

- modules/artifact-registry/README.md
- modules/artifact-registry/main.tf
- modules/artifact-registry/variables.tf
- tests/modules/artifact_registry/examples/cleanup-policies.yaml
This PR aim to add support of cleanup policies for artifact registry module.
ie : https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository#example-usage---artifact-registry-repository-cleanup
---
**Checklist**
> artifact-registry: Support cleanup policies

- modules/folder/README.md
- modules/organization/README.md
- modules/project/README.md
- tests/modules/project/examples/data.yaml
Logging bucket name can be reused only after 7 days (when it is actually deleted). When different tests reuse the same name, the ones that are executed as 2nd and later will fail with message:
```
Error updating Logging Bucket Config [...]: googleapi: Error 400: Buckets 
must be in an ACTIVE state to be modified
```
As their actual state is:
```
lifecycleState: DELETE_REQUESTED
```
---
**Checklist**
> Use unique names for logging buckets in examples

- modules/project/README.md
> README fixes for #1907

- modules/cloud-config-container/simple-nva/README.md
Tiny README update: `can_ip_forward = true` in `simple-nva` examples
> can_ip_forward in simple-nva examples

- modules/bigtable-instance/README.md
- modules/bigtable-instance/main.tf
- modules/bigtable-instance/outputs.tf
- modules/bigtable-instance/variables.tf
_instance_type_ variable was removed because is deprecated. _labels_ variable was added.
_display_name_ was fixed.
---
**Checklist**
> Removed deprecated variable and added labels

- fast/stages/2-networking-a-peering/data/dns-policy-rules.yaml
- fast/stages/2-networking-b-vpn/data/dns-policy-rules.yaml
- fast/stages/2-networking-c-nva/data/dns-policy-rules.yaml
- fast/stages/2-networking-d-separate-envs/data/dns-policy-rules.yaml
- fast/stages/2-networking-e-nva-bgp/data/dns-policy-rules.yaml
- tests/fast/stages/s2_networking_a_peering/stage.yaml
- tests/fast/stages/s2_networking_b_vpn/stage.yaml
- tests/fast/stages/s2_networking_c_nva/stage.yaml
- tests/fast/stages/s2_networking_d_separate_envs/stage.yaml
- tests/fast/stages/s2_networking_e_nva_bgp/stage.yaml
This PR adds kernels.googleusercontent.com zone in DNS response policy for supporting Vertex AI Managed Notebook as per the [following](https://cloud.google.com/vertex-ai/docs/workbench/managed/service-perimeter) documentation.
> Add kernels.googleusercontent.com zone in dns response policy

- fast/stages/0-bootstrap/templates/workflow-github.yaml
Reverts GoogleCloudPlatform/cloud-foundation-fabric#1938 as it breaks stage 0.
> Revert "Add debug step for JWT tokens"

- tests/examples/variables.tf
- tests/modules/cloud_run/examples/secrets.yaml
- tests/modules/net_address/examples/internal.yaml
- tests/modules/net_address/examples/ipsec-interconnect.yaml
- tests/modules/net_address/examples/ipv6.yaml
- tests/modules/net_lb_ext/examples/dual_stack.yaml
- tests/modules/net_lb_ext/examples/e2e.yaml
- tests/modules/net_lb_ext/examples/ext_migs.yaml
- tests/modules/net_lb_ext/examples/fwd_rules.yaml
- tests/modules/net_lb_ext/examples/migs.yaml
- tests/modules/net_vpn_ha/examples/gcp-to-onprem.yaml
- tests/modules/workstation_cluster/examples/custom-image.yaml
- tests/modules/workstation_cluster/examples/iam.yaml
- tests/modules/workstation_cluster/examples/private-cluster.yaml
- tests/modules/workstation_cluster/examples/simple.yaml
This PR changes variable region's default value in example tests to real region value.
Some of the modules parse the region name to decide whether to create regional or zonal resources.
> Fix variable region

- modules/net-lb-app-ext/README.md
> net-lb-app-ext example fixes

- modules/net-lb-app-ext/README.md
- tests/fixtures/compute-mig-bc.tf
- tests/modules/net_lb_app_ext/examples/complex-example.yaml
zone a doesn't exist in every region. Use zones b,c for MIG fixture.
> Use zones b and c for MIG fixture

- modules/service-directory/README.md
- modules/service-directory/main.tf
- modules/service-directory/variables.tf
- tests/modules/service_directory/examples/pna.yaml
Endpoints in Service Directory can be *associated* with a VPC. In this case, they can be used by supported Google Cloud products to send requests directly to resources inside a VPC. This feature is called [Private Network Access](https://cloud.google.com/service-directory/docs/private-network-access-overview).
The `google_service_directory_endpoint` resource supports this configuration with a new argument `network`.
Unfortunately, this argument has an unusual format: it is similar to a standard VPC ID, but instead of the project ID, it expects the project number.
---
**Checklist**
If applicable, I acknowledge that I have:
> Add PNA support to Service Directory module

- modules/net-lb-ext/README.md
- tests/fixtures/compute-mig.tf
- tests/modules/net_lb_ext/examples/dual_stack.yaml
- tests/modules/net_lb_ext/examples/ext_migs.yaml
- tests/modules/net_lb_ext/examples/fwd_rules.yaml
- tests/modules/net_lb_ext/examples/migs.yaml
> Use fixtures in net-lb-ext

- modules/vpc-sc/variables.tf
This PR enables to support keyword ANY_USER_ACCOUNT when crafting VPC SC egress rule.
This keyword (identity_type) is currently not enabled by validation block in [modules/vpc-sc/variable.tf](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/vpc-sc/variables.tf#L95).
Despite the fact that this option is specifically not enabled by fast vpc-sc module, it is indeed fully supported by underlying terraform resource [google_access_context_manager_service_perimeters](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeters#identity_type).
Desired state:
[ x] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/maste …
> Support for ANY_USER_ACCOUNT in module vpc-sc egress rule.

- fast/stages/0-bootstrap/terraform.tfvars.sample
add locations on terraform.tfvars.sample for bootstrap stage
> Add locations on terraform.tfvars.sample for bootstrap stage

- modules/vpc-sc/variables.tf
Google provider supports empty string for `identity_type`. Even if `IDENTITY_TYPE_UNSPECIFIED` is used as the value, Terraform state stores empty string as the value instead. Hence it make sense to support empty string as a value in the module.
Also `ANY_USER_ACCOUNT` is the correct value for ingress `identity_type`.
---
**Checklist**
> Fix identity_type

- modules/vpc-sc/variables.tf
This is continuation of https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/1978.
Because the logical operators (`||`, `&&`) in Terraform [do not short-circuit](https://developer.hashicorp.com/terraform/language/expressions/operators#logical-operators), and [coalesce()](https://developer.hashicorp.com/terraform/language/functions/coalesce) never returns non-empty string, empty string validation needs to be done differently.
The provided code change properly validates if `identity_type` is null or empty string or any of the allowed keywords.
---
**Checklist**
> Proper validation of empty string value in identity_type

- modules/dns/README.md
- modules/dns/main.tf
- modules/dns/variables.tf
- tests/modules/dns/examples/routing-policies.yaml
Added health checked targets for geo routing policy in dns module
---
**Checklist**
> Added health checked targets for geo routing policy in dns module

- modules/dns/README.md
- tests/modules/dns/examples/routing-policies.yaml
> Fixed README and test for dns module

- modules/net-firewall-policy/README.md
- modules/net-firewall-policy/factory.tf
- modules/net-firewall-policy/hierarchical.tf
- tests/modules/net_firewall_policy/examples/factory.yaml
> Fix factory default value for rule ports in firewall policy module

- blueprints/data-solutions/data-platform-foundations/README.md
This PR fixes #1314 by setting the prefix used in the data platform's example to 12 characters, which is the longest allowed in FAST multitenant stages.
Service account names which are too long will fail provider validation in the plan with an error similar to this one:
```
Error: "account_id" ("test-0123456789-orc-sa-df-build") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
```
> Ensure data platform service accounts meet FAST requirements

- fast/stages/2-networking-a-peering/data/hierarchical-ingress-rules.yaml
- fast/stages/2-networking-b-vpn/data/hierarchical-ingress-rules.yaml
- fast/stages/2-networking-c-nva/data/hierarchical-ingress-rules.yaml
- fast/stages/2-networking-d-separate-envs/data/hierarchical-ingress-rules.yaml
- fast/stages/2-networking-e-nva-bgp/data/hierarchical-ingress-rules.yaml
- modules/net-firewall-policy/README.md
- tests/modules/net_firewall_policy/examples/global-net.yaml
- tests/modules/net_firewall_policy/examples/hierarchical.yaml
Fixes #2023, the rationale for this PR is in that issue.
> Selectively enable logging in FAST and firewall policy module rules

- modules/dns/main.tf
If a Cloud DNS managed zone has been created through this module without `dnssec_config` and the DNS Zone is manually modified in the UI, for example to enable logging, even if you do not touch the DNSSEC configuration, a `dnssec_config` will be added to the terraform state, with the variable `state` set to `off`:
```
+ dnssec_config {
+ kind          = "dns#managedZoneDnsSecConfig"
+ non_existence = "nsec3"
+ state         = "off"
+ default_key_specs {
+ algorithm  = "rsasha256"
+ key_length = 2048
+ key_type   = "keySigning"
+ kind       = "dns#dnsKeySpec"
}
+ default_key_specs {
+ algorithm  = "rsasha256"
+ key_length = 1024
+ key_type   = "zoneSigning"
+ kind       = "dns#dnsKeySpec"
}
}
```
From this point on, you can no longer run terraform without running into an error of the API …
> Fix dnssec_config issue on state off

- modules/project/README.md
- modules/project/outputs.tf
Add Tags in project output.
---
**Checklist**
> Add Tags in project output.

- fast/stages/0-bootstrap/README.md
- fast/stages/0-bootstrap/organization.tf
- fast/stages/0-bootstrap/variables.tf
Fix for #2056, import org policies only when requested, and only when org policies are applied (`bootstrap_user` is not set).
---
**Checklist**
> Fix imports of org policies

- blueprints/data-solutions/vertex-mlops/vertex.tf
- modules/net-address/README.md
- tests/modules/net_address/examples/internal.yaml
* Fix non empty plan after apply for `google_notebooks_instance` 
* Use different address in tests for `net-address` to avoid conflicts
---
**Checklist**
> Fix e2e tests - vertex mlops and net-address

- blueprints/networking/psc-glb-and-armor/README.md
- blueprints/networking/psc-glb-and-armor/consumer.tf
- blueprints/networking/psc-glb-and-armor/modules/producer/main.tf
- blueprints/networking/psc-glb-and-armor/modules/producer/outputs.tf
- blueprints/networking/psc-glb-and-armor/modules/producer/variables.tf
- blueprints/networking/psc-glb-and-armor/outputs.tf
- blueprints/networking/psc-glb-and-armor/variables.tf
Use Fabric modules in blueprints/networking/psc-glb-and-armor
Few minor improvements along the way:
* remove unnecessary subnets (additional NAT for PSC, VMS)
* remove NOOP compute engine instance
* added url_rewrite for service b, so the service actually works as expected
* added allow-list for consumer projects that can connect to the producers PSC service
* improved `curl` to it uses `terraform output` for find the IP address
* added possibility to meaningfully create projects (using prefixes, parent etc.)
This that are different , though not sure if that's OK:
* added network in consumer project, so PSC attachment doesn't complain on missing `default` network, not sure if that was expected
---
**Checklist**
> Use Fabric modules in blueprints/networking/psc-glb-and-armor

- modules/iam-service-account/main.tf
This fixes a corner case where an email is passed it to the service account module, e.g. when consuming an existing service account with no creation, and the full email is then used as the name.
> Accept email in service account module name

- modules/folder/README.md
- modules/organization/README.md
- modules/project/README.md
- tests/modules/folder/examples/logging.yaml
- tests/modules/organization/examples/logging.yaml
- tests/modules/project/examples/logging.yaml
This fixes recent E2E failures:
```
Error: "***-1708673310w5-destination-project" name must be 4 to 30 characters with lowercase and uppercase letters, numbers, hyphen, single-quote, double-quote, space, and exclamation point
```
---
**Checklist**
> Fix too long project names in e2e tests

- blueprints/third-party-solutions/phpipam/README.md
- blueprints/third-party-solutions/phpipam/cloudsql.tf
- blueprints/third-party-solutions/phpipam/glb.tf
- blueprints/third-party-solutions/phpipam/main.tf
- blueprints/third-party-solutions/phpipam/outputs.tf
Fix #2114 
For the jquery / mixed content issues on PHPIPAM the proposed fix is based on the solution proposed on the [official repo](https://github.com/phpipam/phpipam/issues/802#issuecomment-1864710950). 
I also notice the error on the cloud sql password in output not available, the issue was related to the missing user type in cloud sql module preventing the password from being populated in the module's output. This was causing the blueprint output not being shown due to null value.
I had the chance to also update the following:
- add http to https redirect in GLB
- use local value for cloudsql_password output 
> Fix phpipam blueprint

- modules/project/service-agents.yaml
This is to activate the Dataform service agent when the API is activated. jit set to true in the project module
---
**Checklist**
> enabling dataform service agent upon activating the API

- modules/compute-vm/README.md
- modules/compute-vm/main.tf
- modules/compute-vm/variables.tf
- modules/net-address/README.md
- modules/net-address/main.tf
- modules/net-address/outputs.tf
- modules/net-address/variables.tf
- modules/net-vpc/README.md
- modules/net-vpc/outputs.tf
- modules/net-vpc/subnets.tf
- modules/net-vpc/variables.tf
- tests/modules/net_address/examples/network-attachments.yaml
- tests/modules/net_vpc/examples/network-attachments.yaml
This PR implements support for PSC network attachments and interfaces. The design moves from Fabric principles, and
- implements support for network attachments in the `net-vpc` module, to allow network owners to directly define them
- implements support for network attachments in the `net-address` module, to allow the use case of creating attachments from Shared VPC service projects
- implements support for network attached interfaces in the `compute-vm` module
At a lower level, the design choice on where and how to implement support (apart from the obvious choice of the vm module), moves from a few simple considerations.
The `net-vpc` variable design uses a separate variable, as network attachments have a 1:1 relationship with subnets (single subnet per attachment), and subnets have a …
> Add support for PSC network attachments and interfaces in modules

- blueprints/factories/README.md
- modules/organization/README.md
- modules/project/README.md
- modules/project/outputs.tf
This PR adds deep links to the factories documentation page. It also adds a missing section to the project module README, and reconciles the name of the custom roles outputs with the the one used in the organization module.
> Add links to factories doc

- README.md
I have found some type in the README.md file. So updated those.
---
**Checklist**
> Updating README.md file for fixing some typo

- .github/actions/post-fabric-tests/action.yml
- .github/workflows/tests.yml
Add test results to jobs summary.
---
**Checklist**
> Add test reports to checks

- blueprints/data-solutions/data-platform-minimal/02-dataproc.tf
- modules/dataproc/README.md
- modules/dataproc/main.tf
- modules/dataproc/outputs.tf
- modules/dataproc/variables.tf
- tests/examples_e2e/setup_module/main.tf
- tests/fixtures/gke-cluster-standard.tf
* added end-to-end tests for dataproc module, regrettably - ~~GCE example proved to be flaky in tests - so it is disabled (the depends_on is not always enough for the cluster creation to complete successfully, sometimes manual retry is required)~~
* included in the examples necessary components (firewall rules, permissions)
* added fixture for GKE cluster
* removed unused variable `service_account` - properly managing service account within module is left as excessive for future reader / self
* removed variable `prefix` as it doesn't make much sense in this context
* removed output variables as due to bugs in the terraform provider they are not returned and result in `terraform plan` errors after apply
Error on GCE dataproc cluster apply:
```
│ Error: Error waiting for creating Dataproc …
```
> Dataproc module cleanup & fixes

- modules/kms/README.md
- tests/examples/variables.tf
- tests/examples_e2e/setup_module/e2e_tests.tfvars.tftpl
- tests/examples_e2e/setup_module/main.tf
- tests/modules/kms/examples/basic.yaml
- tests/modules/kms/examples/import-job.yaml
- tests/modules/kms/examples/purpose.yaml
---
**Checklist**
- [ X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [ X] Ran `terraform fmt` on all modified files
- [ X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [ X] Made sure all relevant tests pass
> Kms e2e tests

- modules/projects-data-source/README.md
---
**Checklist**
- [X ] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X ] Ran `terraform fmt` on all modified files
- [ X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [ X] Made sure all relevant tests pass
> Projects data source e2e tests

- modules/project-factory/README.md
- modules/project-factory/automation.tf
- modules/project-factory/factory-budgets.tf
- modules/project-factory/factory-folders.tf
- modules/project-factory/factory-projects.tf
- modules/project-factory/folders.tf
- modules/project-factory/main.tf
- tests/modules/project_factory/examples/example.yaml
This PR adds support for defining controlling (IaC) projects and resources in the project factory. This is an example from the README:
```yaml
billing_account: 012345-67890A-BCDEF0
parent: folders/12345678
services:
- compute.googleapis.com
- stackdriver.googleapis.com
iam:
roles/owner:
- rw
roles/viewer:
- ro
automation:
project: foo-prod-iac-core-0
service_accounts:
rw:
description: Read/write automation sa for app example 0.
ro:
description: Read-only automation sa for app example 0.
buckets:
state:
description: Terraform state bucket for app example 0.
iam:
roles/storage.objectCreator:
- rw
roles/storage.objectViewer:
- rw
- ro
- "group: devops@example.org"
```
> Support automation/controlling projects and resources in project factory

- modules/net-cloudnat/README.md
- modules/net-cloudnat/main.tf
- modules/net-cloudnat/variables.tf
Closes #2165
This PR adds an additional variable to configure the
`tcp_time_wait_timeout_sec` as exposed by the provider.
---
**Checklist**
> feat(net-cloudnat): add `tcp_time_wait` to `config_timeouts`

- blueprints/cloud-operations/packer-image-builder/main.tf
- modules/net-cloudnat/README.md
- modules/net-cloudnat/main.tf
- modules/net-cloudnat/variables.tf
- tests/modules/net_cloudnat/examples/subnets.yaml
This completes the fix of #2140 by properly implementing subnetwork configuration by mediating the provider implementation via a single variable that encapsulates both `source_subnetwork_ip_ranges_to_nat` and the `subnetworks` block.
> Fix subnet configuration in cloud nat module

- fast/stages/0-bootstrap/data/custom-roles/organization_admin_viewer.yaml
- fast/stages/0-bootstrap/templates/workflow-github.yaml
- fast/stages/0-bootstrap/templates/workflow-sourcerepo.yaml
- fast/stages/1-resman/templates/workflow-github.yaml
- fast/stages/1-resman/templates/workflow-sourcerepo.yaml
The missing permissions is a consequence of #2139.
This also bumps the Terraform version in our workflow files, to support recent language features. Fixes #2176
> Add missing permission to org viewer custom role in FAST stage 0

- modules/cloud-run-v2/README.md
- tests/fixtures/cloud-run-kms-iam-grant.tf
* create a fixture adding IAM grants to Cloud Run service agent
* add to README.md information about required grant
Decided to add ths as a fixture though it may not be reused so:
* grant is not polluting the example
* grant is fairly easy discoverable from README.md
* setup_module is not burdened with additional grant which is used only for this example
---
**Checklist**
> Fix failing e2e tests for Cloud Run CMEK

- modules/project/README.md
- modules/project/quotas.tf
- modules/project/variables.tf
- tests/modules/project/examples/outputs.yaml
- tests/modules/project/examples/quotas.yaml
Follow up on #2210 - add factory to manage quotas.
Use cases for this factory:
* application teams - to manage quotas within their projects (usually together with `project_create = false`), especially when using GPUs
* to be used in [modules/project-factory](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/project-factory) - to allow quota management during project creation
---
**Checklist**
> Add project quotas factory

- fast/stages/0-bootstrap/data/org-policies/iam.yaml
- fast/stages/0-bootstrap/data/org-policies/serverless.yaml
- fast/stages/0-bootstrap/data/org-policies/storage.yaml
- tests/fast/stages/s0_bootstrap/checklist.yaml
- tests/fast/stages/s0_bootstrap/simple.yaml
**Enabled by default:**
- iam.serviceAccountKeyExposureResponse: disable any SA keys that are detected as exposed
- storage.secureHttpTransport: disable HTTP access to storage resources
- 
**Commented out:**
- constraints/cloudfunctions.restrictAllowedGenerations: Cloud Function versions
> Add new org policies to FAST

- fast/stages/1-resman/branch-networking.tf
Fix permissions for FAST branch network dev for read service accounts.
---
**Checklist**
> [FAST] Fix permissions for branch network dev - read sa

- modules/project/service-agents.yaml
Enabling the `connectors.googleapis.com` service is insufficient to create the `service-<project_number>@gcp-sa-connectors.iam.gserviceaccount.com` service account.
In a Shared VPC architecture, we are unable to assign the role of dns.peer to this service account, as outlined in the [integration documentation](
https://cloud.google.com/integration-connectors/docs/create-endpoint-attachment#create-ep-hostname)
---
**Checklist**
> Added missing identity when connectors API is enabled

- modules/project-factory/outputs.tf
`local.folders` is [just a map of var-based keys to string manipulations on those keys](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/project-factory/factory-folders.tf#L32), while `local.hierarchy` is [the seemingly-intended map of var-based keys to generated IDs/numbers](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/project-factory/factory-folders.tf#L39). Access to the actual generated IDs/numbers is necessary for practical use of this module.
I tested this by modifying a clone, but I haven't actually run your tests.
Thank you for recently developing this convenient module!
---
I acknowledge that I have:
> Fix bug from output typo in new project-factory module

- fast/stages/0-bootstrap/organization.tf
- tests/collectors.py
- tests/fast/stages/s0_bootstrap/iam_by_principals.tfvars
- tests/fast/stages/s0_bootstrap/iam_by_principals.yaml
When I provide `iam_by_principals` to bootstrap stage, not all entries are taken into account, as only principals listed `local.iam_principals` were used. For example, if using this to grant permissions to non-FAST defined groups, this would not work.
---
**Checklist**
> Fix 0-bootstrap iam_by_principals not taking into account all principals

- .github/workflows/linting.yml
- .style.yapf
- tools/lint.sh
Move the yapf style definition out of command line call into dedicated file.
---
**Checklist**
> Explicit YAPF style

- modules/alloydb/README.md
- modules/alloydb/main.tf
- tests/examples_e2e/setup_module/main.tf
- tests/fixtures/alloydb-kms-iam-grant.tf
- tests/modules/alloydb/examples/cmek.yaml
- tests/modules/alloydb/examples/cross_region_replication.yaml
- tests/modules/alloydb/examples/simple.yaml
Fixed issue with AlloyDB e2e tests. I had to add ignore_changes due to a bug in the API (not yet managed in the provider) causing an attribute not being set and plan never aligned with infrastructure state. 
---
> Fixed e2e tests for alloydb module

- .pre-commit-config.yaml
- .yamllint
- blueprints/apigee/bigquery-analytics/send-requests.sh
- blueprints/cloud-operations/workload-identity-federation/setup.sh
- tests/modules/artifact_registry/examples/cleanup-policies.yaml
- tests/modules/gcs/examples/iam-authoritative.yaml
- tests/modules/gcs/examples/iam-bindings-additive.yaml
- tests/modules/gcs/examples/iam-bindings.yaml
- tests/modules/secret_manager/examples/secret-cmek.yaml
- tools/check_boilerplate.py
- tools/pre-commit-tfdoc.sh
- tools/tflint-fast.py
Adding this for those who are forgetful as me, to run `terraform fmt` or `tools/tfdoc.py` on changed files.
As of now configuration includes following linters.
* Terraform:
* terraform fmt
* terraform tflint
* Python specific:
* yapf
* Shell scripts
* shellcheck
* shfmt
* YAML files:
* yamllint (disabled as of now)
* check-yaml
* Other:
* end-of-file-fixer
* trailing-whitespace fixer
* Fabric specific
* tools/tfdoc.py
* tools/check_boilerplate.py
The checks that are raising most issues in our repo are:
- end-of-file-fixer
- trailing-whitespace fixer
- shellfmt
- shellcheck
Out of those, only shellcheck requires manual fixes, all other 3 above just apply the fix themselves. Shellcheck is controversial so we may want to disable it. 
If you want to check the changes the linters introduce run …
> Add pre-commit hook configuration

- fast/stages/2-security/README.md
- fast/stages/2-security/outputs.tf
- modules/project-factory/factory-projects.tf
Two small fixes that enable using VPC-SC via the project factory module and FAST stage.
> Add perimeter ids in vpc-sc module outputs, fix vpc-sc in project factory module

- modules/net-lb-app-ext-regional/README.md
- modules/net-lb-app-ext/README.md
- modules/net-lb-app-ext/main.tf
- modules/net-lb-app-int-cross-region/README.md
- modules/net-lb-app-int/README.md
- modules/net-lb-ext/README.md
- modules/net-lb-int/README.md
- modules/net-lb-proxy-int/README.md
lifecycle create_before_destroy on SSL certificates is not working, as with such strategy alreadyExists error is thrown when creating new certificate.
Closes #2093
---
**Checklist**
> Add documentation for load balancer changes

- tools/pre-commit-tfdoc.sh
Addresses # 2342
Changes: updates the shebang for the pre-commit hook, specifically `pre-commit-tfdocs.sh`, so that bash is taken from $PATH and not hardcoded. 
```bash
export PATH="/opt/homebrew/bin/bash:$PATH" # This makes our bash version to be selected by the shebang
git commit -m "My great commit!"  # This will trigger the pre-hook using the injected bash version into env
```
---
**Checklist**
> Change shebang on pre-commit checks

- tools/pre-commit-tfdoc.sh
Closes #2342
---
**Checklist**
> use /bin/sh for pre-commit script for portability

- blueprints/apigee/apigee-x-foundations/monitoring.tf
- blueprints/apigee/bigquery-analytics/main.tf
- blueprints/cloud-operations/asset-inventory-feed-remediation/main.tf
- blueprints/cloud-operations/compute-quota-monitoring/main.tf
- blueprints/cloud-operations/network-quota-monitoring/deploy-cloud-function/main.tf
- blueprints/cloud-operations/scheduled-asset-inventory-export-bq/main.tf
- blueprints/cloud-operations/unmanaged-instances-healthcheck/main.tf
- blueprints/networking/private-cloud-function-from-onprem/main.tf
- modules/cloud-function-v1/README.md
- modules/cloud-function-v1/bundle.tf
- modules/cloud-function-v1/main.tf
- modules/cloud-function-v1/variables.tf
- modules/cloud-function-v2/README.md
- modules/cloud-function-v2/bundle.tf
- modules/cloud-function-v2/main.tf
- modules/cloud-function-v2/variables.tf
This is especially useful when deploying source code provided as zip archives. Aside from the variable name change, this is transparent for the previous use case of dynamicallygenerating the bundle from a source folder.
> Support pre-made bundle archives in cloud function modules

- blueprints/apigee/apigee-x-foundations/monitoring.tf
- blueprints/apigee/bigquery-analytics/main.tf
- blueprints/cloud-operations/asset-inventory-feed-remediation/main.tf
- blueprints/cloud-operations/compute-quota-monitoring/main.tf
- blueprints/cloud-operations/network-quota-monitoring/deploy-cloud-function/main.tf
- blueprints/cloud-operations/scheduled-asset-inventory-export-bq/main.tf
- blueprints/cloud-operations/unmanaged-instances-healthcheck/main.tf
- blueprints/networking/private-cloud-function-from-onprem/main.tf
- modules/cloud-function-v1/README.md
- modules/cloud-function-v1/bundle.tf
- modules/cloud-function-v1/main.tf
- modules/cloud-function-v1/variables.tf
- modules/cloud-function-v2/README.md
- modules/cloud-function-v2/bundle.tf
- modules/cloud-function-v2/main.tf
- modules/cloud-function-v2/variables.tf
- tests/modules/cloud_function_v1/examples/multiple_functions.yaml
- tests/modules/cloud_function_v2/examples/iam.yaml
- tests/modules/cloud_function_v2/examples/multiple_functions.yaml
This addresses an issue when multiple cloud functions use the same bundle with different entrypoints, and our Cloud Function modules have to upload the same bundle for each individual function.
This PR makes GCS object URIs directly usable as bundles, and reinforces validation for the existing bundle types (local zip archive or folder).
> Support GCS objects in cloud function modules bundles

- modules/cloud-function-v1/main.tf
- modules/cloud-function-v2/main.tf
Fixes the changes introduced with #2361
> Strip bucket name from bundle URI in cloud function modules

- modules/project-factory/factory-budgets.tf
Fixes #2365 . 
Using project id for the projects in the filter is not correct and the [project number is expected](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget#projects). This fixes  that.
---
**Checklist**
> Fix for plan not in sync when creating billing budgets in project factory #2365

- modules/net-address/README.md
- modules/net-address/psc.tf
- tests/modules/net_address/examples/psc-service-attachment-all-apis.yaml
> Add example, tests and fix for Google APIs PSC endpoint

- modules/secret-manager/README.md
- modules/secret-manager/main.tf
- modules/secret-manager/variables.tf
> Added expire_time option to the secret-manager module

- blueprints/data-solutions/data-platform-foundations/03-orchestration.tf
- blueprints/data-solutions/vertex-mlops/ci-cd.tf
- blueprints/gke/autopilot/main.tf
- blueprints/gke/binauthz/main.tf
- blueprints/gke/patterns/autopilot-cluster/main.tf
- modules/artifact-registry/README.md
- modules/artifact-registry/main.tf
- modules/artifact-registry/outputs.tf
- modules/artifact-registry/variables.tf
- tests/modules/artifact_registry/examples/other-formats.yaml
* Fixes #2377
* Add support for new formats and remote repo types
* Variable changes for simplified interface
> Update `modules/artifact-registry` with newly-released features.

- blueprints/gke/patterns/batch/tutorial.md
- blueprints/gke/patterns/batch/versions_override.tf
Without versions override it fails with:
Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/kubectl: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/kubectl │
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see which modules are currently depending on hashicorp/kubectl, run the following command:
│     terraform providers
---
**Checklist**
> Fix tutorial error.

- fast/assets/templates/workflow-gitlab.yaml
- fast/stages/0-bootstrap/templates/workflow-gitlab.yaml
- fast/stages/1-resman/templates/workflow-gitlab.yaml
- fast/stages/1-tenant-factory/templates/workflow-gitlab.yaml
This fixes the gitlab templates. There is one other aspect that is relevant for gitlab self hosted users and not changed in this. The host keys need to point to their host
```
ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
ssh-keyscan gitlab.com | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
```
> gitlab workflow template fixes #2401

- fast/stages/0-bootstrap/automation.tf
Resolved an issue that appeared when applying FAST's bootstrap stage where merging blocks with conflicting key names were utilised to apply IAM bindings for service account impersonation between service accounts involved in CICD workload authorisation. This conflict resulted in only the final IAM binding from the merge block being applied, leading to incomplete and therefore incorrect IAM configurations that manifested itself during deployments using GitHub Actions.
---
**Checklist**
> [FAST] Fix IAM bindings to impersonate resman CICD SAs at bootstrap stage

- modules/project/service-agents.yaml
The correct format for this service account is documented in https://cloud.google.com/build/docs/cloud-build-service-account
---
**Checklist**
> fix cloudbuild service account email

- modules/ncc-spoke-ra/README.md
- tests/examples/variables.tf
- tests/examples_e2e/setup_module/e2e_tests.tfvars.tftpl
- tests/examples_e2e/setup_module/main.tf
- tests/fixtures/compute-vm-nva.tf
End-to-end tests for NCC Spoke RA Module.
(failing to reproduce failures observed in FAST cleanups)
---
**Checklist**
> E2E tests for ncc-spoke-ra

- blueprints/gke/patterns/autopilot-cluster/outputs.tf
- modules/artifact-registry/README.md
- modules/artifact-registry/outputs.tf
> Reintroduce docker image path output in AR module

- modules/net-firewall-policy/factory.tf
Add coalesce to factory net-firewall-policies to support empty yaml files.
---
**Checklist**
> Add coalesce to factory fw policies to support empty yaml files

- fast/assets/templates/workflow-github.yaml
- fast/assets/templates/workflow-gitlab.yaml
- fast/extras/0-cicd-gitlab/README.md
- fast/stage-links.sh
- fast/stages/0-bootstrap/README.md
- fast/stages/0-bootstrap/templates/workflow-github.yaml
- fast/stages/0-bootstrap/templates/workflow-gitlab.yaml
- fast/stages/1-resman/README.md
- fast/stages/1-resman/templates/workflow-github.yaml
- fast/stages/1-resman/templates/workflow-gitlab.yaml
- fast/stages/1-tenant-factory/README.md
- fast/stages/1-tenant-factory/templates/workflow-github.yaml
- fast/stages/1-tenant-factory/templates/workflow-gitlab.yaml
- fast/stages/2-networking-a-simple/README.md
- fast/stages/2-networking-b-nva/README.md
- fast/stages/2-networking-c-separate-envs/README.md
- fast/stages/2-security/README.md
- fast/stages/3-data-platform/dev/README.md
- fast/stages/3-gcve/prod/README.md
- fast/stages/3-gke-multitenant/dev/README.md
- fast/stages/3-project-factory/dev/README.md
Removes `alpha` from `gcloud storage cp`, as it moved to GA.
---
**Checklist**
> Remove alpha from gcloud storage cp as it moved to GA

- modules/compute-mig/autoscaler.tf
Fixed an obvious error.
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/ci-c3d-highcpu-60-build-canva.compute_mig/modules/compute-mig/autoscaler.tf line 222, in resource "google_compute_region_autoscaler" "default":
│  222:         schedule              = schedule.cron_schedule
│ 
│ This object does not have an attribute named "cron_schedule".
```
> Fix wrong expression in compute-mig module

- blueprints/gke/patterns/autopilot-cluster/outputs.tf
- modules/artifact-registry/README.md
- modules/artifact-registry/outputs.tf
All formats follow the same naming convention "$region-$format.pkg.dev". This PR simply renames the existing `docker_image_path` output to `url`.
> Add generic URL output to modules/artifiact-registry

- CONTRIBUTING.md
- tests/fixtures.py
- tools/plan_summary.py
Adds `--extra-files` option to plan_summary.py cmd
---
**Checklist**
> Add `--extra-files` option to plan_summary.py cmd

- modules/net-vpc-peering/main.tf
> Fix grammar in net-vpc-peering preconditions

- fast/stages/1-vpcsc/data/access-levels/geo.yaml
- modules/vpc-sc/README.md
- modules/vpc-sc/schemas/access-level.schema.json
- modules/vpc-sc/schemas/egress-policy.schema.json
- modules/vpc-sc/schemas/ingress-policy.schema.json
As discussed, this only covers the VPC-SC module and does not yet integrate the schemas in FAST.
> VPC-SC factory JSON Schemas

- tests/examples/conftest.py
- tests/examples/test_plan.py
- tests/examples/utils.py
- tests/examples_e2e/conftest.py
- tests/examples_e2e/test_plan.py
- tools/tfdoc.py
Improved the example testing machinery in anticipation of YAML schema testing. This includes the introduction of a generic `get_tftest_directive` function for parsing directives and their arguments, along with optimizations to avoid redundant directive parsing by storing parsed details within the Example object.
> example testing improvements

- modules/vpc-sc/schemas/access-level.schema.json
- tests/collectors.py
- tests/schemas/vpc-sc/fail-access-level-invalid-member-prefix.yaml
- tests/schemas/vpc-sc/fail-access-level-no-member-prefix.yaml
- tests/schemas/vpc-sc/pass-access-level-member-prefix.yaml
Allow files under `tests/schemas/` to be validated using a tftest directive
- Test FAST factory files: `pytest -v -k "fast and schema"`
- Validate all files under `tests/schemas/` against their schemas: `pytest -v -k "tests and schemas"`
- Validate schemas in YAML examples: `pytest -v -k "examples and yaml"`
- `pytest -v -k "(tests and schemas) or (fast and schema) or (examples and yaml)"`
> Extend test collector to include yaml files under tests/schemas/ and fast data files

- fast/stages/3-network-security/data/firewall-policy-rules/dev/egress.yaml
- fast/stages/3-network-security/data/firewall-policy-rules/dev/ingress.yaml
- fast/stages/3-network-security/schemas/firewall-policy-rules.schema.json
- modules/net-firewall-policy/README.md
- modules/net-firewall-policy/schemas/firewall-policy-rules.schema.json
- modules/net-vpc-firewall/README.md
- modules/net-vpc-firewall/schemas/firewall-rules.schema.json
This completes the schemas used in FAST factories. Also fixes VPC firewall schema merged in previous PR to include egress rules.
> Firewall policy module factory schema

- modules/kms/tags.tf
<p>
The current version of the KMS Terraform module uses the `google_tags_tag_binding` resource to bind tags to KMS key rings. However, according to the Terraform documentation, this resource is only applicable to projects, folders, and organizations. For non-global resources, such as KMS key rings, the correct resource to use is `google_tags_location_tag_binding`.
Moreover, through multiple tests on a corporate Terraform project, tag bindings using `google_tags_location_tag_binding` have been successful, whereas attempts with `google_tags_tag_binding` have not worked.
</p>
---
**Checklist**
> Use the `google_tags_location_tag_binding` Terraform resource to bind tags on KMS key rings

- modules/certificate-authority-service/README.md
- modules/certificate-authority-service/outputs.tf
Adds the `ca_pool` output object to certification-authority-service module.
---
**Checklist**
> Add ca pool object to certification-authority-service module

- modules/project-factory/factory-projects.tf
This Pull Request addresses two issues I stumbled upon, while working with your nice and shiny framework.
Projects configured in `folders_data_path` have their filename as key (see [code](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/project-factory/factory-projects.tf#L23), do note the use of `basename()` to get **only** the filename), whereas those from `projects_data_path` have their entire path, relative to `projects_data_path`, as key (see [code](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/project-factory/factory-projects.tf#L34), do note the absence of `basename()`).
This causes project files from the two sources to be key'ed differently, which has some implications down the line.
1. When `local.projects` is …
> Key inconsistency in project-factory and fix for null-value

- tests/examples_e2e/setup_module/main.tf
Adds pubsub to the list of jitsi service accounts for the default project. 
I wonder how this was working in the past...
> Add e2e pubusb errors

- fast/stages/0-bootstrap/organization.tf
Adding `compute.setNewProjectDefaultToZonalDNSOnly`, and `compute.restrictProtocolForwardingCreationForTypes` (as commented out code) to the list of importable policies for `bootstrap`
This is the list of automatically created org policies on a new organization as of 2024-09-13.
```bash
admin_@cloudshell:~$ gcloud resource-manager org-policies list --organization=xxxx --format=yaml
---
booleanPolicy:
enforced: true
constraint: constraints/compute.setNewProjectDefaultToZonalDNSOnly
etag: CJi8j7cGELi0htYC
updateTime: '2024-09-13T06:39:20.717331Z'
---
constraint: constraints/essentialcontacts.allowedContactDomains
etag: CJi8j7cGEODs29cC
listPolicy:
allowedValues:
- '@xxxxx.tld'
updateTime: '2024-09-13T06:39:20.720828Z'
---
constraint: constraints/iam.allowedPolicyMemberDomains
etag: …
```
> Update list of imported org policies

- blueprints/gcve/pc-minimal/README.md
- fast/stages/1-resman/README.md
- fast/stages/3-gcve/prod/README.md
- fast/stages/README.md
Hi! This is only a few README changes to:
- reflect an old change that the 1-resman stage in Fast doesn't deal with org policies on org level anymore, there are tags instead
- fix a few typos
---
**Checklist**
> README fixes to FAST docs

- modules/secure-source-manager-instance/iam.tf
Location field was missing causing an error:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "URL path has empty component",
│         "field": "projects/PROJECT_ID/locations//instances/INSTANCE_ID"
│       }
│     ]
│   }
│ ]
---
**Checklist**
> Add location for each SSM IAM resource

- modules/secure-source-manager-instance/README.md
- modules/secure-source-manager-instance/iam.tf
- modules/secure-source-manager-instance/main.tf
- modules/secure-source-manager-instance/outputs.tf
- modules/secure-source-manager-instance/variables.tf
- tests/modules/secure_source_manager_instance/examples/iam-bindings-additive.yaml
- tests/modules/secure_source_manager_instance/examples/iam-bindings.yaml
- tests/modules/secure_source_manager_instance/examples/iam.yaml
- tests/modules/secure_source_manager_instance/examples/private-instance.yaml
- tests/modules/secure_source_manager_instance/examples/public-instance-with-cmek.yaml
- tests/modules/secure_source_manager_instance/examples/public-instance.yaml
Modified the secure-source-manager-instance module to allow management of an existing instance (eg create repos and manage IAM). Also removed the location attr from the repositories var as it needs to be the same as the instance, so this would save having to enter a location for each repo being created.
---
**Checklist**
> Allow manage existing SSM instance

- modules/artifact-registry/README.md
- modules/artifact-registry/iam.tf
- modules/artifact-registry/main.tf
- modules/artifact-registry/outputs.tf
- modules/artifact-registry/variables-iam.tf
- modules/artifact-registry/variables.tf
- tests/modules/artifact_registry/examples/iam.yaml
This PR implements the new IAM interface in the `atifact-registry` module (#2605)
In order to have a consistent interface across the different modules, this update will cause a delete/create of the existing permissions set in the `iam` variable: 
```
+ resource "google_artifact_registry_repository_iam_binding" "authoritative" {
+ etag       = (known after apply)
+ id         = (known after apply)
+ location   = "europe"
+ members    = [
+ "allUsers",
]
+ project    = "xxredactedxx"
+ repository = "public"
+ role       = "roles/artifactregistry.reader"
}
- resource "google_artifact_registry_repository_iam_binding" "bindings" {
- etag       = "xxredactedxx" -> null
- id         = "xxredactedxx" -> null
- location   = "europe" -> null
- members    = [
- "allUsers",
] -> null
- project    = …
```
> feat: implement the new iam interface in `artifact-registry`

- modules/alloydb/README.md
- modules/alloydb/main.tf
- modules/alloydb/variables.tf
Include secondary cluster and instance variables in the cross_region_replication one
> Alloydb variables refactor

- modules/artifact-registry/iam.tf
Happy to be the first one to complain 🙂 
As mentionned by @juliocc in https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2606 the move is failing if we transfer the resource to the non-beta provider:
```
│ The "google_artifact_registry_repository_iam_binding" resource type does
│ not support moving resource state across resource types.
```
The TF 1.8 has introduced a new feature that makes the move failing (I was testing with 1.7 in #2606):
> Providers can now transfer the ownership of a remote object between resources of different types, for situations where there are two different resource types that represent the same remote object type.
> This extends the moved block behavior to support moving between two resources of different types only if the provider for the …
> fix(artifact-registry): fix a move issue with tf>1.7

- fast/stages/2-networking-b-nva/nva-simple.tf
Fixes FAST stage 2-b (simple NVA) wrong location setting on MIGs, which is causing test failures.
---
**Checklist**
> [FAST] Fix stage 2 simple NVA wrong location - causing test failures

- fast/stages/2-networking-a-simple/data/dns-policy-rules.yaml
- fast/stages/2-networking-b-nva/data/dns-policy-rules.yaml
- fast/stages/2-networking-c-separate-envs/data/dns-policy-rules.yaml
- tests/fast/stages/s2_networking_a_simple/ncc.yaml
- tests/fast/stages/s2_networking_a_simple/simple.yaml
- tests/fast/stages/s2_networking_a_simple/vpn.yaml
- tests/fast/stages/s2_networking_b_nva/ncc-ra.yaml
- tests/fast/stages/s2_networking_b_nva/regional.yaml
- tests/fast/stages/s2_networking_b_nva/simple.yaml
- tests/fast/stages/s2_networking_c_separate_envs/simple.yaml
Adding "*.gke.goog" to private google access default DNS configuration.
This will allow DNS based access to GKE clusters from on-premise and in GCP, solving transitivity issues and allowing more secure GKE control plane access (https://cloud.google.com/kubernetes-engine/docs/how-to/latest/network-isolation#modify_the_control_plane_access).
---
**Checklist**
- [ X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X ] Ran `terraform fmt` on all modified files
- [] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [] Made sure all relevant tests pass
> Adding DNS for GKE control plane to private google access APIs

- modules/gke-hub/main.tf
Fixes issue with current module where enabling Config Sync does not work because of missing `enabled=true` field.
---
**Checklist**
> Add required enabled field introduced in Terraform version 5.41.0

- fast/stages/0-bootstrap/organization.tf
- tests/fast/stages/s0_bootstrap/simple.yaml
Role was managed by both stages 0 and 1, it should only be managed by 1.
> Fix permadiff in bootstrap IAM

- modules/cloud-run-v2/README.md
- modules/cloudsql-instance/README.md
- tests/modules/cloud_run_v2/examples/cloudsql.yaml
- tests/modules/cloudsql_instance/examples/custom.yaml
- Cloud Run - connecting to Cloud SQL
- Cloud SQL - creating users for IAM service account
---
**Checklist**
> Additional examples for Cloud Run and Cloud SQL

- modules/cloud-run-v2/job.tf
When attempting to mount GCS or NFS volumes, the following error message would appear:
```
│ Error: Unsupported attribute
│
│   on .terraform/modules/deploy_backfill_tmdb/modules/cloud-run-v2/job.tf line 133, in resource "google_cloud_run_v2_job" "job":
│  133:               bucket    = volumes.value.bucket
│     │ volumes.value is object with 5 attributes
│
│ This object does not have an attribute named "bucket".
╵
╷
│ Error: Unsupported attribute
│
│   on .terraform/modules/deploy_backfill_tmdb/modules/cloud-run-v2/job.tf line 134, in resource "google_cloud_run_v2_job" "job":
│  134:               read_only = volumes.value.is_read_only
│     │ volumes.value is object with 5 attributes
│
│ This object does not have an attribute named …
```
> Fix the location of the GCS and NFS attributes

- modules/README.md
updates the snippet on how to reference Fabric modules using github tags to the latest tag (`v35.0.0`).
---
**Checklist**
> bump modules/README github tag reference

- modules/vpc-sc/README.md
- modules/vpc-sc/factory.tf
- tests/modules/vpc_sc/examples/factory.yaml
This PR fixes the issue described in issue #2675. I've also adapted one of the example based tests so that the incorrect behavior is checked in the future.
---
**Checklist**
> Fix "inconsistent conditional result types" error in `modules/vpc-sc`

- modules/cloud-run-v2/README.md
- modules/cloud-run-v2/service.tf
- tests/modules/cloud_run_v2/examples/gcs-mount.yaml
closes #2684
---
**Checklist**
> Fix gcs & NFS mounts for cloud-run-v2 service

- fast/stages/0-bootstrap/data/custom-roles/project_iam_viewer.yaml
- tests/fast/stages/s0_bootstrap/simple.yaml
- tests/fast/stages/s1_resman/simple.tfvars
GCP roles only capitalize the first letter of IAM:
> Make project iam viewer name consistent with GCP naming

- modules/cloud-run-v2/README.md
- modules/iam-service-account/README.md
- modules/iam-service-account/outputs.tf
- modules/pubsub/README.md
- tests/modules/pubsub/examples/bigquery-subscription-with-service-account.yaml
Make outputs of service account depend on the IAM grants given within the module, so SA has all necessary permissions when used in other contexts. 
---
**Checklist**
> Fix E2E tests

- modules/cloud-run-v2/job.tf
- modules/cloud-run-v2/service.tf
Closes: #2698
Testcase:
```hcl
module "project" {
source         = "./fabric/modules/project"
name           = var.project_id
project_create = false
services = ["file.googleapis.com"]
}
module "bucket" {
source     = "./fabric/modules/gcs"
project_id = var.project_id
prefix     = var.prefix
name       = "my-bucket"
location   = var.region
versioning = true
labels = {
cost-center = "devops"
}
iam = {
"roles/storage.objectAdmin" = ["serviceAccount:${module.project.default_service_accounts.compute}"]
}
}
module "bucket2" {
source     = "./fabric/modules/gcs"
project_id = var.project_id
prefix     = var.prefix
name       = "my-bucket2"
location   = var.region
versioning = true
labels = {
cost-center = "devops"
}
iam = {
"roles/storage.objectAdmin" = …
```
> Fix non-empty plan after mixing CloudSQL with other mounts

- blueprints/apigee/apigee-x-foundations/README.md
- blueprints/apigee/apigee-x-foundations/outputs.tf
Added outputs to apigee-x-foundations blueprint (instances and lbs)
---
**Checklist**
> Added outputs to apigee-x-foundations blueprint (instances and lbs)

- tools/pre-commit-tfdoc.sh
Use read line instead of xargs. While probably a bit slower, this works reliably on Linux and OS X. (BSD and GNU xargs are unfortunately with different arguments) Also added option to set Python binary (eg. export PYTHON=python3). pre-commit.com hooks stash uncommitted changes, so patching it locally isn't really a good option.
On OS X:
```
Regenerate README.md with tfdoc.py........................................Failed
- hook id: cff-readme
- exit code: 1
xargs: command line cannot be assembled, too long
```
> Change tfdoc pre-commit hook script to use while read

- .github/workflows/linting.yml
- .github/workflows/tests.yml
Maintainers occasionally force push to these branches. This will allow tests to run without the need for a dummy PR
> Run tests and linting when pushing to master or fast-dev

- fast/stages/0-bootstrap/organization.tf
We cannot run apply with org-level billing accounts, and this was only caught after releasing.
> Add missing role to FAST stage 0 org-level delegated IAM grants

- modules/net-swp/policy-rules.tf
Adds basename to SWP policy rules factory
---
**Checklist**
> Add basename to SWP policy rules factory

- blueprints/networking/ha-vpn-over-interconnect/README.md
- modules/net-vlan-attachment/README.md
- modules/net-vlan-attachment/main.tf
- modules/net-vlan-attachment/outputs.tf
- modules/net-vlan-attachment/variables.tf
Add ability to automatically generate MD5 keys in VLAN attachments module.
---
> Add optional automated MD5 generation to net-vlan-attachment module

- blueprints/apigee/network-patterns/nb-glb-psc-neg-sb-psc-ilbl7-hybrid-neg/README.md
- blueprints/networking/private-cloud-function-from-onprem/README.md
- blueprints/networking/vpc-connectivity-lab/README.md
- blueprints/serverless/cloud-run-corporate/README.md
- modules/net-vpn-ha/README.md
- modules/net-vpn-ha/main.tf
- modules/net-vpn-ha/outputs.tf
- modules/net-vpn-ha/variables.tf
- tests/fast/stages/s2_networking_a_simple/simple.yaml
- tests/fast/stages/s2_networking_a_simple/vpn.yaml
- tests/fast/stages/s2_networking_b_nva/ncc-ra.yaml
- tests/fast/stages/s2_networking_b_nva/regional.yaml
- tests/fast/stages/s2_networking_b_nva/simple.yaml
- tests/fast/stages/s2_networking_c_separate_envs/simple.yaml
- tests/modules/net_vpn_ha/examples/gcp-to-gcp.yaml
- tests/modules/net_vpn_ha/examples/gcp-to-onprem.yaml
- tests/modules/net_vpn_ha/examples/ipv6.yaml
- Add ability to autogenerate MD5 keys in net-vpn-ha.
- Fix VPN tunnels secret outputs
---
**Checklist**
> Add ability to autogenerate md5 keys in net-vpn-ha

- modules/logging-bucket/README.md
- modules/logging-bucket/iam.tf
- modules/logging-bucket/main.tf
- modules/logging-bucket/outputs.tf
- modules/logging-bucket/variables.tf
- modules/project/README.md
- modules/project/logging.tf
- modules/project/variables-observability.tf
- modules/project/variables.tf
- tests/modules/logging_bucket/examples/views.yaml
- tests/modules/project/examples/log-scopes.yaml
- Add views, and tags support to logging buckets
- Add log scopes to project
---
**Checklist**
> Add support for log views and log scopes

- adrs/20241029-versioning.md
- adrs/20241219-tag-bindings.md
- adrs/fast/1-network-ranges.md
- adrs/modules/20231106-factories.md
- Add new ADR document why we use `map(string)` for `tag_bindings`
- Small fixes in other ADRs
> Document `tag_bindings` definition as `map(string)`

- modules/net-lb-app-ext-regional/main.tf
- modules/net-lb-app-ext/main.tf
- modules/net-lb-app-int/main.tf
An empty `ssl_certificates` list will conflict with a user-defined `certificate_manager_certificates` value, so exclude it.
This was fixed in https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2764, but only for the `net-lb-app-int` module and not for the `net-lb-app-ext` or `net-lb-app-ext-regional` modules.
I'm not sure why `net-lb-app-int-cross-region` doesn't allow a user to set a value for `ssl_certificates`, but I'm going to leave it alone.
Screenshot from https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/2760
---
**Checklist**
> Fix handling of SSL certificates in external load balancer modules

- modules/net-vpc/psa.tf
Sometimes [E2E tests](https://github.com/GoogleCloudPlatform/fast-e2e/actions/runs/12500889107) fail with:
```
Error: Error waiting for Create Service Networking Connection: Error code 9, message: Allocated IP range \'servicenetworking-googleapis-com-cloud-sql\' not found in network.
```
This should prevent this (and make PSA connection creation more reliable).
---
**Checklist**
> Make PSA connection more robust

- blueprints/gke/patterns/autopilot-cluster/cluster.tf
Without this change, terraform errors with:
│ Error: Cycle: module.project.google_storage_bucket_iam_member.gcs-sinks-binding, module.project.google_project_iam_member.project-sinks-binding, module.project.google_essential_contacts_contact.contact, module.project.google_bigquery_dataset_iam_member.bq-sinks-binding, module.project.google_project_iam_member.bucket-sinks-binding, module.project (close), module.project.output.sink_writer_identities (expand), local.cluster_sa (expand), module.project.var.iam_bindings_additive (expand), module.project.google_project_iam_member.bindings, module.project.google_logging_project_sink.sink, module.project.google_pubsub_topic_iam_member.pubsub-sinks-binding
The actual error is wrong variable reference. :shrug: 
Maybe we need add tests for those …
> Fix cycle in the autopilot-cluster blueprint

- adrs/fast/addon-stages.md
To be discussed. Example working implementation of netsec refactored as described in this ADR, except for the README [is here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/ludo/netsec-envs/fast/stages/2-network-security).
> ADR proposal for FAST add-on stages

- fast/stages/1-resman/outputs-cicd.tf
> feat: restructure how var files are provided to workflow templates

- modules/compute-vm/README.md
- tests/modules/compute_vm/examples/alias-ips.yaml
- tests/modules/compute_vm/examples/confidential.yaml
- tests/modules/compute_vm/examples/defaults.yaml
- tests/modules/compute_vm/examples/disk-options.yaml
- tests/modules/compute_vm/examples/group.yaml
- tests/modules/compute_vm/examples/gvnic.yaml
- tests/modules/compute_vm/examples/iam.yaml
- tests/modules/compute_vm/examples/independent-boot-disk.yaml
- tests/modules/compute_vm/examples/instance-schedule-create.yaml
- tests/modules/compute_vm/examples/instance-schedule-id.yaml
- tests/modules/compute_vm/examples/ips.yaml
- tests/modules/compute_vm/examples/metadata.yaml
- tests/modules/compute_vm/examples/sa-custom.yaml
- tests/modules/compute_vm/examples/sa-default.yaml
- tests/modules/compute_vm/examples/sa-managed.yaml
- tests/modules/compute_vm/examples/sa-none.yaml
- tests/modules/compute_vm/examples/snapshot-schedule-create.yaml
- tests/modules/compute_vm/examples/sole-tenancy.yaml
- tests/modules/compute_vm/examples/spot.yaml
- tests/modules/compute_vm/examples/tag-bindings.yaml
- tests/modules/compute_vm/examples/template.yaml
Add E2E tests and fix examples:
* boot disk image configuration fixes
* updated docs for alias IPs and gVNIC
* added IAM grant and note about permissions for service agent for Instance Schedules
* use Confidential Compute compatible image and instance type
---
**Checklist**
> modules/compute-vm end-to-end tests and fixes

- fast/stages/0-bootstrap/outputs-providers.tf
- Use map to lookup stage parent config. Fixes bug with a ternary that was testing against an invalid value
- Use email (instead of name) for impersonation field
> Fix stage 1 addons provider outputs

- fast/stages/1-resman/stage-2-security.tf
This fix prevents
```
╷
│ Error: Invalid index
│
│   on stage-2-security.tf line 54, in module "sec-folder":
│   54:       "roles/resourcemanager.tagUser"        = [module.net-sa-rw[0].iam_email]
│     │ module.net-sa-rw is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
╷
│ Error: Invalid index
│
│   on stage-2-security.tf line 57, in module "sec-folder":
│   57:       "roles/resourcemanager.tagViewer"      = [module.net-sa-ro[0].iam_email]
│     │ module.net-sa-ro is empty tuple
```
when 
```tfvars
fast_stage_2 = {
networking = { enabled = false }
}
```
> Allow networking stage to be disabled

- modules/certificate-manager/main.tf
- tests/modules/certificate_manager/examples/map-with-managed-cert-dns-authz.yaml
Closes #2832
---
**Checklist**
> fix(certificate-manager): reference dns_authz by fully qualified id

- modules/data-catalog-tag-template/README.md
- modules/data-catalog-tag-template/iam.tf
- modules/data-catalog-tag-template/main.tf
- modules/data-catalog-tag-template/outputs.tf
- modules/data-catalog-tag-template/schemas/tag-template.schema.json
- modules/data-catalog-tag-template/variables.tf
This is a prerequisite for the new data foundation design, and implements support for tag-level IAM. It also refactors a few bits to improve the module interface, and adds a json schema for the factory.
> Refactor data catalog tag template module

- modules/cloud-run-v2/README.md
Resources in subnet are in use for ~1-2h after removal of Cloud Run instance (see: https://cloud.google.com/run/docs/configuring/vpc-direct-vpc#delete-subnet)
b/332419038
---
**Checklist**
> Disable E2E test for direct VPC Egress

- modules/compute-vm/README.md
Fixes:
```
Plan: 5 to add, 0 to change, 0 to destroy.
module.project.google_project_service.project_services["compute.googleapis.com"]: Creating...
module.project.google_project_service.project_services["compute.googleapis.com"]: Creation complete after 4s [id=***-1738911960w5-prj/compute.googleapis.com]
module.project.google_project_iam_member.service_agents["compute-system"]: Creating...
module.project.google_project_iam_member.service_agents["compute-system"]: Creation complete after 7s [id=***-1738911960w5-prj/roles/compute.serviceAgent/serviceAccount:service-223793131721@compute-system.iam.gserviceaccount.com]
module.project.google_project_iam_member.bindings["compute-admin-service-agent"]: Creating...
module.instance.google_compute_resource_policy.schedule[0]: Creating... …
```
> Add dependency for compute-vm schedule

- fast/stages/0-bootstrap/data/custom-roles/organization_admin_viewer.yaml
- fast/stages/1-resman/data/top-level-folders/teams.yaml
- tests/fast/stages/s1_resman/simple.yaml
Allow the Project factory read only SA to retrieve buckets IAM policy for buckets created by the PF
---
**Checklist**
> Add bucket IAM policy read

- modules/alloydb/README.md
- modules/cloud-function-v1/README.md
- modules/cloud-run-v2/README.md
- modules/cloudsql-instance/README.md
- modules/compute-vm/README.md
- modules/dataproc/README.md
- modules/gcs/README.md
- modules/kms/README.md
- modules/project/README.md
- modules/secret-manager/README.md
- tests/modules/kms/examples/basic.yaml
- tests/modules/kms/examples/import-job.yaml
- tests/modules/kms/examples/purpose.yaml
- tests/modules/project/examples/data.yaml
- tools/create_e2e_sandbox.sh
Add `var.prefix` to keyring names, as they are [not removed](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/kms_key_ring) on destroy. This allows retried E2E tests to complete.
Fix creation of E2E sandbox, so all necessary files are created and random `var.prefix` value is set.
---
**Checklist**
> Fix KMS E2E tests

- blueprints/cloud-operations/vm-migration/host-target-projects/README.md
- blueprints/cloud-operations/vm-migration/host-target-projects/main.tf
- blueprints/cloud-operations/vm-migration/single-project/README.md
- blueprints/cloud-operations/vm-migration/single-project/main.tf
- modules/iam-service-account/README.md
- modules/iam-service-account/main.tf
- modules/iam-service-account/outputs.tf
- modules/iam-service-account/variables.tf
Remove Service Account key generation functionality as it stores the generated key in state. Users wanting to use this functionality, it is possible by adding `google_service_account_key` referring service account email.
---
**Checklist**
** Upgrade Notes **
```upgrade-note
modules/iam-service-account: Removed service account key generation functionality
```
> Remove Service Account key generation

- modules/dns/outputs.tf
#1728 introduced a `count` for the `google_dns_keys.dns_keys` data source, but the corresponding output was not updated accordingly.
---
**Checklist**
> output dns_keys instead of a list

- modules/project-factory/main.tf
Currently, failed interpolations fail with the error message like this:
```
Error: invalid value for member (IAM members must have one of the values outlined here: https://cloud.google.com/billing/docs/reference/rest/v1/Policy#Binding)
with module.projects-iam["service1"].google_project_iam_member.shared_vpc_host_iam["rw"],
on ../project/shared-vpc.tf line 131, in resource "google_project_iam_member" "shared_vpc_host_iam":
131:   member     = each.value
```
This is not helpful, when looking for a source of the issue. With this PR, error messages look like this:
```
Error: Error in function call
on main.tf line 173, in module "projects-iam":
173:         try(
174:           # project service accounts
175:           module.service-accounts["${each.key}/${v}"].iam_email,
176:           # …
```
> Add error messages for failing interpolations

- fast/stages/1-resman/stage-2.tf
The stage2 CICD SAs were not being granted roles/iam.serviceAccountTokenCreator on the corresponding stage2 SAs. For whatever reason the code was appending "-prod" to the cicd-sa-ro/rw keys when adding them resulting in nulls. 
---
**Checklist**
> Fix CICD SA access

- modules/project/README.md
- tests/modules/project/examples/data.yaml
Fix error:
```
Error: Error creating Policy: googleapi: Error 403: Permission \'orgpolicy.policies.create\' denied on resource \'//cloudresourcemanager.googleapis.com/projects/***-1740759668w4-***-1740759668w4-project\' (or it may not exist).
Details:
[
{
"@type": "type.googleapis.com/google.rpc.ErrorInfo",
"domain": "cloudresourcemanager.googleapis.com",
"metadata": {
"permission": "orgpolicy.policies.create",
"resource": "projects/***-1740759668w4-***-1740759668w4-project"
},
"reason": "IAM_PERMISSION_DENIED"
}
]
```
In the test. Prefix was included twice in the project name, so the call was targeting wrong project. 
---
**Checklist**
> Fix failing E2E test for module/project

- modules/cloudsql-instance/README.md
- modules/net-vpc/README.md
- tests/examples_e2e/conftest.py
- tests/examples_e2e/setup_module/main.tf
- tests/examples_e2e/test_plan.py
- tests/fixtures.py
Fix tests:
* examples_e2e.test_plan.test_example[terraform:modules/gcs:GCS notifications:1]
* examples_e2e.test_plan.test_example[terraform:modules/gcs:Cloud KMS:1]
By adding `google_storage_project_service_account` and `google_bigquery_default_service_account` to setup_module for E2E tests. This should fix the issue with missing service accounts reported by some of the tests:
```
Error 400: Service account service-***@gs-project-accounts.iam.gserviceaccount.com does not exist., badRequest
```
Fix tests using Private Service Access with `ABANDON` policy, by adding a new tag to tests: `isolated`.
Isolated tests do not reuse test project, but instead they always get a fresh one, and it is discarded after the test is run. As `ABANDON` policy to remove results in project in a different state …
> Introduce test isolation and fix missing GCS service account

- fast/stages/2-project-factory/README.md
- fast/stages/2-project-factory/outputs.tf
> Fix localfile project factory readme

- modules/dns/README.md
- modules/dns/main.tf
- modules/dns/variables.tf
- tests/modules/dns/examples/reverse-zone-managed.yaml
Allow creation of a lookup zones in Cloud DNS that have records (unmanaged). Add a flag to create managed zones, where records are added automatically.
I'm not sure what is the exact use case for managed reverse lookup zone, so I decided to make it a non-default option, and make an un-managed the default, happy to change that if managed approach is prevalent. 
---
**Checklist**
**Breaking Changes**
```upgrade-note
`modules/dns`: Reverse zones are by default created as unmanaged now. To keep your zone as managed, please set `var.zone_config.private.reverse_managed` to `true`
```
> Allow un-managed reverse lookup zones

- modules/net-vpc/README.md
- modules/net-vpc/schemas/subnet.schema.json
- tests/modules/net_vpc/examples/subnet-options.yaml
**Description**
- Fixed the subnet JSON schema in the `net-vpc` module to include the `allow_subnet_cidr_routes_overlap` attribute
- Added example code for hybrid subnets implementation
---
**Checklist**
> Fix subnet schema in net-vpc module & hybrid subnets example implementation

- .github/workflows/linting.yml
- .pre-commit-config.yaml
- modules/project-factory/README.md
- modules/project-factory/factory-projects-object.tf
- modules/project-factory/factory-projects.tf
- tools/duplicate-diff.py
Create separate file for canonicalization of project factory objects and introduce duplicate-diff lint checker.
TODO:
---
**Checklist**
> Project object c14n in separate file

- blueprints/third-party-solutions/gitlab/README.md
- blueprints/third-party-solutions/gitlab/assets/cloud-config.yaml
- blueprints/third-party-solutions/gitlab/gitlab.tf
- blueprints/third-party-solutions/gitlab/services.tf
- blueprints/third-party-solutions/gitlab/variables.tf
As per the title this PR fixes Cloud SQL deployment adapting module arguments and update gitlab deployment to leverage local regional remote docker artifact registry for pulling gitlab ce image
- [] Made sure all relevant tests pass
> Fix Cloud SQL deployment and use local remote docker hub for pulling gitlab docker image

- fast/stages/0-bootstrap/data/custom-roles/storage_viewer.yaml
Removes object creator permission from storage viewer custom role.
---
**Checklist**
> [FAST] Remove object creator permission from storage viewer custom role

- modules/net-vpc-factory/factory-project.tf
- modules/net-vpc-factory/factory-projects-object.tf
- tools/duplicate-diff.py
> Use factory-projects-object to normalize inputs for project module in net-vpc-factory

- modules/compute-vm/main.tf
- modules/compute-vm/resource-policies.tf
When using independent disks, the snapshot policy was not correctly referring the boot disks.
I decided not to align the boot-disk name when using independent disks, to avoid forcing everybody (using independent disks) to recreate instances when upgrading the module.
Closes: #3064
---
**Checklist**
> fix reference to boot disk in snapshots when using independent disks

- modules/cloudsql-instance/README.md
Adds `cloudsql_iam_authentication` flag example defining SA users in `cloudsql-instance` module.
---
**Checklist**
> [cloudsql-instance] Add cloudsql_iam_authentication flag to fix example in readme

- modules/cloud-run-v2/README.md
- modules/cloud-run-v2/service.tf
- modules/cloud-run-v2/variables.tf
- tests/modules/cloud_run_v2/examples/service-otel-sidecar.yaml
- Adds `depends_on` flag to container definition
- Adds `port` to HTTP liveness & startup probes
---
**Checklist**
> [cloud-run-v2] Add ability to deploy OpenTelemetry Collector sidecar

- modules/alloydb/README.md
- modules/alloydb/main.tf
- modules/alloydb/outputs.tf
- modules/alloydb/variables.tf
- modules/alloydb/versions.tf
- modules/alloydb/versions.tofu
- tests/modules/alloydb/examples/cmek.yaml
- tests/modules/alloydb/examples/custom.yaml
- tests/modules/alloydb/examples/psc.yaml
- tests/modules/alloydb/examples/read_pool.yaml
- tests/modules/alloydb/examples/simple.yaml
* Added support for read poll instances.
* Added support for public (outbound) IPs.
* Added new arguments: `machine_type`, `skip_await_major_version_upgrade`, and `subscription_type`.
* Added outputs for key cluster attributes, including ID and name.
* Improved input variable validations and simplified configurations.
* Fixed bug where AlloyDB user accounts always had null passwords.
* Resolved Terraform state drift issues for `network_config` and `psc_config`.
* Fixed `continuous_backup_config` always being implicitly or explicitly enabled.
* Fixed `automated_backup_policy` and `maintenance_update_policy`, which do not support non-zero minutes, seconds and nanos.
* Fixed various typos.
* Aligned the format of test examples.
---
**Checklist**
> AlloyDB read poll support and various usability fixes

- modules/cloud-run-v2/job.tf
- modules/cloud-run-v2/main.tf
Adds ability to optionally update Cloud Run job containers outside Terraform.
---
**Checklist**
> Add ability to optionally update Cloud Run job containers outside Terraform

- modules/project-factory/README.md
- modules/project-factory/folders.tf
- modules/project-factory/main.tf
- tests/modules/project_factory/examples/example.yaml
Service account emails are static and can be used in context replacements.
> Enable context replacements for IAM principals in project factory module

- modules/cloudsql-instance/main.tf
Trying to infer that whether backups should be enabled or not if it causing isues with DMS. DMS when you configure a migration job, demotes the destination instance to a replica and replicas do no allow backups, so if you created the instance originally with this module you will have a drift in the backup enablement always, because you are forcing the value programatically
---
**Checklist**
> Backup enablement for CloudSQL instance should be only based on user provided settings

- modules/project-factory/README.md
- modules/project-factory/main.tf
- tests/modules/project_factory/examples/example.yaml
Project Factory: fixes reference to automation SAs in IAM block for service accounts
---
> Project Factory: fix reference to automation SAs in IAM block for service accounts

- modules/project-factory/README.md
- modules/project-factory/automation.tf
- modules/project-factory/schemas/project.schema.json
- modules/project-factory/schemas/project.schema.md
This supersedes #3097 by optionally exposing the prefix used in automation resource names by the project factory.
Old behaviour and new behaviour if prefix is unset, is to use the project id as the prefix in automation resource names. This is of course to a) guarantee univocity of the bucket name, b) allow easy identification of resources in the IaC project, which pools automation resources for many application-level projects.
This yaml shows the above and will generate a `[project id]-tf-state` bucket and a `[project id]-rw` service account. 
```yaml
automation:
project: foo-iac-0
service_accounts:
rw:
description: Read/write automation service account for apt registries.
bucket:
description: Terraform state bucket for apt registries.
```
New behaviour when `automation.prefix` is set is …
> Allow explicit definition of automation prefix in project factory

- modules/cloudsql-instance/outputs.tf
Return correct value for cloudsql primary instance id
---
**Checklist**
> Return instance ID not IP address

- modules/net-swp/README.md
- tests/modules/net_swp/examples/transparent-proxy.yaml
Based on #3140 by @apichick , improving transparent proxy example to use `modules/net-address`.
---
**Checklist**
> Improve SWP transparent gateway example

- fast/stages/0-bootstrap/data/custom-constraints/gke.yaml
- fast/stages/0-bootstrap/data/org-policies-managed/gke.yaml
- fast/stages/0-bootstrap/data/org-policies/gke.yaml
- fast/stages/1-resman/README.md
- fast/stages/1-resman/main.tf
- fast/stages/1-resman/organization-tags.tf
- fast/stages/1-resman/organization.tf
- tests/fast/stages/s0_bootstrap/cicd.yaml
- tests/fast/stages/s0_bootstrap/managed_org_policies.yaml
- tests/fast/stages/s0_bootstrap/simple.yaml
- tests/fast/stages/s0_bootstrap/simple_org_policies.yaml
This also disables a custom constraint for GKE which needs to be imported and raises errors on apply.
> Improve and document org policy tags use in FAST resman stage

- .pre-commit-config.yaml
- fast/stages/2-networking-a-simple/data/dns-policy-rules.yaml
- fast/stages/2-networking-b-nva/data/dns-policy-rules.yaml
- fast/stages/2-networking-c-separate-envs/data/dns-policy-rules.yaml
- tests/fast/stages/s2_networking_a_simple/ncc.yaml
- tests/fast/stages/s2_networking_a_simple/simple.yaml
- tests/fast/stages/s2_networking_a_simple/vpn.yaml
- tests/fast/stages/s2_networking_b_nva/ncc-ra.yaml
- tests/fast/stages/s2_networking_b_nva/regional.yaml
- tests/fast/stages/s2_networking_b_nva/simple.yaml
- tests/fast/stages/s2_networking_c_separate_envs/simple.yaml
- tools/duplicate-diff.py
Add missing policy routing for Private Google Access
Added checks to keep files in sync between stages
Closes #3159
---
**Checklist**
> Add notebooks, appengine and appspot to dns policy routing in FAST networking stage

- modules/cloud-run-v2/job.tf
- modules/cloud-run-v2/service.tf
When using service unmanaged version, tf should not track labels created by gh action  google-github-actions/deploy-cloudrun@v2:
1) commit-sha (gh action adds this label)
2) goog-terraform-provisioned (gh action removes this label)
3) managed-by (gh action adds this label)
---
**Checklist**
> feat: ignores labels added by gh action in unmanaged cloud run service / job

- fast/stages/1-resman/organization.tf
fixed option to set descriptions for environment tag values. Currently it indexes on the key/short name from the bootstrap environment var/output, instead of the tag name that the rest of this references in resman. Similar to how it's defined for IAM customisations a few lines above
---
**Checklist**
> Fixed option to set descriptions for environment tag values

- fast/stages/2-networking-a-simple/data/dns-policy-rules.yaml
- fast/stages/2-networking-b-nva/data/dns-policy-rules.yaml
- fast/stages/2-networking-c-separate-envs/data/dns-policy-rules.yaml
The `accounts.google.com` endpoint does not work via PGA since it requires user-level interaction in the browser. This change bypasses resolution in the DNS response policies, to allow OAuth flows against Google as an IdP to work from inside VPCs.
> Bypass accounts.google.com in FAST DNS policy rules

- modules/net-vpc/README.md
- modules/net-vpc/schemas/subnet.schema.json
- modules/net-vpc/schemas/subnet.schema.md
- modules/net-vpc/subnets.tf
- modules/net-vpc/variables.tf
- tests/modules/net_vpc/examples/ipv6_only.yaml
This PR adds support for IPv6-only subnets.  IP collections may also be specified to use Bring Your Own IPv6 prefixes when creating the subnet.
---
> Add support for IPv6 only subnets and IP collections

- modules/project-factory/automation.tf
- modules/project-factory/factory-projects.tf
- modules/project-factory/main.tf
- modules/project-factory/schemas/project.schema.json
- modules/project-factory/schemas/project.schema.md
Added option to set force_destroy on the buckets in the project-factory module. For #3188 
---
**Checklist**
> Added option to set force_destroy on pf buckets

- modules/net-vpc/subnets.tf
Create (or import) subnets with empty description. Google forces recreate on subnet description change (for some reason). This change lines up how the alternative types of subnets (proxy only/PSC) handles descriptions with how the regular subnet blocks handles descriptions. This is required when importing existing subnets into the subnet factory that don't have a description without needed to recreate the whole subnet.
---
**Checklist**
> Create (or import) subnets with empty description

- CONTRIBUTING.md
- tools/build_service_agents.py
- tools/tfdoc.py
- tools/versions.py
This change adds inline [PEP 723-style](https://peps.python.org/pep-0723/) dependencies to a few of our script tools.
This simplifies the workflow for contributors, especially those without a fully configured Python environment. Now, anyone can run these tools directly using uv, which will automatically manage the necessary dependencies.
> Add PEP 723 dependencies to tfdoc.py, versions.py and build_service_agents.py

- modules/project-factory/main.tf
Fixes broken substitution of Service Agents when calling module `project-iam`. Setting `iam_bindings` and `iam_bindings_additive` now substitutes like `iam`, where it already works.
Addresses the substitution issue described here: https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/3208
---
**Checklist**
> Fix for service agent substitutions in project factory additive bindings

- modules/compute-vm/README.md
- modules/compute-vm/outputs.tf
- modules/compute-vm/template.tf
This PR fixes the null outputs when creating regional instance templates.
Fixes #3225
---
**Checklist**
> Support regional instance templates in compute-vm module outputs

- modules/project-factory/factory-projects.tf
Fixes force_destroy for project factory buckets
---
**Checklist**
> Fixes force_destroy for project factory buckets

- modules/net-vpc-factory/factory-project.tf
- modules/net-vpc-factory/factory-projects-object.tf
- modules/net-vpc-factory/schemas/network-project.schema.json
- modules/project-factory/factory-projects-object.tf
- modules/project-factory/main.tf
- modules/project-factory/schemas/project.schema.json
Add support for adding quotas in the project-factory module
---
**Checklist**
> Add support for quotas to project-factory module

- fast/stages/2-project-factory/schemas/project.schema.md
- modules/project-factory/schemas/project.schema.json
fixed schema to allow iam_bindings_additive roles with "." ( eg roles/compute.admin)
---
**Checklist**
> fixed schema patter for iam_bindings_additive roles

- fast/stages/2-networking-a-simple/monitoring-vpn.tf
- fast/stages/2-networking-b-nva/monitoring-vpn-onprem.tf
- fast/stages/2-networking-c-separate-envs/monitoring-vpn-onprem.tf
This pull request migrates existing VPN alerting rules from Monitoring Query Language (MQL) to Prometheus Query Language (PromQL).
---
**Checklist**
> Migrated VPN alerting rules from MQL to PromQL

- modules/gke-cluster-standard/main.tf
- modules/gke-hub/README.md
For a GKE standard cluster with node auto provisioning disabled, the node_pool_auto_config settings are irrelevant and seeing the changes in terraform plan can be confusing.
With this PR, if the node auto provisioning is enabled then node_pool_auto_config settings will be applied otherwise not.
---
**Checklist**
> Provide node_pool_auto_config only when node auto provisioning is enabled for GKE standard cluster

- modules/project-factory/README.md
- modules/project-factory/automation.tf
- modules/project-factory/outputs.tf
- modules/project-factory/projects-service-accounts.tf
- modules/project-factory/sample-data-1/projects/app-0/dev-app0-be-0.yaml
- tests/modules/project_factory/examples/example.yaml
This PR adds some improvements to the new project factory module, some of which were highlighted by the GenAI factory which consumes it.
- add the `automation` prefix to automation resource keys (e.g. `$iam_principals:service_accounts/foo/automation/rw`)
- support cross-referencing automation service accounts in `iam_sa_roles` blocks
- add automation resources to projects output (fixes #3302)
**Breaking Changes**
```upgrade-note
`modules/project-factory`: automation resource keys now have the `/automation` prefix added between project key and resource key, e.g. `$iam_principals:service_accounts/foo/automation/rw`
```
> New project factory improvements

- fast/stages/0-org-setup/data/organization/org-policies/cloudbuild.yaml
Remove compute policy from cloudbuild file.
---
**Checklist**
> Cleanup 0-org-setup cloud build org-policies

- fast/stages/0-org-setup/schemas/project.schema.json
- modules/project-factory/README.md
- modules/project-factory/automation.tf
- modules/project-factory/outputs.tf
- modules/project-factory/projects-buckets.tf
- modules/project-factory/schemas/project.schema.json
- tests/modules/project_factory/examples/example.yaml
This PR rationalizes handling of prefix in project factory automation resources by
- skipping the global prefix in service account names, to simplify length constraints and adopt the convention used in the FAST org setup stage
- allowing to override prefix in storage buckets, so that an existing bucket can be referenced by "portable" key when defining managed folders and bucket creation is not wanted
A new subsection has been added to the project factory README to explain prefix behaviour for automation resources.
**Breaking Changes**
```upgrade-note
`modules/project-factory`: the format for automation service account names has changed.
```
> Rationalize prefix handling for project factory automation resources

- .pre-commit-config.yaml
With this change, `pre-commit` will create a dedicated virtual-environment with specified dependencies to run checks. Currently, it depends on the default interpreter having all dependencies installed from `tools/requirements.txt` 
---
**Checklist**
> Use pre-commit managed Python environment for pre-commit checks
