tests/foundations/business-units/__init__.py, tests/foundations/business-units/conftest.py, tests/foundations/business-units/terraform.tfvars, tests/foundations/business-units/test_folders.py, tests/foundations/business-units/test_outputs.py, tests/foundations/business-units/test_projects.py, tests/foundations/business-units/test_service_accounts.py
Simple tests for business-units example were added.
=> Add tests for business-units example

README.md, infrastructure/README.md, infrastructure/shared-vpc/README.md
Infrastructure README needs more work, but at least i's not empty.
=> Minimal rewording of top-level README, initial infrastructure README

foundations/business-units/main.tf, foundations/business-units/variables.tf, foundations/environments/main.tf, foundations/environments/variables.tf, infrastructure/shared-vpc/main.tf, infrastructure/shared-vpc/variables.tf, tests/foundations/business-units/test_projects.py, tests/foundations/environments/test_projects.py
This also fixes unit tests. If it's ok, we might merge and then rebase on master your PR that adds tests to hub and spoke, so that tests don't error out.
=> Update module versions, fix project service dependency

modules/bigquery/README.md, modules/bigquery/main.tf, modules/bigquery/outputs.tf, modules/bigquery/vars.tf
Opinionated BigQuery module with support for datasets, tables, views and dataset-level permissions.
=> BigQuery Module

.ci/cloudbuild.test.yaml, foundations/business-units/main.tf, foundations/business-units/modules/business-unit-folders/main.tf, foundations/environments/main.tf
Update folders, log sinks, service accounts versions to avoid errors with recent Terraform versions.
=> Update foundations modules versions

.ci/cloudbuild.lint.yaml, .ci/cloudbuild.test.yaml, modules/project/README.md, modules/project/main.tf, modules/project/variables.tf
This is a workaround to fix #31 while the GCP terraform provider is fixed
=> New project variable to prevent deletion of default network

.ci/cloudbuild.lint.yaml, .ci/cloudbuild.test.yaml, .ci/scripts/check_boilerplate.py, modules/compute-vm-cos-coredns/cloud-config-file.yaml, modules/gke-cluster/outputs.tf
=> Development fix ci

infrastructure/onprem-google-access-dns/assets/Corefile, infrastructure/onprem-google-access-dns/main.tf, infrastructure/onprem-google-access-dns/outputs.tf, infrastructure/onprem-google-access-dns/variables.tf, modules/on-prem-in-a-box/assets/Corefile, modules/on-prem-in-a-box/assets/dynamic-vpn-gw-cloud-init.yaml, modules/on-prem-in-a-box/assets/static-vpn-gw-cloud-init.yaml, modules/on-prem-in-a-box/main.tf, modules/on-prem-in-a-box/variables.tf
Hey Aleks, I simplified the module variables a bit, fixed a tiny error in the ipsec conf file (I remembered fixing the same originally and being puzzled on how to do it), and updated the example to use an external Corefile. If you like it, I will ad the cnames for private google access tomorrow, and add the sections on how to test the different features in the README.
=> Minor changes to onprem module and example

README.md, foundations/README.md, infrastructure/README.md
PR to track progress on README work for the development branch.
=> Update top-level and section READMEs

CHANGELOG.md, modules/organization/README.md, modules/organization/main.tf, modules/organization/outputs.tf, modules/organization/variables.tf, modules/organization/versions.tf, tests/modules/organization/__init__.py, tests/modules/organization/fixture/main.tf, tests/modules/organization/fixture/variables.tf, tests/modules/organization/test_plan.py
=> Organization module

foundations/environments/README.md, foundations/environments/outputs.tf
Outputs have been uncommented and updated
=> Update outputs for foundations/environments example

modules/gke-cluster/main.tf, modules/gke-cluster/variables.tf
=> Add peering route configuration support for private clusters

modules/source-repository/README.md, modules/source-repository/main.tf, modules/source-repository/outputs.tf, modules/source-repository/variables.tf, modules/source-repository/versions.tf
Initial version of a module for managing Source Repositories
=> Source repository module

modules/datafusion/README.md, modules/datafusion/main.tf, modules/datafusion/outputs.tf, modules/datafusion/variables.tf, modules/datafusion/versions.tf
=> First commit for Data Fusion module

modules/kms/README.md, modules/kms/main.tf, modules/kms/outputs.tf, modules/kms/variables.tf, tests/modules/kms/__init__.py, tests/modules/kms/fixture/main.tf, tests/modules/kms/fixture/outputs.tf, tests/modules/kms/fixture/variables.tf, tests/modules/kms/test_plan.py
This improves the KMS module in several ways
- keyring is now optional so that keys can be managed in an existing keyring
- keyring IAM
- specifying key purpose
- key labels
- outputs depend on relevant IAM bindings
It also removes the dual "protected" / "unprotected" key resources which were triggering spurious recreation in dependent resources, as reported by Lorenzo. A notice has been added in the README.
It goes without saying that this version is mostly incompatible with the previous one.
=> KMS module refactoring

modules/gcs/README.md, modules/gcs/main.tf, modules/gcs/outputs.tf, modules/gcs/variables.tf, tests/modules/gcs/fixture/variables.tf
Add Cloud KMS  support to GCS module
=> Add Cloud KMS  support to GCS module

modules/net-vpc/README.md, modules/net-vpc/main.tf, modules/net-vpc/variables.tf
This also changes some variable defaults with no impact on usage.
=> Set instance zone in net vpc route to avoid recreation

modules/compute-vm/main.tf
This PR includes the resolution to a bug which happens to be while creating a compute engine with reserved External IP
=> Reserved External IP-Compute VM

modules/gke-cluster/README.md, modules/gke-cluster/main.tf, modules/gke-cluster/variables.tf
This PR proposes a solution to fix issue #123 
Please let me know if you'd like me to make any changes.
=>  #123: Proposal to extend gke-module

CHANGELOG.md, modules/gcs/README.md, modules/gcs/main.tf, modules/gcs/variables.tf
This PR is to add retention policy for the bucket.
=> Add retention policy in gcs module

modules/gcs/README.md, modules/gcs/main.tf, modules/gcs/variables.tf
This PR is to add logging for buckets.
=> Add bucket logging

modules/vpc-sc/README.md, modules/vpc-sc/main.tf, modules/vpc-sc/outputs.tf, modules/vpc-sc/variables.tf
=> Minor vpc-sc module corrections

cloud-operations/scheduled-asset-inventory-export-bq/main.tf, data-solutions/gcs-to-bq-with-dataflow/main.tf, modules/bigquery-dataset/README.md, modules/bigquery-dataset/main.tf, modules/bigquery-dataset/variables.tf, tests/data_solutions/gcs_to_bq_with_dataflow/test_plan.py
=> Refactor access in bigquery-dataset module, add support for IAM

CHANGELOG.md, modules/folder/README.md, modules/folder/main.tf, modules/folder/outputs.tf, modules/folder/variables.tf, modules/organization/README.md, modules/organization/main.tf, modules/organization/outputs.tf, modules/organization/variables.tf, modules/project/README.md, modules/project/main.tf, modules/project/outputs.tf, modules/project/variables.tf
Add support for creating logging sinks and logging exclusions in the `project`, `folder` and `organization` modules
Fixes #161 and #163
=> Logging sinks and exclusions

cloud-operations/asset-inventory-feed-remediation/README.md, cloud-operations/asset-inventory-feed-remediation/variables.tf, networking/hub-and-spoke-peering/README.md, networking/hub-and-spoke-peering/main.tf, networking/hub-and-spoke-peering/outputs.tf, networking/hub-and-spoke-peering/variables.tf, tests/networking/hub_and_spoke_peering/fixture/main.tf, tests/networking/hub_and_spoke_peering/test_plan.py
This adds more flexibility to the hub and spoke peering example
=> Update hub and spoke peering to optionally create project

foundations/environments/main.tf, modules/project/README.md
iam_additive variable from Project module expects { "roles" = list(string) } input.
Therefore, I believe the issue #174 is till active
=> Fix wrong iam_addictive variable input

foundations/environments/main.tf, modules/project/README.md
This implements the last changes to merge #197, which fixed incorrect IAM additive in the environments foundation example, and the project module docs.
Fixes #174
=> Fix IAM additive

modules/organization/main.tf
=> Depend org module resources for policy etc from IAM bindings

modules/net-vpc-firewall-yaml/README.md, modules/net-vpc-firewall-yaml/main.tf, modules/net-vpc-firewall-yaml/outputs.tf, modules/net-vpc-firewall-yaml/variables.tf, modules/net-vpc-firewall-yaml/versions.tf
=> Added FW-Yaml module for distributed-firewall network example.

modules/vpc-sc/README.md, modules/vpc-sc/main.tf, modules/vpc-sc/variables.tf
It requires BeyondCorp Enterprise Premium. we will implement it in future iterations.
=> Remove Access Level device_policy configuration

.gitignore, modules/folder/README.md, modules/folder/main.tf, modules/folder/outputs.tf, modules/organization/README.md, modules/organization/main.tf, modules/organization/outputs.tf, modules/project/README.md, modules/project/main.tf, modules/project/outputs.tf, tests/modules/folder/test_plan_logging.py, tests/modules/organization/test_plan_logging.py, tests/modules/project/test_plan_logging.py
- Move to non-authoritative bindings to allow multiple sinks to write to
the same destination
- Allow automatically adding logging bucket IAM bindings
=> Fix IAM bindings for logging sinks

.ci/cloudbuild.test.environments.yaml, .ci/cloudbuild.test.examples.yaml, .ci/cloudbuild.test.modules.yaml, modules/gke-cluster/main.tf, networking/onprem-google-access-dns/main.tf
This only fixes errors raised by tests, some sensitive output issues might not have been caught here and will be fixed as they surface during regular usage.
=> Update to Terraform 0.15

third-party-solutions/openshift/prepare.py, third-party-solutions/openshift/tf/bootstrap.tf, third-party-solutions/openshift/tf/masters.tf, third-party-solutions/openshift/tf/variables.tf
=> Support labels in Openshift example

modules/vpc-sc/versions.tf
Fix min provider version for vpc-sc module
=> Fix min provider version for vpc-sc module

CHANGELOG.md, data-solutions/gcs-to-bq-with-dataflow/main.tf, modules/project/service_accounts.tf
Move `bq` robot service account into the robot service account project output
=> Move `bq` robot service account into the right project output

CHANGELOG.md, data-solutions/data-platform-foundations/README.md
This branch add the open-in-cloud-shell button to the main README file.
=> open-in-cloud-shell button added

CHANGELOG.md, modules/project/main.tf, modules/project/service_accounts.tf, tests/cloud_operations/scheduled_asset_inventory_export_bq/test_plan.py, tests/data_solutions/data_platform_foundations/test_plan.py
Create pubsub service identity if service is enabled.
=> Create pubsub service identity if service is enabled

modules/project/README.md, modules/project/main.tf, modules/project/outputs.tf, modules/project/variables.tf
Is this change independant enough ?
=> Add new variable for flexibility between project id & name

modules/dns/main.tf
This PR is to change list (deprecated in v0.15) into tolist (introduced in v0.12)
(see https://www.terraform.io/docs/language/functions/list.html)
=> Update list ==> tolist

modules/pubsub/README.md, modules/pubsub/variables.tf
Fixed type in max_delivery_attempts variable name.
=> Fixed typo in pubsub/variables.tf.

modules/net-vpc/README.md
Added a recommendation to avoid setting up shared vpcs using the module for prod usage.
=> Updated README.md for net-vpc module

networking/decentralized-firewall/validator/Dockerfile, networking/decentralized-firewall/validator/README.md, networking/decentralized-firewall/validator/action.yml, networking/decentralized-firewall/validator/firewallSchema.yaml, networking/decentralized-firewall/validator/firewallSchemaAutoApprove.yaml, networking/decentralized-firewall/validator/firewallSchemaSettings.yaml, networking/decentralized-firewall/validator/requirements.txt, networking/decentralized-firewall/validator/validator.py
- Based on Yamale YAML schema validator, written in Python 3.
- Also contains `action.yml` for use a GitHub Action.
=> Added decentralized firewall rule validator

data-solutions/data-platform-foundations/01-environment/README.md, data-solutions/data-platform-foundations/01-environment/main.tf, data-solutions/data-platform-foundations/01-environment/variables.tf, data-solutions/data-platform-foundations/02-resources/README.md, data-solutions/data-platform-foundations/02-resources/main.tf, data-solutions/data-platform-foundations/02-resources/providers.tf, data-solutions/data-platform-foundations/02-resources/variables.tf, data-solutions/data-platform-foundations/03-pipeline/gcs_to_bigquery.md, data-solutions/data-platform-foundations/03-pipeline/pubsub_to_bigquery.md, tests/data_solutions/data_platform_foundations/test_plan.py
- Fixed SA permissions
- Usage of impersonation to avoid SA private key export
- Fixed required API enablement
- Added FW rules required by dataflow
=> Bugfixing Data Foundations

CHANGELOG.md, README.md, modules/README.md, modules/naming-convention/README.md, modules/naming-convention/main.tf, modules/naming-convention/outputs.tf, modules/naming-convention/variables.tf, tests/modules/naming_convention/__init__.py, tests/modules/naming_convention/fixture/main.tf, tests/modules/naming_convention/test_plan.py
Julio, this is what we developed together a while ago minimally polished, with README and test. First building block of that thing we started working on.
=> Naming convention module

modules/folder/main.tf, modules/organization/main.tf, modules/project/main.tf
=> Depend log sinks from IAM roles

modules/net-vpc/README.md, modules/net-vpc/main.tf, modules/net-vpc/variables.tf, tests/modules/net_vpc/fixture/data/factory-subnet.yaml, tests/modules/net_vpc/fixture/main.tf, tests/modules/net_vpc/fixture/variables.tf, tests/modules/net_vpc/test_plan_subnets.py
This PR integrates a "mini-factory" to drive subnet creation from well-formed YaML files.
=> net-vpc module: added subnet mini-factory

modules/vpc-sc/README.md, modules/vpc-sc/main.tf
Fix VPC-SC module: properly handle bridge dry-run mode logic.
=> Fix VPC-SC module, add example

cloud-operations/scheduled-asset-inventory-export-bq/README.md, cloud-operations/scheduled-asset-inventory-export-bq/cf/main.py, cloud-operations/scheduled-asset-inventory-export-bq/main.tf, cloud-operations/scheduled-asset-inventory-export-bq/variables.tf, tests/cloud_operations/scheduled_asset_inventory_export_bq/fixture/variables.tf
**As A** solution architect
**I Need To** have variable Resource Manager node to point CAI Exporter at
**So That** I maintain flexibility between project to deploy and a node to report beneath. 
**Summary**
Adds new variable
=> Add target_node and minor fixes 

modules/folder/README.md, modules/folder/firewall-policy.tf, modules/folder/outputs.tf, modules/folder/variables.tf, modules/organization/README.md, modules/organization/firewall-policy.tf, modules/organization/outputs.tf, modules/organization/variables.tf, tests/modules/folder/fixture/main.tf, tests/modules/folder/fixture/variables.tf, tests/modules/folder/test_plan_firewall_policy.py, tests/modules/organization/fixture/main.tf, tests/modules/organization/fixture/variables.tf, tests/modules/organization/test_plan_firewall.py
This replaces all the `google_compute_organization_security_*`
resources with the newer `google_compute_firewall_*` resources.
=> Update hierarchical firewall resource

CHANGELOG.md, modules/project/service_accounts.tf
Add missing Service Identity Accounts: artifactregistry, composer.
=> Add missing Service Identity Accounts

tools/tfdoc.py
=> Fix extra newlines in tfdoc

tools/tfdoc.py
Support nullable variables in tfdoc
=> Support nullable variables in tfdoc

.github/workflows/linting.yml, .github/workflows/markdown-link-check.json, .github/workflows/tests.yml, README.md
- Removing old link checker stuff
- Activating linting and tests for fast-dev-gke
- Removing outbound links from README.md
=> Activate GHA for fast-dev-gke branch

fast/stages/02-networking-nva/vpc-landing.tf, fast/stages/02-networking-vpn/vpc-landing.tf
This will allow the project factory to link new projects to the landing project.
=> Use prod folder for landing project

examples/factories/project-factory/main.tf
Add a missing permission needed to actually create a gke cluster in the project
=> Update PF to grant network user to the cloud service agent when using gke

examples/factories/project-factory/README.md, examples/factories/project-factory/main.tf, examples/factories/project-factory/outputs.tf, examples/factories/project-factory/variables.tf
- Add GKE roles in the host project
- Use SA names from project module
- Add a few outputs
- Add prefix for project ids
=> Project factory fixes

fast/stages/00-bootstrap/README.md, fast/stages/00-bootstrap/billing.tf, fast/stages/00-bootstrap/organization.tf, fast/stages/00-bootstrap/outputs.tf, fast/stages/00-bootstrap/variables.tf, fast/stages/02-networking-vpn/vpc-spoke-dev.tf, fast/stages/02-networking-vpn/vpc-spoke-prod.tf
=> Allow specifying custom role names

fast/stages/03-project-factory/prod/README.md, fast/stages/03-project-factory/prod/main.tf, fast/stages/03-project-factory/prod/variables.tf
Related to #534. Includes project prefix to the PF stage
=> Use prefix for PF projects

.github/workflows/linting.yml, tools/check_boilerplate.py, tools/check_documentation.py, tools/check_links.py, tools/check_names.py, tools/requirements.txt, tools/state_iam.py, tools/tfdoc.py, tools/validate_schema.py
- Reformat code using yapf
- Add linting check
- Rename REQUIREMENTS.txt to requirements.txt
PD: yapf while I convince @ludoo to use Black 😀
=> Reformat python code using yapf

modules/dns/README.md
=> Fix broken link

modules/data-catalog-policy-tag/README.md, modules/data-catalog-policy-tag/iam.tf, modules/data-catalog-policy-tag/main.tf, modules/data-catalog-policy-tag/variables.tf
Data Catalog policy tag: Add IAM at tag level
=> Policy Tag: Add IAM at tag level

modules/folder/README.md, modules/folder/iam.tf, modules/folder/variables.tf, tests/modules/folder/fixture/main.tf, tests/modules/folder/fixture/variables.tf, tests/modules/folder/test_plan.py
=> Add support for IAM additive to folder module

examples/data-solutions/sqlserver-alwayson/README.md, examples/data-solutions/sqlserver-alwayson/instances.tf, examples/data-solutions/sqlserver-alwayson/main.tf, examples/data-solutions/sqlserver-alwayson/outputs.tf, examples/data-solutions/sqlserver-alwayson/scripts/functions.ps1, examples/data-solutions/sqlserver-alwayson/scripts/specialize-node.ps1, examples/data-solutions/sqlserver-alwayson/scripts/specialize-witness.ps1, examples/data-solutions/sqlserver-alwayson/scripts/windows-startup-node.ps1, examples/data-solutions/sqlserver-alwayson/scripts/windows-startup-witness.ps1, examples/data-solutions/sqlserver-alwayson/secrets.tf, examples/data-solutions/sqlserver-alwayson/service-accounts.tf, examples/data-solutions/sqlserver-alwayson/variables.tf, examples/data-solutions/sqlserver-alwayson/vpc.tf, tests/examples/data_solutions/sqlserver_alwayson/__init__.py, tests/examples/data_solutions/sqlserver_alwayson/fixture/main.tf, tests/examples/data_solutions/sqlserver_alwayson/fixture/variables.tf, tests/examples/data_solutions/sqlserver_alwayson/test_plan.py
A fully scripted out version of setting up SQL Server AlwaysOn availability groups.
=> SQL Server AlwaysOn availability groups example

fast/stages/00-bootstrap/outputs.tf, fast/stages/01-resman/branch-data-platform.tf, fast/stages/01-resman/branch-networking.tf, fast/stages/01-resman/branch-sandbox.tf, fast/stages/01-resman/branch-security.tf, fast/stages/01-resman/branch-teams.tf
This fixes a few cases where importing an existing resource fails. There might be others, we'll fix them as we find them.
=> Fix a few import errors in FAST

modules/cloudsql-instance/README.md, modules/cloudsql-instance/main.tf, modules/cloudsql-instance/variables.tf, modules/project/service-accounts.tf, tests/modules/cloudsql_instance/fixture/variables.tf, tests/modules/cloudsql_instance/test_plan.py
=> Add sqladmin to project jit_si and fix some documentation

modules/project/README.md
This adds some descriptive text for the project module and its examples, and adds a few extra examples that illustrate specific uses. It also fixes #471 .
=> Improve project module README

fast/stages/01-resman/organization.tf
These prevent deploying Cloud Functions and should probably be off by default.
=> FAST: disable some org policies

fast/assets/templates/workflow-gitlab.yaml, fast/stages/00-bootstrap/README.md, fast/stages/00-bootstrap/identity-providers.tf, fast/stages/00-bootstrap/outputs.tf, fast/stages/00-bootstrap/variables.tf, fast/stages/01-resman/variables.tf
- Added Gitlab CI Template
- Changed Identify Provider settings
- Fixed incorrect outputs
- Enabled Gitlab
=> FAST: added Gitlab CI template

examples/cloud-operations/network-dashboard/cloud-function/main.py, examples/cloud-operations/network-dashboard/cloud-function/metrics/ilb_fwrules.py, examples/cloud-operations/network-dashboard/cloud-function/metrics/instances.py, examples/cloud-operations/network-dashboard/cloud-function/metrics/limits.py, examples/cloud-operations/network-dashboard/cloud-function/metrics/metrics.py, examples/cloud-operations/network-dashboard/cloud-function/metrics/networks.py, examples/cloud-operations/network-dashboard/cloud-function/metrics/peerings.py, examples/cloud-operations/network-dashboard/cloud-function/metrics/routers.py, examples/cloud-operations/network-dashboard/cloud-function/metrics/routes.py
- Move functions from main.py into multiple separate files in the `metrics` directory
- introduce a config object to store clients, limits and other config objects
=> Refactor network dashboard to use multiple files

modules/net-vpc-firewall/README.md, modules/net-vpc-firewall/outputs.tf, tests/fast/stages/s03_data_platform/__init__.py, tools/tfdoc.py
fixes #647 also roll out for variables if tests pass
=> Fix tfdoc parsing on newllines in outputs

fast/assets/schemas/subnet.schema.yaml, modules/net-vpc/README.md
=> Fix subnet YAML schema and vpc module documentation

fast/stages/02-networking-nva/landing.tf, fast/stages/02-networking-nva/main.tf, fast/stages/02-networking-nva/spoke-dev.tf, fast/stages/02-networking-nva/spoke-prod.tf, fast/stages/02-networking-peering/landing.tf, fast/stages/02-networking-peering/main.tf, fast/stages/02-networking-peering/spoke-dev.tf, fast/stages/02-networking-peering/spoke-prod.tf, fast/stages/02-networking-vpn/landing.tf, fast/stages/02-networking-vpn/main.tf, fast/stages/02-networking-vpn/spoke-dev.tf, fast/stages/02-networking-vpn/spoke-prod.tf
=> Fix optional service accounts in networking stages

fast/stages/01-resman/billing.tf
Add billing.costsManager to the PF SAs to allow it to create billing alerts.
Fixes #720
=> FAST: Resman: Update billing.tf

modules/net-vpc/subnets.tf, tests/modules/net_vpc/test_plan_subnets.py
=> Avoid setting empty IAM binding in subnet factory

examples/data-solutions/data-platform-foundations/01-dropoff.tf
=> Fix dataset name

modules/vpc-sc/README.md
=> Add egress / ingress policy example to VPC SC module

fast/stages/00-cicd/outputs.tf
=> FAST: fix typo in CI/CD stage outputs.

blueprints/data-solutions/data-platform-foundations/README.md, modules/project/service-accounts.tf, tests/blueprints/data_solutions/data_platform_foundations/test_plan.py, tests/blueprints/gke/binauthz/test_plan.py
Project module: Add Artifactregistry Service Identity SA creation.
=> Project module: Add Artifactregistry Service Identity SA creation.

fast/stages/00-cicd/versions.tf
=> FAST: revert 00-cicd provider changes

FABRIC-AND-CFT.md, README.md
Convert existing document to markdown. Needs editing.
Fixes #862
=> Fabric vs CFT doc

.github/workflows/tests.yml, default-versions.tf, tests/test-versions.tf
This is just causing problems for little gain
=> Improve handling of tf plugin cache in tests

.github/workflows/tests.yml
Renaming some workflows to align CI to #808 
doc-examples -> examples
examples -> blueprints
=> Rename workflow names

modules/folder/logging.tf, modules/organization/logging.tf, modules/project/logging.tf
Fixes 990
PS: This is just an excuse to try the new automatic labeler
=> Only set partitioned table when sink type is bigquery

.github/workflows/container-image.yml
This PR adds OpenContainers annotations to our published container images.
Fixes #1011
=> Add OpenContainers annotations to published container images

fast/stages/00-bootstrap/README.md
=> Updating a small typo

fast/stages/FAQ.md
Common error when we have multiple identities
=> Adding new section for Authentication issues

blueprints/data-solutions/data-platform-foundations/README.md
Fix table in Data Platform README.
=> [Data Platform] Fix Table in readme

fast/stages/01-resman/outputs.tf
=> Fix destroy in stage 1 outputs

CHANGELOG.md, modules/gke-cluster/main.tf
=> Skip node config for autopilot

fast/stages-multitenant/0-bootstrap-tenant/templates/workflow-github.yaml, fast/stages-multitenant/1-resman-tenant/templates/workflow-github.yaml, fast/stages/0-bootstrap/templates/workflow-github.yaml, fast/stages/1-resman/templates/workflow-github.yaml
=> Post PR message in GitHub workflow on init or validate failure

modules/gke-hub/README.md
* Fix missing subnets and duplicate service account names for nodepools
* add fix for missing IAM role for fleet service account
* enable dataplane_v2 and workload_identity as they are required for Service Mesh
=> Fixes for service-mesh example in gke-hub

modules/gke-cluster/README.md, modules/gke-cluster/main.tf, modules/gke-cluster/variables.tf, tests/modules/gke_cluster/examples/dns.yaml
=> Fix gke-cluster dns config feature

modules/project/README.md
=> Remove unused attribute from project module README example

fast/stages/0-bootstrap/README.md
I did not have chance to test Gitlab URL
=> Add documentation about referring modules stored on CSR

.github/workflows/linting.yml, .github/workflows/release.yml, .github/workflows/tests.yml
Some of the versions we're using are deprecated
=> Bump actions versions

modules/net-vpn-ha/main.tf
This fixes an error with external gateways introduced in #1184.
=> Fix external gateway in VPN HA module

modules/net-vpc/README.md
=> Fix secondary ranges in net-vpc readme

modules/dataproc/outputs.tf
In this PR I fix Dataproc output cluster name
=> Dataproc module. Fix output.

blueprints/data-solutions/bq-ml/README.md, blueprints/data-solutions/data-playground/README.md, blueprints/data-solutions/vertex-mlops/README.md, modules/project/service-accounts.tf
In this PR I fix the creation of the JIT Notbook Service Account.
=> Fix JIT notebook service account.

blueprints/data-solutions/composer-2/README.md, blueprints/data-solutions/composer-2/variables.tf
In this PR we add [var.network_config.composer_ip_ranges](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/e4fc47a0633e5dea0cdbd9c3b2f399305340e9bf/blueprints/data-solutions/composer-2/composer.tf#L87) in the variable definition to fix issue https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/1236.
=> Composer-2 - Fix 1236

fast/stages/2-networking-b-vpn/vpn-spoke-dev.tf, fast/stages/2-networking-b-vpn/vpn-spoke-prod.tf
Re-add missing secret to spoke tunnels.
=> Fix FAST hub and spoke with VPN networking stage

fast/stages-multitenant/0-bootstrap-tenant/README.md, fast/stages-multitenant/1-resman-tenant/variables.tf, fast/stages/0-bootstrap/README.md
=> Allow longer org prefix plus tenant prefix

fast/extras/0-cicd-github/main.tf
=> Strip org name from deploy key repo in FAST cicd stage

modules/secret-manager/README.md, modules/secret-manager/main.tf, modules/secret-manager/variables.tf
This PR add CMEK support on Secret manager module
=> Add CMEK support on Secret manager module

modules/gke-cluster-standard/main.tf
=> Ignore entire node config in standard cluster

fast/stages/2-networking-e-nva-bgp/ncc.tf, modules/ncc-spoke-ra/versions.tf
PR to fix router priority typo
=> fix routes priority typo

modules/cloud-run/README.md, modules/cloud-run/main.tf, modules/cloud-run/variables.tf, tests/modules/cloud_run/examples/trigger-service-account-external.yaml, tests/modules/cloud_run/examples/trigger-service-account.yaml
Allows setting service account for triggers in Cloud Run
=> Add trigger SA for Cloud Run

fast/stages/0-bootstrap/templates/workflow-github.yaml
Issue: https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/1413
=> Bump GH TF version to coincide with module requirements

fast/stages/2-networking-a-peering/data/subnets/dev/dev-dataplatform-ew1.yaml, fast/stages/2-networking-b-vpn/data/subnets/dev/dev-dataplatform-ew1.yaml, fast/stages/2-networking-c-nva/data/subnets/dev/dev-dataplatform-ew1.yaml, fast/stages/2-networking-d-separate-envs/data/subnets/dev/dev-dataplatform-ew1.yaml, fast/stages/2-networking-e-nva-bgp/data/subnets/dev/dev-dataplatform-ew1.yaml
10.128.0.0/9 is public network.
Closes: #1424
=> Use RFC6598 addresses for pods and subnets

blueprints/data-solutions/sqlserver-alwayson/instances.tf, fast/stages/2-networking-e-nva-bgp/nva.tf, modules/compute-vm/README.md, modules/compute-vm/variables.tf
=> Make internal/external addresses optional in compute-vm

modules/folder/README.md, modules/organization/README.md, modules/project/README.md
This has been bugging me for a long time...
=> Add ToCs to resource manager modules

modules/net-lb-app-ext/README.md, modules/net-lb-app-ext/backends.tf, modules/net-lb-app-ext/groups.tf, modules/net-lb-app-int/README.md, modules/net-lb-app-int/groups.tf, modules/net-lb-app-int/main.tf, modules/net-lb-ext/groups.tf, modules/net-lb-ext/outputs.tf, modules/net-lb-int/outputs.tf
=> Align group names in lb modules

modules/cloud-function-v2/main.tf
=> Move IAM grant to function level for trigger SA

blueprints/data-solutions/data-platform-foundations/README.md
=> Add information about required groups

fast/stages/3-data-platform/dev/README.md
=> [Data Platform] Update README.md

tools/lint.sh
The script that was supposed to be included in #1640
=> Lint script

modules/__docs/20230816-iam-refactor.md
=> Add IAM variables template to ADR

fast/stages/1-resman/branch-tenants.tf
Fix tenant folder tag on 1-resman stage.
---
**Checklist**
=> [FAST] Fix tenant folder tag

fast/stages/2-networking-a-peering/data/hierarchical-ingress-rules.yaml, fast/stages/2-networking-b-vpn/data/hierarchical-ingress-rules.yaml, fast/stages/2-networking-c-nva/data/hierarchical-ingress-rules.yaml, fast/stages/2-networking-d-separate-envs/data/hierarchical-ingress-rules.yaml, fast/stages/2-networking-e-nva-bgp/data/hierarchical-ingress-rules.yaml
=> Fix indentation in FAST hierarchical firewall rules

modules/apigee/main.tf, tests/modules/apigee/env_only.yaml, tests/modules/apigee/env_only_with_api_proxy_type.yaml, tests/modules/apigee/env_only_with_deployment_type.yaml
Fixed problem in apigee module with try when attachments were being created
---
**Checklist**
- [X ] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [ X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [X ] Made sure all relevant tests pass
=> Apigee module fix try

blueprints/factories/project-factory/README.md, blueprints/factories/project-factory/factory.tf, blueprints/factories/project-factory/main.tf, tests/blueprints/factories/project_factory/examples/example.yaml
=> Add support for org policies to project factory

blueprints/data-solutions/data-platform-minimal/02-composer.tf, blueprints/data-solutions/data-platform-minimal/02-processing.tf, blueprints/data-solutions/data-platform-minimal/README.md, blueprints/data-solutions/data-platform-minimal/demo/README.md
In this PR I fix minor bug in the blueprint.
=> Minimal Data Platform - Fix

modules/pubsub/main.tf
Fixes #1742 
---
**Checklist**
=> Append "s" to pubsub backoff times

modules/net-vpc/README.md, modules/net-vpc/outputs.tf
=> Make subnets depend on proxy only subnets

modules/apigee/outputs.tf
Removed unnecessary try statements in apigee module outputs
---
**Checklist**
=> Removed unnecessary try statements from apigee module outputs

modules/apigee/README.md, modules/apigee/iam.tf, modules/apigee/main.tf, modules/apigee/variables.tf, tests/modules/apigee/all_psc_mode.yaml, tests/modules/apigee/all_vpc_mode.yaml
Added iam_bindings and iam_bindings_additive to apigee module
---
**Checklist**
=> Added iam_bindings and iam_bindings_additive to apigee module

blueprints/factories/project-factory/factory.tf
Simplify #1836 fix
---
**Checklist**
=> Simplify #1836 fix, Avoid map-related casting errors in project factory

modules/net-lb-app-ext/main.tf
Added create_before_destroy = true for self-managed certificates
---
**Checklist**
=> Added create_before_destroy = true for self-managed certificates

modules/cloud-config-container/envoy-sni-dyn-fwd-proxy/README.md, modules/cloud-config-container/envoy-sni-dyn-fwd-proxy/files/envoy.yaml, modules/cloud-config-container/envoy-sni-dyn-fwd-proxy/main.tf, modules/cloud-config-container/envoy-sni-dyn-fwd-proxy/outputs.tf, modules/cloud-config-container/envoy-sni-dyn-fwd-proxy/variables.tf, modules/cloud-config-container/envoy-sni-dyn-fwd-proxy/versions.tf
Added envoy as SNI dynamic forward proxy to cloud-config-container
---
**Checklist**
=> Added envoy as SNI dynamic forward proxy to cloud-config-container

blueprints/factories/project-factory/README.md, blueprints/factories/project-factory/factory.tf, blueprints/factories/project-factory/main.tf, tests/blueprints/factories/project_factory/examples/example.yaml
=> Support multilevel data and allow overriding project id in project factory

blueprints/data-solutions/data-platform-minimal/04-common.tf, blueprints/data-solutions/data-platform-minimal/README.md
Follow up on #1868 for data-platform-minimal - fix DLP Service Agent permissions.
---
**Checklist**
=> Add DLP Service Agent role

modules/cloud-config-container/envoy-sni-dyn-fwd-proxy/files/envoy.yaml
Fixed envoy file, it has extra character that was preventing envoy to start
---
**Checklist**
=> Fixed envoy file, it has extra character that was preventing envoy to start

modules/compute-vm/README.md, modules/compute-vm/main.tf, modules/compute-vm/tags.tf, modules/compute-vm/variables.tf
=> Add support for firewall tags to compute-vm module

fast/stages/0-bootstrap/templates/workflow-github.yaml, fast/stages/1-resman/templates/workflow-github.yaml
Following deprecation of google-github-actions/auth@v0 bump to V2 to fix warnings
---
**Checklist**
=> Patch Github actions ci google-github-actions/auth@v0 --> v2

blueprints/data-solutions/composer-2/README.md, blueprints/data-solutions/composer-2/composer.tf, blueprints/data-solutions/composer-2/main.tf, blueprints/data-solutions/composer-2/outputs.tf, blueprints/data-solutions/composer-2/variables.tf
* Add triggerer configuration for Composer
* make attributes optional where possibile
* added blueprint to E2E test suite
* other small improvements
---
**Checklist**
=> Add triggerer configuration for Composer

fast/stages/0-bootstrap/templates/workflow-github.yaml
=> Add debug step for JWT tokens

modules/gcve-private-cloud/README.md, modules/gcve-private-cloud/main.tf, modules/gcve-private-cloud/outputs.tf, tests/modules/gcve_private_cloud/examples/network-policy.yaml
Fixes errors in GCVE network policies
---
**Checklist**
=> Fix GCVE network policy

.github/workflows/linting.yml
Add version check to Linting workflow.
[Failed run](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/actions/runs/7320387984/job/19939429659)
---
**Checklist**
=> Add version check

tools/lint.sh
Follow up to comments in #1950
---
**Checklist**
=> Add version check to tools/lint.sh

tests/fixtures.py
=> Better error reporting when missing setup for E2E tests

fast/stages/0-bootstrap/data/org-policies/compute.yaml, tests/fast/stages/s0_bootstrap/checklist.yaml, tests/fast/stages/s0_bootstrap/simple.yaml
=> Enforce trusted image projects constraint in FAST bootstrap (CSPR-related)

fast/assets/templates/workflow-sourcerepo.yaml, fast/stages-multitenant/0-bootstrap-tenant/templates/workflow-sourcerepo.yaml, fast/stages-multitenant/1-resman-tenant/templates/workflow-sourcerepo.yaml, fast/stages/0-bootstrap/cicd.tf, fast/stages/0-bootstrap/templates/workflow-sourcerepo.yaml
=> Fix sourcerepo templates and concat call

modules/data-catalog-tag-template/README.md
Tag Template - Fix readme tests
---
**Checklist**
=> Tag Template - Fix readme tests

fast/stages/0-bootstrap/README.md
=> Clarify relationship with checklist groups in FAST bootstrap docs

fast/stages/0-bootstrap/data/org-policies/compute.yaml, fast/stages/0-bootstrap/data/org-policies/storage.yaml, tests/fast/stages/s0_bootstrap/checklist.yaml, tests/fast/stages/s0_bootstrap/simple.yaml
Fixes #2047
Fixes #2048
Fixes #2049
=> Enable additional recommended org policies

modules/data-catalog-tag/README.md, modules/data-catalog-tag/main.tf
Fix Data-Catalot Tag module
---
**Checklist**
=> Fix data-catalog tag module

modules/net-lb-app-ext/urlmap.tf
=> Do not convert route rules to set

modules/folder/README.md, modules/organization/README.md, modules/project/README.md, tests/modules/folder/examples/logging.yaml, tests/modules/organization/examples/logging.yaml, tests/modules/project/examples/logging.yaml
I don't know how I counted characters for #2108 
[E2E run](https://github.com/GoogleCloudPlatform/fast-e2e/actions/runs/8022645981)
---
**Checklist**
=> Once again fix e2e tests

modules/net-vpc/subnets.tf
[terraform-provider-google#16804](https://github.com/hashicorp/terraform-provider-google/issues/16804) is closed
---
**Checklist**
=> Remove ignore_changes as terraform-provider-google#16804 is closed

blueprints/cloud-operations/README.md
Fixed typo in /cloud-foundation-fabric/tree/master/blueprints/cloud-operations/README.md
---
**Checklist**
=> Update README.md (Fixed typos in /cloud-foundation-fabric/tree/master/blueprints/cloud-operations)

CONTRIBUTING.md
Updated CONTRIBUTING.md with a guide to cut a new release
=> Updated CONTRIBUTING.md with a guide to cut a new release

blueprints/networking/hub-and-spoke-peering/README.md, blueprints/networking/hub-and-spoke-vpn/README.md
=> Add stub READMEs for the removed hub and spoke blueprints

modules/net-cloudnat/README.md, modules/net-cloudnat/main.tf, modules/net-cloudnat/variables.tf
=> Support optional secondary ranges in net-cloudnat module

fast/stages/2-networking-c-nva/data/subnets/dmz/dmz-ew1.yaml, fast/stages/2-networking-c-nva/data/subnets/dmz/dmz-ew4.yaml, fast/stages/2-networking-c-nva/nva.tf, fast/stages/2-networking-c-nva/test-resources.tf
Fix to the changes in #2115 that are breaking FAST e2e.
=> Fix subnet names in FAST net stage c nva

modules/gcs/README.md, modules/gcs/tags.tf, modules/gcs/variables.tf, tests/modules/gcs/examples/tags.yaml
Partial fix for #2157 also minimally reworked the module's README.
=> Add support for tags to GCS module

modules/pubsub/README.md, modules/pubsub/main.tf, tests/modules/pubsub/examples/subscriptions.yaml
Closes: #2240 
---
**Checklist**
=> Use default labels on pubsub subscription when no override is provided

modules/vpc-sc/README.md, modules/vpc-sc/factory.tf, tests/modules/vpc_sc/examples/factory.yaml
=> Fix factory ingress policy services in vpc-sc module

fast/stages/0-bootstrap/README.md
=> Update docs - gcp-network-admins -> gcp-vpc-network-admins

modules/net-vpc/README.md
=> Fix failing E2E net-vpc test

fast/stages/0-bootstrap/organization-iam.tf, tests/fast/stages/s0_bootstrap/checklist.yaml, tests/fast/stages/s0_bootstrap/simple.yaml
=> Add wif permissions to bootstrap tf SA

fast/stages/0-bootstrap/organization.tf
=> Adjust list of imported org policies to official docs

tests/examples_e2e/setup_module/main.tf
=> Add AlloyDB service for e2e tests harness

fast/stages/0-bootstrap/data/org-policies/serverless.yaml
Fixes #2323 
@ludoo @sruffilli here's an example of something that goes through the factory but is not actually doing what it's supposed to.
=> Fix restrictAllowedGenerations org policy example

fast/stages/2-networking-b-nva/net-landing.tf, tests/fast/stages/s2_networking_b_nva/ncc-ra.yaml
Enable networkconnectivity when using NCC-RA in 2-b
=> FAST: Enable networkconnectivity when using NCC-RA in 2-b

modules/net-lb-app-int-cross-region/variables-backend-service.tf
---
**Checklist**
Since I only added missing validation values I don't see the need to regenerate docs, it won't do anything. (You can correct me if I'm wrong). By the way, there might be additional modules with the same issue, I haven't got around to use them yet so you might hear from me again soon.
Cheers 👍
=> Added missing validation values for backend services

blueprints/gke/patterns/batch/tutorial.md, blueprints/gke/patterns/kafka/tutorial.md, blueprints/gke/patterns/mysql/tutorial.md, blueprints/gke/patterns/redis-cluster/tutorial.md
=> Add Terraform installation step to meet the versions.tf requirements

modules/workstation-cluster/iam.tf
Minor fixes in workstations IAM
---
**Checklist**
=> Minor fixes in workstations IAM

fast/stages/0-bootstrap/README.md
=> Add wording for SCC Enterprise to FAST stage 0

modules/firestore/README.md, modules/firestore/main.tf, modules/firestore/outputs.tf, modules/firestore/variables.tf, modules/firestore/versions.tf, tests/modules/firestore/examples/existing-database-with-document.yaml, tests/modules/firestore/examples/new-database-with-document.yaml, tests/modules/firestore/examples/new-database-with-field.yaml, tests/modules/firestore/examples/new-database-with-index.yaml, tests/modules/firestore/examples/new-database-with-weekly-backup.yaml, tests/modules/firestore/examples/new-database.yaml
Added firestore module
---
**Checklist**
=> Added firestore module

blueprints/apigee/apigee-x-foundations/README.md, blueprints/factories/README.md, blueprints/gcve/pc-minimal/README.md, blueprints/gke/patterns/batch/README.md, blueprints/gke/patterns/batch/tutorial.md, blueprints/gke/patterns/kafka/README.md, blueprints/gke/patterns/mysql/README.md, fast/stages/1-resman/README.md, fast/stages/1-tenant-factory/README.md, fast/stages/3-gcve/prod/README.md, modules/__docs/20231106-factories.md, modules/firestore/variables.tf, modules/net-cloudnat/variables.tf, modules/net-lb-app-ext/README.md, modules/project-factory/README.md
---
**Checklist**
When applicable, I acknowledge that I have:
=> Several wording and typos updates 

modules/project/README.md, modules/project/service-agents.yaml
Follow up to #2248
---
**Checklist**
=> Add info about roles for connectors service agent

modules/project-factory/factory-projects.tf
Allow project factory projects to override name from yaml definition
=> Allow project factory projects to override name

modules/cloud-function-v2/README.md, tests/examples_e2e/setup_module/main.tf
Fix for broken tests from #2413
---
**Checklist**
=> Fix Cloud Function v1/v2 E2E tests

modules/cloud-function-v2/main.tf
=> Manage lifecycle of cloud functions v2 IAM

blueprints/factories/README.md
A minor typo in the Resource Factories README
---
**Checklist**
=> Typo in README: well know -> well-known

fast/stages/2-networking-a-simple/spoke-peerings.tf
=> Fix peering routes config in fast a network stage

modules/net-address/README.md, modules/net-address/psc.tf, modules/net-address/variables.tf, tests/modules/net_address/examples/psc-global.yaml
=> Add support for PSC global access to net-address

modules/cloudsql-instance/README.md
Adding dependency on the IAM grant, because on destroy, if the grant is removed before instance is deleted, instance deletion fails :shrug::
```
Error: Error, failed to delete instance db: Error waiting for Delete Instance: 
```
---
**Checklist**
=> Fix failing tests for CloudSQL

modules/project-factory/README.md, modules/project-factory/schemas/project.schema.json, modules/vpc-sc/README.md, tests/examples/conftest.py, tests/examples/test_plan.py, tests/examples/utils.py, tests/requirements.txt
@wiktorn I'm gonna need your help to ensure I'm not breaking the e2e stuff
=> Introduce YAML schema validation for YAML examples

modules/certificate-authority-service/main.tf
Fixes CAS module returning bad pool id while creating the CAs.
---
**Checklist**
=> [fix] certificate authority service returning bad pool id

modules/project/cmek.tf
A nasty typo which causes the module to crash
---
**Checklist**
=> project-cmek-smallfix

modules/project/cmek.tf
Yet another typo was found
---
**Checklist**
=> Fix CMEK typo in project module. Part 2 :)

modules/cloud-run-v2/README.md, modules/cloud-run/README.md, tests/fixtures/vpc-connector.tf
=> Fix e2e tests for cloud run

modules/secret-manager/README.md, modules/secret-manager/main.tf, modules/secret-manager/variables.tf
=> Support secret-level expire time in secret manager module

fast/stages/0-bootstrap/identity-providers-defs.tf
Added option to configure WIF for Terraform enterprise/HCP Terraform.
---
**Checklist**
=> added terraform enterprise/hcp terraform def to wif providers

fast/stages/0-bootstrap/identity-providers-defs.tf
Fixed the principal branch/repo for TFE. No assertion for branch, and repo is (currently) what is actually used to map
---
**Checklist**
=> fixed tfe wif definition variables

.github/workflows/linting.yml, .github/workflows/tests.yml
=> Extend tests to fast-dev

blueprints/apigee/bigquery-analytics/main.tf, blueprints/data-solutions/vertex-mlops/README.md, blueprints/data-solutions/vertex-mlops/ci-cd.tf, blueprints/data-solutions/vertex-mlops/variables.tf, modules/gcs/main.tf
Fix failing Vertex MLOps tests
---
**Checklist**
=> fix Vertex-ML-Ops e2e tests

blueprints/data-solutions/vertex-mlops/README.md, blueprints/data-solutions/vertex-mlops/main.tf, blueprints/data-solutions/vertex-mlops/vertex.tf
Fix IAM drift and example tests.
---
**Checklist**
=> Fix Vertex MLOps blueprint 

fast/stages/0-bootstrap/README.md
Small doc correction of some variable names.
Fixes #2679 
---
**Checklist**
=> Swap groups_iam/iam_group for iam_by_principals in bootstrap README

fast/README.md
=> Keeping my contributor status :)

modules/cloud-run-v2/README.md, tests/modules/cloud_run_v2/examples/gcs-mount.yaml, tests/modules/cloud_run_v2/examples/service-beta-features.yaml
Add E2E test case for direct vpc egress.
See: #2684
---
**Checklist**
=> Fix examples for GCS mount

modules/alloydb/main.tf
=> Fix typo on maintenance config

modules/net-swp/README.md, modules/net-swp/main.tf, modules/net-swp/outputs.tf, modules/net-swp/policy-rules.tf, modules/net-swp/schemas/policy-rule.schema.json, modules/net-swp/schemas/url-list.schema.json, modules/net-swp/variables.tf, tests/modules/net_swp/examples/basic.yaml, tests/modules/net_swp/examples/factories.yaml, tests/modules/net_swp/examples/psc.yaml, tests/modules/net_swp/examples/rules.yaml, tests/modules/net_swp/examples/tls-no-ip.yaml, tests/modules/net_swp/examples/tls.yaml
This streamlines the interface, and adds context-based substitutions and factories to the `net-swp` module.
=> SWP module refactor

fast/stages/1-resman/stage-2-networking.tf, fast/stages/1-resman/stage-2-security.tf, tests/fast/stages/s1_resman/simple.tfvars, tests/fast/stages/s1_resman/simple.yaml
=> Fix parent id lookup for networking and security in resource management stage

modules/net-lb-app-int/main.tf
Fixes #2760
Description of the problem and repro in the issue above.
=> Ignore ssl certificates if none are passed in net-lb-app-int module

tests/examples/test_plan.py
=> Fix failing tests for OpenTofu

modules/cloud-config-container/bindplane/README.md, modules/cloud-config-container/bindplane/cloud-config.yaml, modules/cloud-config-container/bindplane/main.tf, modules/cloud-config-container/bindplane/variables.tf
Fix bindplane module in cloud-config-container
=> Fix bindplane cos module

modules/certificate-authority-service/variables.tf
=> Fix validation message in cas module

blueprints/data-solutions/bq-ml/README.md, blueprints/data-solutions/data-playground/README.md, blueprints/data-solutions/vertex-mlops/README.md, modules/project/service-agents.yaml, tests/examples_e2e/setup_module/jit.tf.json, tests/examples_e2e/setup_module/main.tf, tools/build_service_agents.py
Fix to most of the errors related to service networking we're seeing in the e2e pipeline.
It seems we only have a 4 failures related to Cloud KMS that I can't figure out. @wiktorn can you take a look?
=> Fabric e2e fixes

blueprints/data-solutions/vertex-mlops/vertex.tf
=> fix non-empty plan after apply for vertex mlops

fast/assets/templates/workflow-github.yaml, fast/stages/0-bootstrap/templates/workflow-github.yaml, fast/stages/1-resman/templates/workflow-github.yaml, fast/stages/1-tenant-factory/templates/workflow-github.yaml, tools/versions.py
=> Simplify versions tf and update FAST workflows

modules/certificate-manager/README.md, modules/certificate-manager/outputs.tf
Closes #2829
---
**Checklist**
=> feat(certificate-manager): add dns_authorizations output

fast/stages/1-resman/outputs-cicd.tf
Small fixes for WIF and providers templating in git workflows.
---
**Checklist**
=> Workflow fix

fast/stages/UPGRADING.md
Documentation update for upgrade process, per #2873 
---
**Checklist**
=> Add note about the use of n-stagename/moved/ files during upgrade

modules/iam-service-account/main.tf, tests/modules/iam_service_account/tftest.yaml, tests/modules/iam_service_account/universe.tfvars, tests/modules/iam_service_account/universe.yaml
=> Add universe support to iam-service-accounts

blueprints/data-solutions/bq-ml/README.md, blueprints/data-solutions/data-playground/README.md, blueprints/data-solutions/vertex-mlops/README.md, modules/project/README.md, modules/project/service-agents.tf, modules/project/service-agents.yaml, tests/modules/gke_hub/examples/full.yaml, tests/modules/project/examples/basic.yaml, tests/modules/project/examples/data.yaml, tests/modules/project/examples/iam-authoritative.yaml, tests/modules/project/examples/shared-vpc-auto-grants.yaml, tests/modules/project/examples/shared-vpc-host-project-iam.yaml, tests/modules/project/examples/shared-vpc.yaml, tests/modules/project_factory/examples/example.yaml, tools/build_service_agents.py
=> Make service agents work in different universes

.github/pull_request_template.md, CHANGELOG.md, tools/changelog.py
=> Add breaking changes to changelog

modules/cloud-function-v1/README.md, modules/cloud-function-v1/outputs.tf, modules/cloud-function-v2/README.md, modules/cloud-function-v2/outputs.tf, modules/cloud-run-v2/README.md, modules/cloud-run-v2/outputs.tf, modules/cloud-run/README.md, modules/cloud-run/outputs.tf, modules/compute-vm/README.md, modules/compute-vm/outputs.tf
Add outputs to modules with commands helping to interact with created resources
---
**Checklist**
=> Add execution/invocation commands to outputs

modules/compute-vm/README.md, modules/gcs/README.md, tests/modules/compute_vm/examples/instance-schedule-create.yaml
And enable them as examples.
---
**Checklist**
=> Fix E2E tests using modules/project project_create

modules/vpc-sc/service-perimeters-regular.tf
=> Fix project ids in ingress policy resources

fast/stages/0-bootstrap/data/custom-roles/billing_viewer.yaml
=> fix(bootstrap): fix custom roles billing viewer duplicate permissions

modules/binauthz/README.md
=> Fixed title: from Artifact Registry to Binary Authorization

blueprints/data-solutions/README.md
Fix image link
---
**Checklist**
=> Fix broken link in GCP Data Services blueprints

fast/stages/2-networking-a-simple/README.md
=> Fast 2-networking-a README update

modules/project-factory/factory-projects.tf
*  `shared_vpc_service_config` and `vpc_sc` merges
---
**Checklist**
=> Use full type definition in project-factory

modules/project-factory/README.md, modules/project-factory/automation.tf, modules/project-factory/main.tf, tests/modules/project_factory/examples/example.yaml, tests/modules/project_factory/shared_vpc_network_user.yaml
=> Rationalize project factory context interpolations for automation service accounts

modules/project/shared-vpc.tf
=> Fix issue 2978

.github/workflows/linting.yml, .pre-commit-config.yaml, CHANGELOG.md, modules/project-factory/README.md, modules/project-factory/factory-projects-object.tf, modules/project-factory/factory-projects.tf, tools/duplicate-diff.py
=> Merge master to fast dev

tests/examples/test_plan.py
=> Improve failure message for tests

modules/vpc-sc/README.md
=> Better lifecycle management description in VPC-SC module

fast/stages/0-bootstrap/data/org-policies/compute.yaml, tests/fast/stages/s0_bootstrap/simple_org_policies.yaml
- [Confidential space images](https://cloud.google.com/confidential-computing/confidential-space/docs/confidential-space-images)
- [GKE Nodes Images](https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#node_image_source_projects)
---
**Checklist**
=> Add trusted images projects

fast/stages/0-bootstrap/data/org-policies-managed/storage.yaml, fast/stages/0-bootstrap/data/org-policies/storage.yaml, tests/fast/stages/s0_bootstrap/cicd.yaml, tests/fast/stages/s0_bootstrap/simple.yaml
=> Restrict HMAC keys in FAST

modules/secops-rules/README.md, modules/secops-rules/main.tf, modules/secops-rules/variables.tf, modules/secops-rules/versions.tf, modules/secops-rules/versions.tofu, tests/examples/variables.tf, tests/modules/secops_rules/examples/basic.yaml, tests/modules/secops_rules/examples/factory.yaml
=> secops-rules module

modules/net-vpc-factory/factory-projects-object.tf
=> Apply recent changes to factory-projects-object.tf to vpc-factory

fast/stages/1-resman/data/stage-2/project-factory.yaml
Small fix to allow the PF RO service account to read budget alerts.
---
**Checklist**
=> PF SA fix for budget alert

modules/net-vpc-factory/factory-projects-object.tf, modules/project-factory/automation.tf, modules/project-factory/factory-projects-object.tf, modules/project-factory/factory-projects.tf, tools/duplicate-diff.py
This fixes a regression introduced in #3030 and #3031
=> Fix automation object names in project factory

modules/dataplex-aspect-types/versions.tf, modules/dataplex-aspect-types/versions.tofu, modules/managed-kafka/README.md, modules/managed-kafka/main.tf, modules/managed-kafka/outputs.tf, modules/managed-kafka/variables.tf, modules/managed-kafka/versions.tf, modules/managed-kafka/versions.tofu, tests/examples/variables.tf, tests/modules/managed_kafka/examples/connect.yaml, tests/modules/managed_kafka/examples/simple.yaml, tests/modules/managed_kafka/examples/topics.yaml
=> New Managed Kafka module

fast/stages/0-bootstrap/data/org-policies-iac/iam.yaml, fast/stages/0-bootstrap/data/org-policies-managed/gcp.yaml, fast/stages/0-bootstrap/data/org-policies/gcp.yaml, tests/fast/stages/s0_bootstrap/cicd.yaml, tests/fast/stages/s0_bootstrap/simple.yaml
=> Relax WIF org policy in IaC project

modules/project-factory/automation.tf, modules/project-factory/schemas/project.schema.json
Reverts GoogleCloudPlatform/cloud-foundation-fabric#3091
=> Revert "Make automation project in project factory module optional"

CHANGELOG.md, fast/stages/2-project-factory/README.md, fast/stages/2-project-factory/outputs.tf, modules/project-factory/README.md, modules/project-factory/main.tf, modules/project-factory/outputs.tf, tests/modules/project_factory/examples/example.yaml
=> Add support for service agent expansion to project factory IAM

fast/stages/2-networking-a-simple/data/dns-policy-rules.yaml, fast/stages/2-networking-b-nva/data/dns-policy-rules.yaml, fast/stages/2-networking-c-separate-envs/data/dns-policy-rules.yaml
Reverts GoogleCloudPlatform/cloud-foundation-fabric#3179
=> Revert "Bypass accounts.google.com in FAST DNS policy rules"

fast/stages/1-vpcsc/main.tf
=> Only consider active projects to default VPC SC perimeter

modules/ai-applications/versions.tf, modules/ai-applications/versions.tofu
=> Fix ai-applications provider_meta

modules/project/main.tf
=> Fixed bug in project network tier resource, it was not working if the project was not created

fast/stages/0-org-setup/output-files.tf, modules/project-factory/README.md, modules/project-factory/outputs.tf
The missing outputs are depended on by consumers like the GenAI factory.
=> Add missing outputs to new project factory module, improve context README section

modules/apigee/README.md, modules/apigee/main.tf, modules/apigee/variables.tf, tests/modules/apigee/examples/access-logging.yaml
=> Add instance access logging support to apigee module

fast/stages/0-org-setup/data/folders/security/.config.yaml, tests/fast/stages/s0_org_setup/not-simple.yaml
=> Add conditional grants on security to pf service account in FAST stage 0

fast/stages/0-org-setup/assets/providers.tf.tpl
=> Fix typo in fast stage 0 provider template

fast/stages/2-security/README.md, fast/stages/2-security/factory-projects.tf, fast/stages/2-security/variables-fast.tf
=> Support universe in fast security stage

fast/stages/0-org-setup/README.md, modules/project-factory/README.md
=> Document log_buckets namespace

fast/stages/0-org-setup/README.md, fast/stages/0-org-setup/organization.tf, fast/stages/0-org-setup/schemas/organization.schema.json, modules/organization/README.md, modules/project-factory/projects.tf, modules/project-factory/schemas/project.schema.json, modules/project/README.md
=> Support iam_by_principals_additive in 0-org-setup
